import { defineConfig } from "vitest/config";

// The extension is a separate npm package and deliberately does NOT carry its
// own vitest install: a second copy of vitest + vite in extension/node_modules
// would double the install the CI extension job pays for, and this package's
// lockfile is regenerated by hand. `npm run test` therefore resolves the
// vitest binary from the repo root's node_modules (npm puts every ancestor
// node_modules/.bin on PATH for a run-script), so run `npm install` at the
// repo root once and this works from here.
//
// Only modules that import nothing from webextension-polyfill can be covered:
// that package IS in extension/node_modules and has no Node-side stub, so
// anything reaching browser.* needs a real extension host. tests/ is outside
// tsconfig.json's `include`, so nothing here is part of `npm run typecheck`.
export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"],
  },
});
