#!/usr/bin/env node
// Generate src/tokens.css from src/lib/tokens.json.
//
// popup.css imports the result and options.css imports popup.css, so this is
// the only place the extension's CSS variables are declared. Run from
// scripts/build.mjs before every build, and available as `npm run tokens`.
// The output is committed so a plain `vite dev` (which does not run
// build.mjs) still has a stylesheet to import.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const tokens = JSON.parse(
  await readFile(resolve(ROOT, "src/lib/tokens.json"), "utf8"),
);

const SEVERITY_KEYS = ["critical", "high", "medium", "low", "info"];

function themeBlock(theme, indent) {
  const t = tokens.themes[theme];
  return [
    `--vr-bg: ${t.bg};`,
    `--vr-card: ${t.card};`,
    `--vr-muted-bg: ${t.mutedBg};`,
    `--vr-text: ${t.text};`,
    `--vr-text-muted: ${t.textMuted};`,
    `--vr-border: ${t.border};`,
    `--vr-input: ${t.input};`,
    `--vr-primary: ${t.primary};`,
    `--vr-primary-text: ${t.primaryText};`,
    `--vr-primary-fg: ${t.primaryFg};`,
    `--vr-success: ${t.success};`,
    `--vr-warning: ${t.warning};`,
    `--vr-danger: ${t.danger};`,
    `--vr-info: ${t.info};`,
    ...SEVERITY_KEYS.map((k) => `--vr-sev-${k}: ${t.severity[k]};`),
    ...SEVERITY_KEYS.map((k) => `--vr-sev-${k}-text: ${t.severityText[k]};`),
  ]
    .map((line) => indent + line)
    .join("\n");
}

function metricsBlock(indent) {
  const m = tokens.metrics;
  return [
    `--vr-radius: ${m.radius};`,
    `--vr-radius-sm: ${m.radiusSm};`,
    `--vr-radius-pill: ${m.radiusPill};`,
    `--vr-font: ${m.font};`,
    `--vr-mono: ${m.mono};`,
    `--vr-shadow: ${m.shadow};`,
  ]
    .map((line) => indent + line)
    .join("\n");
}

// Per-severity chips. The badge shape lives in popup.css; only the hue
// changes here, so a severity retune is one edit in tokens.json.
//
// Two properties, not one: --vr-sev paints the tint, the border and the dot
// from the true severity hue, and --vr-sev-text paints the LABEL. On the light
// theme a label drawn in its own tint's hue lands between 3.6:1 and 4.3:1,
// under the 4.5:1 SC 1.4.3 asks of it, and darkening --vr-sev to fix that
// darkens the tint with it and gains almost nothing. See tokens.json's comment.
//
// The `[data-sev]` half exists because the chip was not the only thing painted
// by severity: the result panel's score and its risk word, and each finding
// row's left rail, took their colour from severityHex() in JS, which is the
// SOLID ramp (the dark theme's) whatever theme is actually showing. On the
// light card that put the risk word between 1.76:1 and 3.35:1. Anything that
// carries a severity now marks itself with data-sev and reads the same two
// variables the chip does, so it follows the theme.
function severityChips() {
  return SEVERITY_KEYS.map((k) =>
    [
      `.badge.${k},`,
      `[data-sev="${k}"] {`,
      `  --vr-sev: var(--vr-sev-${k});`,
      `  --vr-sev-text: var(--vr-sev-${k}-text);`,
      `}`,
    ].join("\n"),
  ).join("\n\n");
}

const css = [
  "/* GENERATED by scripts/gen-tokens.mjs from src/lib/tokens.json. */",
  "/* Do not edit: run `npm run tokens` after changing that file. */",
  "",
  ":root {",
  metricsBlock("  "),
  themeBlock("light", "  "),
  "}",
  "",
  "@media (prefers-color-scheme: dark) {",
  "  :root {",
  themeBlock("dark", "    "),
  "  }",
  "}",
  "",
  '[data-theme="light"] {',
  themeBlock("light", "  "),
  "}",
  "",
  '[data-theme="dark"] {',
  themeBlock("dark", "  "),
  "}",
  "",
  severityChips(),
  "",
].join("\n");

// Run the output through Prettier so the generated file satisfies
// `npm run format:check` in CI without anyone hand-tuning line breaks here.
await writeFile(
  resolve(ROOT, "src/tokens.css"),
  await format(css, { parser: "css" }),
  "utf8",
);
console.log("[tokens] src/tokens.css written from src/lib/tokens.json");
