blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/Y7R6hdGbNe
    about: Chat with maintainers and the community
  - name: Docs
    url: https://vulnradar.dev/docs
    about: Read the docs first
  - name: Security
    url: https://github.com/VulnRadar/vulnradar.dev/security/policy
    about: Report vulns privately
