import type { ScanResult, Severity, Vulnerability } from "@/lib/scanner/types";
import { APP_NAME, APP_URL } from "@/lib/config/constants";
import { getSafetyRating, type SafetyRating } from "@/lib/scanner/safety-rating";

/**
 * Markdown export.
 *
 * A human-readable report for pasting into a PR description, an issue, a
 * wiki, or a chat message: anywhere a rendered .md reads better than the
 * JSON/SARIF machine formats.
 *
 * Mirrors pdf-report.ts's shape: a single pure `generateMarkdownReport(result)`
 * function with no I/O, called client-side from the export menu exactly like
 * the existing JSON/CSV/PDF/SARIF exports (see scan-actions-menu.tsx). There
 * is no dedicated API route for any of those, so Markdown doesn't get one
 * either.
 */

const SEVERITY_ORDER: Severity[] = [
  "critical",
  "high",
  "medium",
  "low",
  "info",
];

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  info: "Info",
};

const SAFETY_LABEL: Record<SafetyRating, string> = {
  safe: "Safe to view",
  caution: "View with caution",
  unsafe: "Not safe to view",
};

function severityCounts(findings: Vulnerability[]): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  for (const finding of findings) {
    if (counts[finding.severity] !== undefined) counts[finding.severity] += 1;
  }
  return counts;
}

function findingSection(finding: Vulnerability): string[] {
  const lines: string[] = [
    `### ${finding.title} [${finding.severity.toUpperCase()}]`,
    "",
  ];

  if (finding.category) {
    lines.push(`Category: ${finding.category}`, "");
  }

  if (finding.description) {
    lines.push(finding.description, "");
  }

  if (finding.evidence) {
    if (finding.evidence.includes("\n")) {
      lines.push("Evidence:", "", "```", finding.evidence, "```", "");
    } else {
      lines.push(`Evidence: \`${finding.evidence}\``, "");
    }
  }

  if (finding.riskImpact) {
    lines.push(`Risk and impact: ${finding.riskImpact}`, "");
  }

  if (finding.aiVerdict) {
    const confidence =
      finding.aiConfidence !== undefined
        ? ` (confidence ${finding.aiConfidence}%)`
        : "";
    lines.push(`AI verdict: ${finding.aiVerdict}${confidence}`, "");
    if (finding.aiReason) lines.push(finding.aiReason, "");
  }

  if (finding.fixSteps && finding.fixSteps.length > 0) {
    lines.push("Fix:", "");
    finding.fixSteps.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
    lines.push("");
  }

  return lines;
}

export function generateMarkdownReport(result: ScanResult): string {
  const findings = result.findings ?? [];
  const lines: string[] = [`# Security report for ${result.url}`, ""];

  const scannedAt = result.scannedAt ? new Date(result.scannedAt) : null;
  const scannedLabel =
    scannedAt && !Number.isNaN(scannedAt.getTime())
      ? scannedAt.toLocaleString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
          hour: "2-digit",
          minute: "2-digit",
        })
      : "Unknown";
  lines.push(`Scanned: ${scannedLabel}`);

  if (result.dangerScore !== undefined) {
    lines.push(`Risk score: ${result.dangerScore}/10`);
  }

  const rating = getSafetyRating(findings);
  lines.push(`Safety rating: ${SAFETY_LABEL[rating]}`);

  const counts = severityCounts(findings);
  lines.push(
    `Findings: ${counts.critical} critical, ${counts.high} high, ${counts.medium} medium, ${counts.low} low, ${counts.info} info`,
    "",
    "---",
    "",
  );

  if (findings.length === 0) {
    lines.push("No findings. Every check passed.", "");
  } else {
    for (const severity of SEVERITY_ORDER) {
      const group = findings.filter((f) => f.severity === severity);
      if (group.length === 0) continue;
      lines.push(`## ${SEVERITY_LABEL[severity]} (${group.length})`, "");
      for (const finding of group) {
        lines.push(...findingSection(finding));
      }
    }
  }

  lines.push("---", "", `Generated by ${APP_NAME} (${APP_URL}).`, "");

  return lines.join("\n");
}
