// AUTO-GENERATED by scripts/knowledge/compile-checks-knowledge.mjs -- do not hand-edit.
// Regenerated on every `npm run build` / `npm run dev` (prebuild/predev hooks).

export const EXACT_LEGACY_CHECK_COUNT = 754;
export const EXACT_PAGE_CHECK_COUNT = 43;
export const EXACT_CHECK_COUNT = 797;
export const EXACT_CHECK_CATEGORY_COUNT = 18;
export const GENERATED_CHECKS_LABEL = "795+";

/**
 * Last commit date of each `lib/scanner/checks-data/<category>.json`, used
 * as the sitemap <lastmod> for that category's per-check pages. A category
 * missing here has no recorded source date and falls back to the build
 * timestamp in lib/seo/routes.ts.
 */
export const CHECK_CATEGORY_LAST_MODIFIED: Record<string, string> = {
  "active-probes": "2026-08-16",
  api: "2026-09-01",
  "client-side": "2026-09-01",
  code: "2026-09-01",
  configuration: "2026-08-12",
  content: "2026-09-01",
  cookies: "2026-08-15",
  dns: "2026-08-15",
  email: "2026-08-13",
  headers: "2026-09-01",
  "host-validation": "2026-08-13",
  "information-disclosure": "2026-09-01",
  reputation: "2026-08-12",
  "secrets-extended": "2026-08-13",
  ssl: "2026-08-12",
  "supply-chain": "2026-08-16",
  tls: "2026-08-15",
  "vibe-code": "2026-09-01",
};
