// Generated by scripts/assets/build-og-image.mjs. Do not edit by hand.
//
// Content hash of public/og-image.png, used to bust the caches that key on
// the image URL. Re-run the script whenever og-image.svg changes, or social
// platforms will keep serving the previous card.
export const OG_IMAGE_HASH = "5eccd8f1";
