// SETTINGS REGISTRY - the single description of every configurable value.
//
// Each entry classifies one `CONFIG_*` constant from config-values.ts into a
// tier and describes how it may be edited. The registry drives three things:
// the resolver's fallback (lib/config/runtime-config.ts), server-side
// validation on write, and (later) the admin settings form.
//
// Adding a configurable value means adding an entry here, not a bare
// constant. Constants that must never be edited at runtime are listed in
// NEVER_CONFIGURABLE below with the reason, so a reader can see they were
// considered rather than forgotten.

import { z } from "zod";

import {
  CONFIG_APP_NAME,
  CONFIG_APP_SLUG,
  CONFIG_APP_DESCRIPTION,
  CONFIG_TOTAL_CHECKS_LABEL,
  CONFIG_APP_URL,
  CONFIG_APP_REPO,
  CONFIG_DISCORD_INVITE_URL,
  CONFIG_SUPPORT_EMAIL,
  CONFIG_LEGAL_EMAIL,
  CONFIG_SECURITY_EMAIL,
  CONFIG_ENTERPRISE_EMAIL,
  CONFIG_NOREPLY_EMAIL,
  CONFIG_TERMS_UPDATED_AT,
  CONFIG_TERMS_CHANGE_SUMMARY,
  CONFIG_LOGO_URL,
  CONFIG_PRIMARY_COLOR,
  CONFIG_BACKGROUND_COLOR_DARK,
  CONFIG_BACKGROUND_COLOR_LIGHT,
  CONFIG_FOOTER_TEXT,
  CONFIG_SEO_TAGLINE,
  CONFIG_SEO_KEYWORDS,
  CONFIG_SEO_OG_IMAGE,
  CONFIG_SEO_OG_IMAGE_WIDTH,
  CONFIG_SEO_OG_IMAGE_HEIGHT,
  CONFIG_SEO_TWITTER_HANDLE,
  CONFIG_SEO_GITHUB_URL,
  CONFIG_SEO_GOOGLE_VERIFICATION,
  CONFIG_SEO_BING_VERIFICATION,
  CONFIG_SEO_LOCALE,
  CONFIG_SEO_LANGUAGE,
  CONFIG_SEO_ORG_FOUNDING_YEAR,
  CONFIG_SEO_LICENSE,
  CONFIG_SESSION_MAX_AGE_DAYS,
  CONFIG_VERSION_COOKIE_MAX_AGE_DAYS,
  CONFIG_NOTIFICATION_POLL_INTERVAL_MS,
  CONFIG_NOTIFICATION_DEFAULT_DISMISS_DAYS,
  CONFIG_SITE_NOTIFICATION_DEFAULT_DISMISS_DAYS,
  CONFIG_DEVICE_TRUST_MAX_AGE_DAYS,
  CONFIG_2FA_PENDING_MAX_AGE_SECONDS,
  CONFIG_EMAIL_2FA_CODE_EXPIRY_MINUTES,
  CONFIG_SESSION_IP_BINDING_ENABLED,
  CONFIG_SESSION_IP_BINDING_IPV4_PREFIX,
  CONFIG_SESSION_IP_BINDING_IPV6_PREFIX,
  CONFIG_API_KEY_IP_BINDING_ENABLED,
  CONFIG_API_KEY_IP_BINDING_IPV4_PREFIX,
  CONFIG_API_KEY_IP_BINDING_IPV6_PREFIX,
  CONFIG_SESSION_TIMEOUT_DAYS,
  CONFIG_PASSWORD_MIN_LENGTH,
  CONFIG_PASSWORD_RESET_HOURS,
  CONFIG_EMAIL_VERIFICATION_HOURS,
  CONFIG_DEVICE_TRUST_DAYS,
  CONFIG_DATA_EXPORT_COOLDOWN_DAYS,
  CONFIG_RATE_LIMIT_LOGIN_ATTEMPTS,
  CONFIG_RATE_LIMIT_LOGIN_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_SIGNUP_ATTEMPTS,
  CONFIG_RATE_LIMIT_SIGNUP_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_FORGOT_PASSWORD_ATTEMPTS,
  CONFIG_RATE_LIMIT_FORGOT_PASSWORD_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_API_REQUESTS,
  CONFIG_RATE_LIMIT_API_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_SCAN_REQUESTS,
  CONFIG_RATE_LIMIT_SCAN_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_BULK_SCAN_REQUESTS,
  CONFIG_RATE_LIMIT_BULK_SCAN_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_BROWSER_SESSION_ATTEMPTS,
  CONFIG_RATE_LIMIT_BROWSER_SESSION_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_AI_CHAT_ATTEMPTS,
  CONFIG_RATE_LIMIT_AI_CHAT_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_ADMIN_REAUTH_ATTEMPTS,
  CONFIG_RATE_LIMIT_ADMIN_REAUTH_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_BILLING_VERIFY_ATTEMPTS,
  CONFIG_RATE_LIMIT_BILLING_VERIFY_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_TEAM_INVITE_ATTEMPTS,
  CONFIG_RATE_LIMIT_TEAM_INVITE_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_AI_VERIFY_ATTEMPTS,
  CONFIG_RATE_LIMIT_AI_VERIFY_WINDOW_MINUTES,
  CONFIG_RATE_LIMIT_AI_SUMMARY_ATTEMPTS,
  CONFIG_RATE_LIMIT_AI_SUMMARY_WINDOW_MINUTES,
  CONFIG_MAX_URL_LENGTH,
  CONFIG_MAX_URLS_BULK,
  CONFIG_SCHEDULE_WORKER_BATCH_CONCURRENCY,
  CONFIG_SCAN_TIMEOUT_SECONDS,
  CONFIG_BULK_SCAN_TIMEOUT_SECONDS,
  CONFIG_CRAWL_SCAN_TIMEOUT_SECONDS,
  CONFIG_SCAN_STATUS_POLL_INTERVAL_MS,
  CONFIG_DEFAULT_SEVERITY_THRESHOLD,
  CONFIG_SCAN_AUTH_ENABLED,
  CONFIG_SCAN_AUTH_MAX_SECRET_LENGTH,
  CONFIG_SCAN_AUTH_MAX_COOKIES,
  CONFIG_SCAN_AUTH_VERIFY_TIMEOUT_MS,
  CONFIG_SCAN_AUTH_MAX_LOGIN_BODY_BYTES,
  CONFIG_SCAN_AUTH_MAX_COOKIE_AGE_SECONDS,
  CONFIG_SCAN_AUTH_BASELINE_DIFF_BYTES,
  CONFIG_SCAN_AUTH_BROWSER_NAV_TIMEOUT_MS,
  CONFIG_SCAN_AUTH_BROWSER_SETTLE_MS,
  CONFIG_SCAN_AUTH_BROWSER_MAX_WAIT_MS,
  CONFIG_SCAN_AUTH_BROWSER_SESSION_TIMEOUT_SECONDS,
  CONFIG_SCAN_AUTH_BROWSER_MAX_HTML_CHARS,
  CONFIG_DEFAULT_API_KEY_DAILY_LIMIT,
  CONFIG_AI_CHAT_MAX_TOKENS,
  CONFIG_AI_CHAT_HISTORY_DAYS,
  CONFIG_AI_CHAT_MAX_INPUT_LENGTH,
  CONFIG_AI_VERIFY_MAX_TOKENS,
  CONFIG_AI_VERIFY_CHUNK_SIZE,
  CONFIG_AI_VERIFY_CALL_TIMEOUT_MS,
  CONFIG_AI_VERIFY_PROBE_TIMEOUT_MS,
  CONFIG_AI_VERIFY_TOTAL_TIMEOUT_MS,
  CONFIG_AI_VERIFY_BATCH_MAX_FINDINGS,
  CONFIG_AI_SUMMARY_MAX_TOKENS,
  CONFIG_GITHUB_REVIEW_MAX_TOKENS_PER_RUN,
  CONFIG_GITHUB_REVIEW_MAX_FILES,
  CONFIG_GITHUB_REVIEW_MAX_TOTAL_BYTES,
  CONFIG_GITHUB_REVIEW_MAX_FILE_BYTES,
  CONFIG_BROWSERBASE_MAX_TTL_SECONDS,
  CONFIG_BROWSERBASE_DEFAULT_TTL_SECONDS,
  CONFIG_BROWSERBASE_LOGS_POLL_INTERVAL_MS,
  CONFIG_DEMO_SCAN_LIMIT,
  CONFIG_DEMO_WINDOW_HOURS,
  CONFIG_MAX_EMAIL_LENGTH,
  CONFIG_MAX_NAME_LENGTH,
  CONFIG_MAX_DESCRIPTION_LENGTH,
  CONFIG_MAX_TEAM_NAME_LENGTH,
  CONFIG_MAX_TAGS_PER_SCAN,
  CONFIG_MAX_TAG_LENGTH,
  CONFIG_TEAM_INVITE_EXPIRY_DAYS,
  CONFIG_PAGINATION_DEFAULT_PAGE_SIZE,
  CONFIG_PAGINATION_MAX_PAGE_SIZE,
  CONFIG_BETA_ENABLED,
  CONFIG_BETA_BANNER_MESSAGE,
  CONFIG_FEATURE_DEMO_MODE,
  CONFIG_FEATURE_TEAMS,
  CONFIG_FEATURE_API_KEYS,
  CONFIG_FEATURE_WEBHOOKS,
  CONFIG_FEATURE_SCHEDULED_SCANS,
  CONFIG_FEATURE_BULK_SCANS,
  CONFIG_FEATURE_PDF_REPORTS,
  CONFIG_FEATURE_EMAIL_NOTIFICATIONS,
  CONFIG_BILLING_ENABLED,
  CONFIG_BILLING_FREE_LIMIT,
  CONFIG_BILLING_CORE_SUPPORTER_LIMIT,
  CONFIG_BILLING_PRO_SUPPORTER_LIMIT,
  CONFIG_BILLING_ELITE_SUPPORTER_LIMIT,
  CONFIG_BILLING_FREE_RETENTION,
  CONFIG_BILLING_CORE_SUPPORTER_RETENTION,
  CONFIG_BILLING_PRO_SUPPORTER_RETENTION,
  CONFIG_BILLING_ELITE_SUPPORTER_RETENTION,
  CONFIG_BILLING_UNLIMITED_MODE_LIMIT,
  CONFIG_BILLING_VERIFY_CODE_EXPIRY_MINUTES,
  CONFIG_BILLING_FREE_API_KEYS,
  CONFIG_BILLING_CORE_SUPPORTER_API_KEYS,
  CONFIG_BILLING_PRO_SUPPORTER_API_KEYS,
  CONFIG_BILLING_ELITE_SUPPORTER_API_KEYS,
  CONFIG_BILLING_FREE_API_REQUESTS_PER_DAY,
  CONFIG_BILLING_CORE_SUPPORTER_API_REQUESTS_PER_DAY,
  CONFIG_BILLING_PRO_SUPPORTER_API_REQUESTS_PER_DAY,
  CONFIG_BILLING_ELITE_SUPPORTER_API_REQUESTS_PER_DAY,
  CONFIG_BILLING_FREE_TEAMS,
  CONFIG_BILLING_CORE_SUPPORTER_TEAMS,
  CONFIG_BILLING_PRO_SUPPORTER_TEAMS,
  CONFIG_BILLING_ELITE_SUPPORTER_TEAMS,
  CONFIG_BILLING_FREE_TEAM_MEMBERS,
  CONFIG_BILLING_CORE_SUPPORTER_TEAM_MEMBERS,
  CONFIG_BILLING_PRO_SUPPORTER_TEAM_MEMBERS,
  CONFIG_BILLING_ELITE_SUPPORTER_TEAM_MEMBERS,
  CONFIG_BILLING_FREE_WEBHOOKS,
  CONFIG_BILLING_CORE_SUPPORTER_WEBHOOKS,
  CONFIG_BILLING_PRO_SUPPORTER_WEBHOOKS,
  CONFIG_BILLING_ELITE_SUPPORTER_WEBHOOKS,
  CONFIG_BILLING_FREE_SCHEDULED_SCANS,
  CONFIG_BILLING_CORE_SUPPORTER_SCHEDULED_SCANS,
  CONFIG_BILLING_PRO_SUPPORTER_SCHEDULED_SCANS,
  CONFIG_BILLING_ELITE_SUPPORTER_SCHEDULED_SCANS,
  CONFIG_BILLING_FREE_BULK_SCAN_URLS,
  CONFIG_BILLING_CORE_SUPPORTER_BULK_SCAN_URLS,
  CONFIG_BILLING_PRO_SUPPORTER_BULK_SCAN_URLS,
  CONFIG_BILLING_ELITE_SUPPORTER_BULK_SCAN_URLS,
  CONFIG_BILLING_FREE_GITHUB_REVIEW_TOKENS_PER_MONTH,
  CONFIG_BILLING_CORE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
  CONFIG_BILLING_PRO_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
  CONFIG_BILLING_ELITE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
} from "./config-values";

/**
 * "runtime" takes effect within the resolver cache TTL with no deploy.
 * "build" is baked into statically generated HTML, so an edit applies on the
 * next build. Both are editable by an admin; only the propagation differs.
 */
export type SettingTier = "runtime" | "build";

export type SettingType =
  "string" | "int" | "bool" | "float" | "email" | "url" | "enum";

/** One admin tab per group. The tab list is derived from these values. */
export type SettingGroup =
  | "General"
  | "Branding"
  | "SEO"
  | "Features"
  | "Billing"
  | "Rate Limits"
  | "Scanning"
  | "Authentication"
  | "AI"
  | "Demo"
  | "Advanced";

export interface SettingDefinition {
  tier: SettingTier;
  type: SettingType;
  /**
   * The shipped value. Always the imported CONFIG_ constant so the registry
   * cannot drift from config-values.ts.
   */
  default: string | number | boolean;
  group: SettingGroup;
  label: string;
  help: string;
  /** Numeric types: value bounds. String types: length bounds. */
  min?: number;
  max?: number;
  /** Allowed values for `type: "enum"`. */
  options?: readonly string[];
}

export const SETTINGS_REGISTRY = {
  // GENERAL

  APP_NAME: {
    tier: "build",
    type: "string",
    default: CONFIG_APP_NAME,
    group: "General",
    label: "Application name",
    help: "Shown in page titles, emails, and the TOTP issuer. Client bundles inline it, so it applies on the next build.",
    min: 1,
    max: 64,
  },
  APP_SLUG: {
    tier: "build",
    type: "string",
    default: CONFIG_APP_SLUG,
    group: "General",
    label: "Application slug",
    help: "Lowercase identifier used in generated filenames and machine-readable output.",
    min: 1,
    max: 64,
  },
  APP_DESCRIPTION: {
    tier: "build",
    type: "string",
    default: CONFIG_APP_DESCRIPTION,
    group: "General",
    label: "Application description",
    help: "Default meta description for pages that do not set their own.",
    min: 1,
    max: 500,
  },
  TOTAL_CHECKS_LABEL: {
    tier: "build",
    type: "string",
    default: CONFIG_TOTAL_CHECKS_LABEL,
    group: "General",
    label: "Total checks label",
    help: 'Marketing count of scanner checks, for example "650+".',
    min: 1,
    max: 32,
  },
  APP_URL: {
    tier: "build",
    type: "url",
    default: CONFIG_APP_URL,
    group: "General",
    label: "Public application URL",
    help: "Origin used for canonical URLs, social cards, and email links; those are baked into built pages, so they only pick up a change here on the next build and deploy. The GitHub/Google/Discord sign-in redirect is the one exception: it reads this value live, no rebuild needed. No trailing slash.",
  },
  APP_REPO: {
    tier: "build",
    type: "string",
    default: CONFIG_APP_REPO,
    group: "General",
    label: "Source repository",
    help: 'GitHub "owner/name" used for the releases feed and the version check.',
    min: 3,
    max: 128,
  },
  DISCORD_INVITE_URL: {
    tier: "build",
    type: "url",
    default: CONFIG_DISCORD_INVITE_URL,
    group: "General",
    label: "Discord invite URL",
    help: "Community link shown in the footer and support pages.",
  },
  TERMS_UPDATED_AT: {
    tier: "runtime",
    type: "string",
    default: CONFIG_TERMS_UPDATED_AT,
    group: "General",
    label: "Terms last updated",
    help: "Date shown on the terms page, in YYYY-MM-DD form. Raising this past a user's stored acceptance date makes them re-accept on their next page load, no rebuild needed. A future date does not delay the prompt: it still applies now, so every current user is asked to re-accept immediately.",
    min: 10,
    max: 10,
  },
  TERMS_CHANGE_SUMMARY: {
    tier: "runtime",
    type: "string",
    default: CONFIG_TERMS_CHANGE_SUMMARY,
    group: "General",
    label: "Terms change summary",
    help: 'Short note shown in the "what changed" callout of the re-accept prompt, alongside Terms last updated. Leave empty to hide that callout.',
    max: 300,
  },
  SUPPORT_EMAIL: {
    tier: "runtime",
    type: "email",
    default: CONFIG_SUPPORT_EMAIL,
    group: "General",
    label: "Support email",
    help: "Address shown to users who need help and used as the reply-to on support mail.",
  },
  LEGAL_EMAIL: {
    tier: "runtime",
    type: "email",
    default: CONFIG_LEGAL_EMAIL,
    group: "General",
    label: "Legal email",
    help: "Contact address on the terms and privacy pages.",
  },
  SECURITY_EMAIL: {
    tier: "runtime",
    type: "email",
    default: CONFIG_SECURITY_EMAIL,
    group: "General",
    label: "Security email",
    help: "Address published in security.txt for vulnerability reports.",
  },
  ENTERPRISE_EMAIL: {
    tier: "runtime",
    type: "email",
    default: CONFIG_ENTERPRISE_EMAIL,
    group: "General",
    label: "Enterprise email",
    help: "Sales contact for enterprise enquiries.",
  },
  NOREPLY_EMAIL: {
    tier: "runtime",
    type: "email",
    default: CONFIG_NOREPLY_EMAIL,
    group: "General",
    label: "No-reply email",
    help: "From address on automated mail. Must be a domain your SMTP relay is allowed to send as.",
  },

  // BRANDING

  LOGO_URL: {
    tier: "build",
    type: "string",
    default: CONFIG_LOGO_URL,
    group: "Branding",
    label: "Logo URL",
    help: "Absolute URL or a path relative to the app root. Used in emails and structured data.",
    min: 1,
    max: 512,
  },
  PRIMARY_COLOR: {
    tier: "build",
    type: "string",
    default: CONFIG_PRIMARY_COLOR,
    group: "Branding",
    label: "Primary colour",
    help: "Hex colour for the PWA theme and browser UI tint. Keep it in sync with --primary in globals.css.",
    min: 4,
    max: 9,
  },
  BACKGROUND_COLOR_DARK: {
    tier: "build",
    type: "string",
    default: CONFIG_BACKGROUND_COLOR_DARK,
    group: "Branding",
    label: "Dark background colour",
    help: "Hex colour reported to the browser for dark mode.",
    min: 4,
    max: 9,
  },
  BACKGROUND_COLOR_LIGHT: {
    tier: "build",
    type: "string",
    default: CONFIG_BACKGROUND_COLOR_LIGHT,
    group: "Branding",
    label: "Light background colour",
    help: "Hex colour reported to the browser for light mode.",
    min: 4,
    max: 9,
  },
  FOOTER_TEXT: {
    tier: "build",
    type: "string",
    default: CONFIG_FOOTER_TEXT,
    group: "Branding",
    label: "Footer text",
    help: "Short line rendered in the site footer.",
    min: 1,
    max: 200,
  },

  // SEO

  SEO_TAGLINE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_TAGLINE,
    group: "SEO",
    label: "Tagline",
    help: "Short pitch used as the default meta description and OpenGraph description.",
    min: 1,
    max: 200,
  },
  SEO_KEYWORDS: {
    tier: "build",
    type: "string",
    // Stored as one comma-separated string: the registry has no list type.
    // Consumers split on "," when they need the array form.
    default: CONFIG_SEO_KEYWORDS.join(", "),
    group: "SEO",
    label: "Keywords",
    help: "Comma-separated terms to rank for. Keep them honest: stuffing unrelated terms is penalised.",
    max: 1000,
  },
  SEO_OG_IMAGE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_OG_IMAGE,
    group: "SEO",
    label: "Social card image",
    help: "Path relative to the app root. 1200x630 renders without cropping on every major network.",
    min: 1,
    max: 512,
  },
  SEO_OG_IMAGE_WIDTH: {
    tier: "build",
    type: "int",
    default: CONFIG_SEO_OG_IMAGE_WIDTH,
    group: "SEO",
    label: "Social card width",
    help: "Pixel width declared to social networks. Must match the real image.",
    min: 200,
    max: 4096,
  },
  SEO_OG_IMAGE_HEIGHT: {
    tier: "build",
    type: "int",
    default: CONFIG_SEO_OG_IMAGE_HEIGHT,
    group: "SEO",
    label: "Social card height",
    help: "Pixel height declared to social networks. Must match the real image.",
    min: 200,
    max: 4096,
  },
  SEO_TWITTER_HANDLE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_TWITTER_HANDLE,
    group: "SEO",
    label: "Twitter handle",
    help: "Leave empty to omit the Twitter card attribution tags entirely.",
    max: 64,
  },
  SEO_GITHUB_URL: {
    tier: "build",
    type: "url",
    default: CONFIG_SEO_GITHUB_URL,
    group: "SEO",
    label: "GitHub URL",
    help: "Repository link used in structured data and the footer.",
  },
  SEO_GOOGLE_VERIFICATION: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_GOOGLE_VERIFICATION,
    group: "SEO",
    label: "Google verification token",
    help: "Search Console ownership token. Leave empty to skip the meta tag.",
    max: 128,
  },
  SEO_BING_VERIFICATION: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_BING_VERIFICATION,
    group: "SEO",
    label: "Bing verification token",
    help: "Bing Webmaster ownership token. Leave empty to skip the meta tag.",
    max: 128,
  },
  SEO_LOCALE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_LOCALE,
    group: "SEO",
    label: "OpenGraph locale",
    help: 'Locale the content targets, for example "en_US".',
    min: 2,
    max: 16,
  },
  SEO_LANGUAGE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_LANGUAGE,
    group: "SEO",
    label: "HTML language",
    help: 'Value of the lang attribute on the html element, for example "en".',
    min: 2,
    max: 16,
  },
  SEO_ORG_FOUNDING_YEAR: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_ORG_FOUNDING_YEAR,
    group: "SEO",
    label: "Founding year",
    help: "Year used in the JSON-LD Organization node.",
    min: 4,
    max: 4,
  },
  SEO_LICENSE: {
    tier: "build",
    type: "string",
    default: CONFIG_SEO_LICENSE,
    group: "SEO",
    label: "Licence",
    help: "SPDX identifier published in the structured data.",
    min: 1,
    max: 64,
  },

  // FEATURES

  FEATURE_DEMO_MODE: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_DEMO_MODE,
    group: "Features",
    label: "Demo scans",
    help: "Lets signed-out visitors run a limited number of scans.",
  },
  FEATURE_TEAMS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_TEAMS,
    group: "Features",
    label: "Teams",
    help: "Turning this off hides team pages from users who already belong to a team.",
  },
  FEATURE_API_KEYS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_API_KEYS,
    group: "Features",
    label: "API keys",
    help: "Turning this off stops users issuing new keys. Existing integrations break.",
  },
  FEATURE_WEBHOOKS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_WEBHOOKS,
    group: "Features",
    label: "Webhooks",
    help: "Outbound scan-complete notifications to user-supplied endpoints.",
  },
  FEATURE_SCHEDULED_SCANS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_SCHEDULED_SCANS,
    group: "Features",
    label: "Scheduled scans",
    help: "Recurring scans on a cron schedule.",
  },
  FEATURE_BULK_SCANS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_BULK_SCANS,
    group: "Features",
    label: "Bulk scans",
    help: "Scanning many URLs in one submission.",
  },
  FEATURE_PDF_REPORTS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_PDF_REPORTS,
    group: "Features",
    label: "PDF reports",
    help: "Downloadable PDF export of a scan result.",
  },
  FEATURE_EMAIL_NOTIFICATIONS: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_FEATURE_EMAIL_NOTIFICATIONS,
    group: "Features",
    label: "Email notifications",
    help: "Transactional mail other than authentication. Security mail is always sent.",
  },

  // BILLING

  BILLING_ENABLED: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_BILLING_ENABLED,
    group: "Billing",
    label: "Billing enabled",
    help: "Turning this off gives every user the unlimited-mode limit and hides pricing.",
  },
  BILLING_FREE_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_LIMIT,
    group: "Billing",
    label: "Free plan daily scans",
    help: "Scans per day on the free plan. Use -1 for unlimited.",
    min: -1,
    max: 100000,
  },
  BILLING_CORE_SUPPORTER_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_LIMIT,
    group: "Billing",
    label: "Core supporter daily scans",
    help: "Scans per day on the core supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 100000,
  },
  BILLING_PRO_SUPPORTER_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_LIMIT,
    group: "Billing",
    label: "Pro supporter daily scans",
    help: "Scans per day on the pro supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 100000,
  },
  BILLING_ELITE_SUPPORTER_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_LIMIT,
    group: "Billing",
    label: "Elite supporter daily scans",
    help: "Scans per day on the elite supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 100000,
  },
  BILLING_FREE_RETENTION: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_RETENTION,
    group: "Billing",
    label: "Free plan history retention",
    help: "Days of scan history kept on the free plan. Use -1 to keep it forever. Lowering this deletes older scans on the next cleanup.",
    min: -1,
    max: 3650,
  },
  BILLING_CORE_SUPPORTER_RETENTION: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_RETENTION,
    group: "Billing",
    label: "Core supporter history retention",
    help: "Days of scan history kept on the core supporter plan. Use -1 to keep it forever.",
    min: -1,
    max: 3650,
  },
  BILLING_PRO_SUPPORTER_RETENTION: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_RETENTION,
    group: "Billing",
    label: "Pro supporter history retention",
    help: "Days of scan history kept on the pro supporter plan. Use -1 to keep it forever.",
    min: -1,
    max: 3650,
  },
  BILLING_ELITE_SUPPORTER_RETENTION: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_RETENTION,
    group: "Billing",
    label: "Elite supporter history retention",
    help: "Days of scan history kept on the elite supporter plan. Use -1 to keep it forever.",
    min: -1,
    max: 3650,
  },
  BILLING_UNLIMITED_MODE_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_UNLIMITED_MODE_LIMIT,
    group: "Billing",
    label: "Unlimited mode daily scans",
    help: "Daily cap applied to everyone when billing is disabled. Use -1 for no cap.",
    min: -1,
    max: 100000,
  },
  BILLING_VERIFY_CODE_EXPIRY_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_VERIFY_CODE_EXPIRY_MINUTES,
    group: "Billing",
    label: "Billing verification code lifetime (minutes)",
    help: "How long the emailed 6-digit billing verification code stays valid. Keep it at or below the billing verify rate-limit window.",
    min: 1,
    max: 60,
  },

  // Per-resource plan limits. Every field below is enforced live by
  // lib/billing/plan-limits.ts at the point a user tries to create the
  // resource (a new API key, webhook, scheduled scan, team, or team
  // member invite). -1 means unlimited, 0 means the plan does not get the
  // resource at all.

  BILLING_FREE_API_KEYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_API_KEYS,
    group: "Billing",
    label: "Free plan API keys",
    help: "Active API keys a free-plan user may have at once. Use -1 for unlimited, 0 to disable API keys on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_CORE_SUPPORTER_API_KEYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_API_KEYS,
    group: "Billing",
    label: "Core supporter API keys",
    help: "Active API keys a core supporter may have at once. Use -1 for unlimited, 0 to disable API keys on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_PRO_SUPPORTER_API_KEYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_API_KEYS,
    group: "Billing",
    label: "Pro supporter API keys",
    help: "Active API keys a pro supporter may have at once. Use -1 for unlimited, 0 to disable API keys on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_ELITE_SUPPORTER_API_KEYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_API_KEYS,
    group: "Billing",
    label: "Elite supporter API keys",
    help: "Active API keys an elite supporter may have at once. Use -1 for unlimited, 0 to disable API keys on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_FREE_API_REQUESTS_PER_DAY: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_API_REQUESTS_PER_DAY,
    group: "Billing",
    label: "Free plan API requests per day",
    help: "Daily request quota assigned to a new API key on the free plan. Use -1 for unlimited.",
    min: -1,
    max: 10000000,
  },
  BILLING_CORE_SUPPORTER_API_REQUESTS_PER_DAY: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_API_REQUESTS_PER_DAY,
    group: "Billing",
    label: "Core supporter API requests per day",
    help: "Daily request quota assigned to a new API key on the core supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 10000000,
  },
  BILLING_PRO_SUPPORTER_API_REQUESTS_PER_DAY: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_API_REQUESTS_PER_DAY,
    group: "Billing",
    label: "Pro supporter API requests per day",
    help: "Daily request quota assigned to a new API key on the pro supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 10000000,
  },
  BILLING_ELITE_SUPPORTER_API_REQUESTS_PER_DAY: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_API_REQUESTS_PER_DAY,
    group: "Billing",
    label: "Elite supporter API requests per day",
    help: "Daily request quota assigned to a new API key on the elite supporter plan. Use -1 for unlimited.",
    min: -1,
    max: 10000000,
  },
  BILLING_FREE_TEAMS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_TEAMS,
    group: "Billing",
    label: "Free plan teams owned",
    help: "Teams a free-plan user may own at once. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_CORE_SUPPORTER_TEAMS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_TEAMS,
    group: "Billing",
    label: "Core supporter teams owned",
    help: "Teams a core supporter may own at once. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_PRO_SUPPORTER_TEAMS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_TEAMS,
    group: "Billing",
    label: "Pro supporter teams owned",
    help: "Teams a pro supporter may own at once. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_ELITE_SUPPORTER_TEAMS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_TEAMS,
    group: "Billing",
    label: "Elite supporter teams owned",
    help: "Teams an elite supporter may own at once. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_FREE_TEAM_MEMBERS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_TEAM_MEMBERS,
    group: "Billing",
    label: "Free plan team seats",
    help: "Members plus pending invites allowed on a team owned by a free-plan user. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 10000,
  },
  BILLING_CORE_SUPPORTER_TEAM_MEMBERS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_TEAM_MEMBERS,
    group: "Billing",
    label: "Core supporter team seats",
    help: "Members plus pending invites allowed on a team owned by a core supporter. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 10000,
  },
  BILLING_PRO_SUPPORTER_TEAM_MEMBERS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_TEAM_MEMBERS,
    group: "Billing",
    label: "Pro supporter team seats",
    help: "Members plus pending invites allowed on a team owned by a pro supporter. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 10000,
  },
  BILLING_ELITE_SUPPORTER_TEAM_MEMBERS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_TEAM_MEMBERS,
    group: "Billing",
    label: "Elite supporter team seats",
    help: "Members plus pending invites allowed on a team owned by an elite supporter. Use -1 for unlimited, 0 to disable teams on this plan.",
    min: -1,
    max: 10000,
  },
  BILLING_FREE_WEBHOOKS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_WEBHOOKS,
    group: "Billing",
    label: "Free plan webhooks",
    help: "Webhook endpoints a free-plan user may register. Use -1 for unlimited, 0 to disable webhooks on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_CORE_SUPPORTER_WEBHOOKS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_WEBHOOKS,
    group: "Billing",
    label: "Core supporter webhooks",
    help: "Webhook endpoints a core supporter may register. Use -1 for unlimited, 0 to disable webhooks on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_PRO_SUPPORTER_WEBHOOKS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_WEBHOOKS,
    group: "Billing",
    label: "Pro supporter webhooks",
    help: "Webhook endpoints a pro supporter may register. Use -1 for unlimited, 0 to disable webhooks on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_ELITE_SUPPORTER_WEBHOOKS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_WEBHOOKS,
    group: "Billing",
    label: "Elite supporter webhooks",
    help: "Webhook endpoints an elite supporter may register. Use -1 for unlimited, 0 to disable webhooks on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_FREE_SCHEDULED_SCANS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_SCHEDULED_SCANS,
    group: "Billing",
    label: "Free plan scheduled scans",
    help: "Recurring scan schedules a free-plan user may keep active. Use -1 for unlimited, 0 to disable scheduled scans on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_CORE_SUPPORTER_SCHEDULED_SCANS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_SCHEDULED_SCANS,
    group: "Billing",
    label: "Core supporter scheduled scans",
    help: "Recurring scan schedules a core supporter may keep active. Use -1 for unlimited, 0 to disable scheduled scans on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_PRO_SUPPORTER_SCHEDULED_SCANS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_SCHEDULED_SCANS,
    group: "Billing",
    label: "Pro supporter scheduled scans",
    help: "Recurring scan schedules a pro supporter may keep active. Use -1 for unlimited, 0 to disable scheduled scans on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_ELITE_SUPPORTER_SCHEDULED_SCANS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_SCHEDULED_SCANS,
    group: "Billing",
    label: "Elite supporter scheduled scans",
    help: "Recurring scan schedules an elite supporter may keep active. Use -1 for unlimited, 0 to disable scheduled scans on this plan.",
    min: -1,
    max: 1000,
  },
  BILLING_FREE_BULK_SCAN_URLS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_BULK_SCAN_URLS,
    group: "Billing",
    label: "Free plan bulk scan URLs",
    help: "URLs allowed in one bulk scan submission on the free plan. Use -1 for unlimited, 0 to disable bulk scans on this plan.",
    min: -1,
    max: 100000,
  },
  BILLING_CORE_SUPPORTER_BULK_SCAN_URLS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_BULK_SCAN_URLS,
    group: "Billing",
    label: "Core supporter bulk scan URLs",
    help: "URLs allowed in one bulk scan submission for a core supporter. Use -1 for unlimited, 0 to disable bulk scans on this plan.",
    min: -1,
    max: 100000,
  },
  BILLING_PRO_SUPPORTER_BULK_SCAN_URLS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_BULK_SCAN_URLS,
    group: "Billing",
    label: "Pro supporter bulk scan URLs",
    help: "URLs allowed in one bulk scan submission for a pro supporter. Use -1 for unlimited, 0 to disable bulk scans on this plan.",
    min: -1,
    max: 100000,
  },
  BILLING_ELITE_SUPPORTER_BULK_SCAN_URLS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_BULK_SCAN_URLS,
    group: "Billing",
    label: "Elite supporter bulk scan URLs",
    help: "URLs allowed in one bulk scan submission for an elite supporter. Use -1 for unlimited, 0 to disable bulk scans on this plan.",
    min: -1,
    max: 100000,
  },

  // GitHub repo review AI token budget. Unlike every other per-plan limit
  // above, -1 (unlimited) is never a valid value here at any tier: 0 is
  // "not available on this plan", any positive integer is a real monthly
  // token cap. VulnRadar's own AI usage runs through subsidized/free-tier
  // provider capacity, not an unlimited budget, so this can't be waived
  // even for the top tier the way dailyScans or webhooks can.
  BILLING_FREE_GITHUB_REVIEW_TOKENS_PER_MONTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_FREE_GITHUB_REVIEW_TOKENS_PER_MONTH,
    group: "Billing",
    label: "Free plan GitHub review tokens/month",
    help: "AI tokens (prompt + completion) a free-plan user may spend on GitHub repo AI code review per calendar month, using VulnRadar's own AI. 0 disables the feature on this plan. Never -1 (unlimited) — bringing your own AI key bypasses this cap entirely instead.",
    min: 0,
    max: 100_000_000,
  },
  BILLING_CORE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_CORE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
    group: "Billing",
    label: "Core supporter GitHub review tokens/month",
    help: "AI tokens a core supporter may spend on GitHub repo AI code review per calendar month, using VulnRadar's own AI. Never -1 (unlimited) — bringing your own AI key bypasses this cap entirely instead.",
    min: 0,
    max: 100_000_000,
  },
  BILLING_PRO_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_PRO_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
    group: "Billing",
    label: "Pro supporter GitHub review tokens/month",
    help: "AI tokens a pro supporter may spend on GitHub repo AI code review per calendar month, using VulnRadar's own AI. Never -1 (unlimited) — bringing your own AI key bypasses this cap entirely instead.",
    min: 0,
    max: 100_000_000,
  },
  BILLING_ELITE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BILLING_ELITE_SUPPORTER_GITHUB_REVIEW_TOKENS_PER_MONTH,
    group: "Billing",
    label: "Elite supporter GitHub review tokens/month",
    help: "AI tokens an elite supporter may spend on GitHub repo AI code review per calendar month, using VulnRadar's own AI. A real finite cap — VulnRadar's AI usage runs through subsidized provider capacity, not an unlimited budget, so even the top tier is never -1 (unlimited) for this field. Bringing your own AI key bypasses this cap entirely instead.",
    min: 0,
    max: 100_000_000,
  },

  // RATE LIMITS
  //
  // Every attempt cap and window here has a minimum of 1. A zero would
  // disable the gate in front of login and let an attacker brute-force the
  // admin account, so the registry refuses to store one.

  RATE_LIMIT_LOGIN_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_LOGIN_ATTEMPTS,
    group: "Rate Limits",
    label: "Login attempts per window",
    help: "Failed logins allowed from one IP before it is locked out for the rest of the window.",
    min: 1,
    max: 100,
  },
  RATE_LIMIT_LOGIN_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_LOGIN_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Login window (minutes)",
    help: "Length of the login rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_SIGNUP_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_SIGNUP_ATTEMPTS,
    group: "Rate Limits",
    label: "Signup attempts per window",
    help: "Accounts one IP may create per window.",
    min: 1,
    max: 100,
  },
  RATE_LIMIT_SIGNUP_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_SIGNUP_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Signup window (minutes)",
    help: "Length of the signup rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_FORGOT_PASSWORD_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_FORGOT_PASSWORD_ATTEMPTS,
    group: "Rate Limits",
    label: "Password reset requests per window",
    help: "Reset emails one IP may trigger per window. Also gates verification resends.",
    min: 1,
    max: 100,
  },
  RATE_LIMIT_FORGOT_PASSWORD_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_FORGOT_PASSWORD_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Password reset window (minutes)",
    help: "Length of the password reset rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_API_REQUESTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_API_REQUESTS,
    group: "Rate Limits",
    label: "API requests per window",
    help: "General API calls allowed per window per caller.",
    min: 1,
    max: 100000,
  },
  RATE_LIMIT_API_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_API_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "API window (minutes)",
    help: "Length of the general API rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_SCAN_REQUESTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_SCAN_REQUESTS,
    group: "Rate Limits",
    label: "Scan requests per window",
    help: "Single-URL scans allowed per window per user. Separate from the daily plan quota.",
    min: 1,
    max: 100000,
  },
  RATE_LIMIT_SCAN_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_SCAN_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Scan window (minutes)",
    help: "Length of the scan rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_BULK_SCAN_REQUESTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BULK_SCAN_REQUESTS,
    group: "Rate Limits",
    label: "Bulk scan requests per window",
    help: "Bulk submissions allowed per window per user. Each submission may carry many URLs.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_BULK_SCAN_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BULK_SCAN_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Bulk scan window (minutes)",
    help: "Length of the bulk scan rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  DEFAULT_API_KEY_DAILY_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DEFAULT_API_KEY_DAILY_LIMIT,
    group: "Rate Limits",
    label: "Default API key daily limit",
    help: "Requests per day granted to a newly issued API key. Existing keys keep the limit they were created with.",
    min: 1,
    max: 1000000,
  },
  RATE_LIMIT_BROWSER_SESSION_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BROWSER_SESSION_ATTEMPTS,
    group: "Rate Limits",
    label: "Browser sessions per window",
    help: "Live BrowserBase sessions one user may create per window. BrowserBase is metered, so this bounds real cost from a compromised session cookie.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_BROWSER_SESSION_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BROWSER_SESSION_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Browser session window (minutes)",
    help: "Length of the browser session rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_AI_CHAT_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_CHAT_ATTEMPTS,
    group: "Rate Limits",
    label: "AI chat messages per window",
    help: "Support chat messages one user may send per window. Bounds AI provider cost from a single account.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_AI_CHAT_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_CHAT_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "AI chat window (minutes)",
    help: "Length of the AI chat rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_AI_VERIFY_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_VERIFY_ATTEMPTS,
    group: "Rate Limits",
    label: "AI verify requests per window",
    help: "AI finding-verification requests one user may send per window, shared by /api/v3/scan/verify and /api/v3/scan/verify-batch. Each request fans out into one AI call per finding, so this bounds cost from a single account.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_AI_VERIFY_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_VERIFY_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "AI verify window (minutes)",
    help: "Length of the AI verify rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_AI_SUMMARY_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_SUMMARY_ATTEMPTS,
    group: "Rate Limits",
    label: "AI summary requests per window",
    help: "AI scan-summary generate/regenerate requests one user may send per window. A cached summary is returned without consuming this limit; only real generation calls count.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_AI_SUMMARY_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_AI_SUMMARY_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "AI summary window (minutes)",
    help: "Length of the AI summary rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_ADMIN_REAUTH_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_ADMIN_REAUTH_ATTEMPTS,
    group: "Rate Limits",
    label: "Admin re-auth attempts per window",
    help: "Password attempts allowed at the admin panel's re-auth gate before it locks out for the rest of the window.",
    min: 1,
    max: 100,
  },
  RATE_LIMIT_ADMIN_REAUTH_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_ADMIN_REAUTH_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Admin re-auth window (minutes)",
    help: "Length of the admin re-auth rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_BILLING_VERIFY_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BILLING_VERIFY_ATTEMPTS,
    group: "Rate Limits",
    label: "Billing verify attempts per window",
    help: "Attempts allowed at the 6-digit billing verification code before lockout. Keep this low: the code space is small enough to brute-force without a tight gate.",
    min: 1,
    max: 100,
  },
  RATE_LIMIT_BILLING_VERIFY_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_BILLING_VERIFY_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Billing verify window (minutes)",
    help: "Length of the billing verification rate-limit bucket. Should stay at or below the code's own validity window.",
    min: 1,
    max: 1440,
  },
  RATE_LIMIT_TEAM_INVITE_ATTEMPTS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_TEAM_INVITE_ATTEMPTS,
    group: "Rate Limits",
    label: "Team invites per window",
    help: "Invite emails one team owner may send per window. Bounds email spam from a compromised or malicious account.",
    min: 1,
    max: 10000,
  },
  RATE_LIMIT_TEAM_INVITE_WINDOW_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_RATE_LIMIT_TEAM_INVITE_WINDOW_MINUTES,
    group: "Rate Limits",
    label: "Team invite window (minutes)",
    help: "Length of the team invite rate-limit bucket.",
    min: 1,
    max: 1440,
  },
  // SCANNING

  MAX_URL_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_URL_LENGTH,
    group: "Scanning",
    label: "Maximum URL length",
    help: "Characters allowed in a submitted URL before it is rejected.",
    min: 16,
    max: 8192,
  },
  MAX_URLS_BULK: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_URLS_BULK,
    group: "Scanning",
    label: "Maximum URLs per bulk scan",
    help: "URLs accepted in one bulk submission.",
    min: 1,
    max: 1000,
  },
  SCHEDULE_WORKER_BATCH_CONCURRENCY: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCHEDULE_WORKER_BATCH_CONCURRENCY,
    group: "Scanning",
    label: "Scheduled scan worker concurrency",
    help: "How many due scheduled scans run at once per polling tick. Keeps a large backlog from launching hundreds of simultaneous scans.",
    min: 1,
    max: 25,
  },
  SCAN_TIMEOUT_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_TIMEOUT_SECONDS,
    group: "Scanning",
    label: "Scan timeout (seconds)",
    help: "Hard ceiling for a single-URL scan.",
    min: 10,
    max: 3600,
  },
  BULK_SCAN_TIMEOUT_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BULK_SCAN_TIMEOUT_SECONDS,
    group: "Scanning",
    label: "Bulk scan timeout (seconds)",
    help: "Hard ceiling for a whole bulk submission.",
    min: 30,
    max: 21600,
  },
  CRAWL_SCAN_TIMEOUT_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_CRAWL_SCAN_TIMEOUT_SECONDS,
    group: "Scanning",
    label: "Crawl scan timeout (seconds)",
    help: "Hard ceiling for a whole crawl submission (discovery plus every page).",
    min: 30,
    max: 21600,
  },
  SCAN_STATUS_POLL_INTERVAL_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_STATUS_POLL_INTERVAL_MS,
    group: "Scanning",
    label: "Scan status poll interval (ms)",
    help: "Suggested interval for a client polling GET /api/v3/scan/status/:id. Not enforced server-side.",
    min: 500,
    max: 60000,
  },
  DEFAULT_SEVERITY_THRESHOLD: {
    tier: "runtime",
    type: "enum",
    default: CONFIG_DEFAULT_SEVERITY_THRESHOLD,
    group: "Scanning",
    label: "Default severity threshold",
    help: "Lowest severity reported when a scan does not specify one.",
    options: ["critical", "high", "medium", "low", "info"],
  },
  SCAN_AUTH_ENABLED: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_SCAN_AUTH_ENABLED,
    group: "Scanning",
    label: "Authenticated scanning",
    help: "Lets a caller supply login material with a single scan request so the scanner can log in first. Fully ephemeral: nothing is ever stored. Turning this off hides the feature from the deployment.",
  },
  SCAN_AUTH_MAX_SECRET_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_MAX_SECRET_LENGTH,
    group: "Scanning",
    label: "Credential secret length",
    help: "Characters allowed in one secret value (password, header value, cookie value) in a scan request.",
    min: 32,
    max: 65536,
  },
  SCAN_AUTH_MAX_COOKIES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_MAX_COOKIES,
    group: "Scanning",
    label: "Cookies per authenticated scan",
    help: "How many cookies a caller may attach to one authenticated scan request.",
    min: 1,
    max: 200,
  },
  SCAN_AUTH_VERIFY_TIMEOUT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_VERIFY_TIMEOUT_MS,
    group: "Scanning",
    label: "Login verification timeout (ms)",
    help: "How long to wait for the verification fetch that proves the login worked.",
    min: 1000,
    max: 120000,
  },
  SCAN_AUTH_MAX_LOGIN_BODY_BYTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_MAX_LOGIN_BODY_BYTES,
    group: "Scanning",
    label: "Login page read limit (bytes)",
    help: "Bytes read from a login or verification page. Only needs to be large enough to reach the CSRF token.",
    min: 1024,
    max: 10485760,
  },
  SCAN_AUTH_MAX_COOKIE_AGE_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_MAX_COOKIE_AGE_SECONDS,
    group: "Scanning",
    label: "Maximum cookie lifetime (seconds)",
    help: "Longest lifetime the cookie jar honours, however long the target says its cookie lives.",
    min: 60,
    max: 86400,
  },
  SCAN_AUTH_BASELINE_DIFF_BYTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BASELINE_DIFF_BYTES,
    group: "Scanning",
    label: "Login evidence threshold (bytes)",
    help: "Byte difference between the anonymous and authenticated fetch before the login counts as verified.",
    min: 1,
    max: 1048576,
  },
  SCAN_AUTH_BROWSER_NAV_TIMEOUT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BROWSER_NAV_TIMEOUT_MS,
    group: "Scanning",
    label: "Browser login navigation timeout (ms)",
    help: "How long to wait for the login page's load event in the browser-driven form login path.",
    min: 1000,
    max: 120000,
  },
  SCAN_AUTH_BROWSER_SETTLE_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BROWSER_SETTLE_MS,
    group: "Scanning",
    label: "Browser login settle window (ms)",
    help: "How long the page must go without a new network request after load before it counts as fully rendered.",
    min: 100,
    max: 30000,
  },
  SCAN_AUTH_BROWSER_MAX_WAIT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BROWSER_MAX_WAIT_MS,
    group: "Scanning",
    label: "Browser login max wait (ms)",
    help: "Hard ceiling on the whole wait-for-load step, load event plus settle window included.",
    min: 1000,
    max: 180000,
  },
  SCAN_AUTH_BROWSER_SESSION_TIMEOUT_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BROWSER_SESSION_TIMEOUT_SECONDS,
    group: "Scanning",
    label: "Browser login session TTL (seconds)",
    help: "BrowserBase session lifetime requested for the login handshake. Short: the browser only needs to render the login page and read its cookies.",
    min: 30,
    max: 600,
  },
  SCAN_AUTH_BROWSER_MAX_HTML_CHARS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SCAN_AUTH_BROWSER_MAX_HTML_CHARS,
    group: "Scanning",
    label: "Browser login HTML capture limit (characters)",
    help: "Characters of rendered HTML read from the browser for form detection and post-submit verification.",
    min: 1024,
    max: 5000000,
  },

  // AUTHENTICATION

  SESSION_TIMEOUT_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SESSION_TIMEOUT_DAYS,
    group: "Authentication",
    label: "Session lifetime (days)",
    help: "How long a session stays valid server-side before the user must sign in again.",
    min: 1,
    max: 365,
  },
  SESSION_MAX_AGE_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SESSION_MAX_AGE_DAYS,
    group: "Authentication",
    label: "Session cookie max age (days)",
    help: "Browser-side lifetime of the session cookie. Keep it equal to or below the session lifetime.",
    min: 1,
    max: 365,
  },
  PASSWORD_MIN_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_PASSWORD_MIN_LENGTH,
    group: "Authentication",
    label: "Minimum password length",
    help: "Shortest password accepted at signup and password reset. Does not affect existing passwords.",
    min: 8,
    max: 128,
  },
  PASSWORD_RESET_HOURS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_PASSWORD_RESET_HOURS,
    group: "Authentication",
    label: "Password reset link lifetime (hours)",
    help: "How long a reset link stays usable. Shorter is safer.",
    min: 1,
    max: 168,
  },
  EMAIL_VERIFICATION_HOURS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_EMAIL_VERIFICATION_HOURS,
    group: "Authentication",
    label: "Email verification link lifetime (hours)",
    help: "How long a verification link stays usable.",
    min: 1,
    max: 720,
  },
  DEVICE_TRUST_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DEVICE_TRUST_DAYS,
    group: "Authentication",
    label: "Device trust duration (days)",
    help: "How long a device may skip the second factor after the user ticks Remember this device.",
    min: 1,
    max: 365,
  },
  DATA_EXPORT_COOLDOWN_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DATA_EXPORT_COOLDOWN_DAYS,
    group: "General",
    label: "Data export cooldown (days)",
    help: "How often a user may request a fresh GDPR data export. Re-downloading an already-generated export is not affected.",
    min: 1,
    max: 365,
  },
  DEVICE_TRUST_MAX_AGE_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DEVICE_TRUST_MAX_AGE_DAYS,
    group: "Authentication",
    label: "Device trust cookie max age (days)",
    help: "Browser-side lifetime of the trusted-device cookie. Keep it equal to the device trust duration.",
    min: 1,
    max: 365,
  },
  "2FA_PENDING_MAX_AGE_SECONDS": {
    tier: "runtime",
    type: "int",
    default: CONFIG_2FA_PENDING_MAX_AGE_SECONDS,
    group: "Authentication",
    label: "Two-factor challenge window (seconds)",
    help: "How long a half-finished login may sit at the second-factor prompt before it expires.",
    min: 60,
    max: 3600,
  },
  EMAIL_2FA_CODE_EXPIRY_MINUTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_EMAIL_2FA_CODE_EXPIRY_MINUTES,
    group: "Authentication",
    label: "Email 2FA code lifetime (minutes)",
    help: "How long an emailed 6-digit two-factor code stays valid, across the password login, OAuth login, and manual resend flows.",
    min: 1,
    max: 60,
  },
  SESSION_IP_BINDING_ENABLED: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_SESSION_IP_BINDING_ENABLED,
    group: "Authentication",
    label: "Bind sessions to their subnet",
    help: "Ends a session and asks for login again when a request arrives from a different subnet than the one it started on. Off by default: mobile networks and wifi-to-cellular handoffs rotate IPs mid-session for real users.",
  },
  SESSION_IP_BINDING_IPV4_PREFIX: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SESSION_IP_BINDING_IPV4_PREFIX,
    group: "Authentication",
    label: "Session IPv4 subnet size (prefix bits)",
    help: "How much of the IPv4 address must match to count as the same network. /24 (the default) tolerates a carrier rotating the last octet; raise it toward /32 for a stricter check.",
    min: 8,
    max: 32,
  },
  SESSION_IP_BINDING_IPV6_PREFIX: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SESSION_IP_BINDING_IPV6_PREFIX,
    group: "Authentication",
    label: "Session IPv6 subnet size (prefix bits)",
    help: "IPv6 equivalent of the IPv4 subnet size setting. /48 is the typical residential/ISP allocation boundary.",
    min: 16,
    max: 128,
  },
  API_KEY_IP_BINDING_ENABLED: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_API_KEY_IP_BINDING_ENABLED,
    group: "Authentication",
    label: "Bind API keys to their subnet",
    help: "Declines API requests from a subnet other than the one the key was first used from; the key itself is not revoked. Off by default: a key used from GitHub Actions or another shared-runner CI provider does not have a fixed IP.",
  },
  API_KEY_IP_BINDING_IPV4_PREFIX: {
    tier: "runtime",
    type: "int",
    default: CONFIG_API_KEY_IP_BINDING_IPV4_PREFIX,
    group: "Authentication",
    label: "API key IPv4 subnet size (prefix bits)",
    help: "How much of the IPv4 address must match. Defaults to /32 (exact match) since a deployment turning this on is expected to have a genuinely fixed server IP.",
    min: 8,
    max: 32,
  },
  API_KEY_IP_BINDING_IPV6_PREFIX: {
    tier: "runtime",
    type: "int",
    default: CONFIG_API_KEY_IP_BINDING_IPV6_PREFIX,
    group: "Authentication",
    label: "API key IPv6 subnet size (prefix bits)",
    help: "IPv6 equivalent of the IPv4 subnet size setting. Defaults to /128 (exact match).",
    min: 16,
    max: 128,
  },

  // AI

  AI_CHAT_MAX_TOKENS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_CHAT_MAX_TOKENS,
    group: "AI",
    label: "Chat token budget",
    help: "Maximum tokens the support chat may generate per reply.",
    min: 256,
    max: 128000,
  },
  AI_CHAT_HISTORY_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_CHAT_HISTORY_DAYS,
    group: "AI",
    label: "Chat history retention (days)",
    help: "How long chat conversations are kept before cleanup deletes them.",
    min: 1,
    max: 365,
  },
  AI_CHAT_MAX_INPUT_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_CHAT_MAX_INPUT_LENGTH,
    group: "AI",
    label: "Chat input cap (characters)",
    help: "Longest message a user may send to the support chat.",
    min: 50,
    max: 10000,
  },
  AI_VERIFY_MAX_TOKENS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_MAX_TOKENS,
    group: "AI",
    label: "Deep scan token budget",
    help: "Tokens allowed per finding. Reasoning models spend up to half of this thinking before they answer, so a finding that needs real cross-referencing can need 4000+ to still leave room for a complete answer.",
    min: 100,
    max: 32000,
  },
  AI_VERIFY_CHUNK_SIZE: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_CHUNK_SIZE,
    group: "AI",
    label: "Findings verified per AI call",
    help: "How many findings are sent to the AI in one request. Smaller chunks mean more calls but a lower risk of a long scan running out of tokens before every finding gets a verdict.",
    min: 1,
    max: 50,
  },
  AI_VERIFY_CALL_TIMEOUT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_CALL_TIMEOUT_MS,
    group: "AI",
    label: "Deep scan call timeout (ms)",
    help: "How long to wait for the AI provider on a single finding.",
    min: 1000,
    max: 300000,
  },
  AI_VERIFY_PROBE_TIMEOUT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_PROBE_TIMEOUT_MS,
    group: "AI",
    label: "Deep scan probe timeout (ms)",
    help: "How long to wait for the initial HTTP probe of the target site.",
    min: 1000,
    max: 120000,
  },
  AI_VERIFY_TOTAL_TIMEOUT_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_TOTAL_TIMEOUT_MS,
    group: "AI",
    label: "Deep scan total timeout (ms)",
    help: "Ceiling for the whole deep-scan batch. Calls that have not settled are reported as timed out.",
    min: 5000,
    max: 600000,
  },
  AI_VERIFY_BATCH_MAX_FINDINGS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_VERIFY_BATCH_MAX_FINDINGS,
    group: "AI",
    label: "Verify-batch findings cap",
    help: "Maximum findings[] length accepted by one POST /api/v3/scan/verify-batch request. Unlike /api/v3/scan/verify, this route takes an arbitrary caller-supplied array, so this cap bounds AI spend from a single request.",
    min: 1,
    max: 500,
  },
  AI_SUMMARY_MAX_TOKENS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_AI_SUMMARY_MAX_TOKENS,
    group: "AI",
    label: "Scan summary token budget",
    help: "Tokens allowed for the one-shot 3-5 sentence scan summary. Reasoning models spend up to half of this thinking before they answer, so too small a budget truncates the visible summary itself, not just the reasoning.",
    min: 500,
    max: 32000,
  },
  GITHUB_REVIEW_MAX_TOKENS_PER_RUN: {
    tier: "runtime",
    type: "int",
    default: CONFIG_GITHUB_REVIEW_MAX_TOKENS_PER_RUN,
    group: "AI",
    label: "GitHub review per-run token ceiling",
    help: "Hard cap on estimated tokens (prompt content) for one GitHub repo AI code review run, regardless of plan, remaining monthly quota, or whether the user brings their own AI key. A repo whose selected files estimate over this is rejected upfront rather than silently truncated.",
    min: 10_000,
    max: 2_000_000,
  },
  GITHUB_REVIEW_MAX_FILES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_GITHUB_REVIEW_MAX_FILES,
    group: "AI",
    label: "GitHub review max files per run",
    help: "Maximum number of files (after skipping binaries and vendor/build directories) fetched from a repo for one scan run, for both the pattern-based secrets pass and the AI review pass.",
    min: 1,
    max: 5000,
  },
  GITHUB_REVIEW_MAX_TOTAL_BYTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_GITHUB_REVIEW_MAX_TOTAL_BYTES,
    group: "AI",
    label: "GitHub review max total bytes per run",
    help: "Total byte budget across every file fetched from a repo for one scan run. Files are skipped once this is exhausted, largest-first pruning is not attempted.",
    min: 100_000,
    max: 200_000_000,
  },
  GITHUB_REVIEW_MAX_FILE_BYTES: {
    tier: "runtime",
    type: "int",
    default: CONFIG_GITHUB_REVIEW_MAX_FILE_BYTES,
    group: "AI",
    label: "GitHub review max single file bytes",
    help: "A single file larger than this is skipped entirely (treated the same as a binary file) rather than fetched and scanned.",
    min: 1_000,
    max: 50_000_000,
  },

  // DEMO

  DEMO_SCAN_LIMIT: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DEMO_SCAN_LIMIT,
    group: "Demo",
    label: "Demo scans per window",
    help: "Scans a signed-out visitor may run before being asked to sign up.",
    min: 1,
    max: 1000,
  },
  DEMO_WINDOW_HOURS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_DEMO_WINDOW_HOURS,
    group: "Demo",
    label: "Demo window (hours)",
    help: "Length of the demo scan bucket.",
    min: 1,
    max: 168,
  },

  // ADVANCED

  VERSION_COOKIE_MAX_AGE_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_VERSION_COOKIE_MAX_AGE_DAYS,
    group: "Advanced",
    label: "Version notice cookie max age (days)",
    help: "How long a dismissed release notice stays dismissed.",
    min: 1,
    max: 3650,
  },
  NOTIFICATION_POLL_INTERVAL_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_NOTIFICATION_POLL_INTERVAL_MS,
    group: "Advanced",
    label: "Notification bell poll interval (ms)",
    help: "How often the header bell polls for new site-wide and per-user notifications (e.g. team invites).",
    min: 10000,
    max: 1800000,
  },
  NOTIFICATION_DEFAULT_DISMISS_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_NOTIFICATION_DEFAULT_DISMISS_DAYS,
    group: "Advanced",
    label: "Default notification dismiss duration (days)",
    help: "How long a dismissed bell notification stays dismissed when it does not set its own duration.",
    min: 1,
    max: 3650,
  },
  SITE_NOTIFICATION_DEFAULT_DISMISS_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_SITE_NOTIFICATION_DEFAULT_DISMISS_DAYS,
    group: "Advanced",
    label: "Default banner/modal/toast dismiss duration (days)",
    help: "How long a dismissed banner, modal, or toast notification stays dismissed when it does not set its own duration.",
    min: 1,
    max: 3650,
  },
  BROWSERBASE_MAX_TTL_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BROWSERBASE_MAX_TTL_SECONDS,
    group: "Advanced",
    label: "Browser session hard cap (seconds)",
    help: "Ceiling on a live browser session. BrowserBase is metered, so raising this raises real cost.",
    min: 30,
    max: 3600,
  },
  BROWSERBASE_DEFAULT_TTL_SECONDS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BROWSERBASE_DEFAULT_TTL_SECONDS,
    group: "Advanced",
    label: "Browser session default TTL (seconds)",
    help: "Lifetime requested when a session is created. Keep it at or below the hard cap.",
    min: 30,
    max: 3600,
  },
  BROWSERBASE_LOGS_POLL_INTERVAL_MS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_BROWSERBASE_LOGS_POLL_INTERVAL_MS,
    group: "Advanced",
    label: "Browser session log poll interval (ms)",
    help: "How often the live browser session viewer page polls for new network/console log lines.",
    min: 1000,
    max: 60000,
  },
  MAX_EMAIL_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_EMAIL_LENGTH,
    group: "Advanced",
    label: "Maximum email length",
    help: "Characters accepted in an email address. The database column is 255.",
    min: 64,
    max: 255,
  },
  MAX_NAME_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_NAME_LENGTH,
    group: "Advanced",
    label: "Maximum name length",
    help: "Characters accepted in a display name. The database column is 255.",
    min: 8,
    max: 255,
  },
  MAX_DESCRIPTION_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_DESCRIPTION_LENGTH,
    group: "Advanced",
    label: "Maximum description length",
    help: "Characters accepted in free-text description fields.",
    min: 32,
    max: 10000,
  },
  MAX_TEAM_NAME_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_TEAM_NAME_LENGTH,
    group: "Advanced",
    label: "Maximum team name length",
    help: "Characters accepted in a team name. The database column is 255.",
    min: 8,
    max: 255,
  },
  MAX_TAGS_PER_SCAN: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_TAGS_PER_SCAN,
    group: "Advanced",
    label: "Maximum tags per scan",
    help: "Tags a user may attach to one scan.",
    min: 1,
    max: 100,
  },
  MAX_TAG_LENGTH: {
    tier: "runtime",
    type: "int",
    default: CONFIG_MAX_TAG_LENGTH,
    group: "Advanced",
    label: "Maximum tag length",
    help: "Characters accepted in one scan tag. Longer input is truncated, not rejected.",
    min: 1,
    max: 255,
  },
  TEAM_INVITE_EXPIRY_DAYS: {
    tier: "runtime",
    type: "int",
    default: CONFIG_TEAM_INVITE_EXPIRY_DAYS,
    group: "Advanced",
    label: "Team invite expiry (days)",
    help: "How long a team invite link stays usable before it must be resent.",
    min: 1,
    max: 90,
  },
  PAGINATION_DEFAULT_PAGE_SIZE: {
    tier: "runtime",
    type: "int",
    default: CONFIG_PAGINATION_DEFAULT_PAGE_SIZE,
    group: "Advanced",
    label: "Default page size",
    help: "Rows returned when a request does not ask for a page size.",
    min: 1,
    max: 200,
  },
  PAGINATION_MAX_PAGE_SIZE: {
    tier: "runtime",
    type: "int",
    default: CONFIG_PAGINATION_MAX_PAGE_SIZE,
    group: "Advanced",
    label: "Maximum page size",
    help: "Largest page a caller may request. Raising this raises the cost of one query.",
    min: 1,
    max: 1000,
  },
  BETA_ENABLED: {
    tier: "runtime",
    type: "bool",
    default: CONFIG_BETA_ENABLED,
    group: "Advanced",
    label: "Beta banner",
    help: "Shows the beta notice at the top of every page.",
  },
  BETA_BANNER_MESSAGE: {
    tier: "runtime",
    type: "string",
    default: CONFIG_BETA_BANNER_MESSAGE,
    group: "Advanced",
    label: "Beta banner message",
    help: "Text of the beta notice. Only shown while the beta banner is on.",
    min: 1,
    max: 500,
  },
} as const satisfies Record<string, SettingDefinition>;

/**
 * Constants that are deliberately not configurable. Listed with the reason so
 * a reader can tell they were considered rather than missed. Keys are the
 * CONFIG_ constant name without the prefix, matching SETTINGS_REGISTRY.
 */
export const NEVER_CONFIGURABLE = {
  APP_VERSION:
    "Describes the running code. Editing it makes the app lie about itself.",
  ENGINE_VERSION:
    "Describes the running detection engine and is stamped onto every stored scan result.",
  MIN_SCHEMA_VERSION:
    "The schema this build requires. Lowering it lets the app start against a database it cannot use.",
  SESSION_COOKIE_NAME:
    "Renaming the cookie signs out every user instantly and orphans their session rows.",
  DEVICE_TRUST_COOKIE_NAME:
    "Renaming the cookie makes every trusted device prompt for a second factor again.",
  "2FA_PENDING_COOKIE_NAME":
    "Renaming the cookie breaks every login that is mid-way through the second factor.",
  VERSION_COOKIE_NAME:
    "Renaming the cookie re-shows the release notice to everyone who already dismissed it.",
  API_KEY_PREFIX:
    "Issued keys carry the old prefix. Changing it invalidates every existing key lookup.",
  API_CURRENT_VERSION:
    "Routes exist on disk. A value pointing at a version with no route directory returns 404.",
  API_SUPPORTED_VERSIONS:
    "Same as the current version: the list has to match the route directories that exist.",
  TOTP_VALIDITY_SECONDS:
    "RFC 6238 interoperability. Authenticator apps assume 30 seconds and cannot be told otherwise.",
  CLEANUP_INTERVAL_MS:
    "Read once when the cleanup timer is registered, so a runtime change would not take effect.",
  DB_CLEANUP_INTERVAL_MS:
    "Read once when the periodic database cleanup timer is registered, so a runtime change would not take effect.",
  SCHEDULE_WORKER_POLL_INTERVAL_MS:
    "Read once when the scheduled-scans worker timer is registered, so a runtime change would not take effect.",
  PAGINATION_DEFAULT_PAGE:
    "The first page is always page 1. The constant exists to avoid a magic number, not to be tuned.",
  DB_POOL_MAX:
    "Read once at module load to construct the pg Pool. A later change has no effect without a process restart. Already has its own env override (DATABASE_POOL_MAX) in lib/database/db.ts.",
  DB_POOL_MIN:
    "Same as DB_POOL_MAX: baked into the Pool at construction. Already overridable via DATABASE_POOL_MIN.",
  DB_IDLE_TIMEOUT_MS:
    "Same as DB_POOL_MAX: baked into the Pool at construction. Already overridable via DATABASE_IDLE_TIMEOUT_MS.",
  DB_CONNECTION_TIMEOUT_MS:
    "Same as DB_POOL_MAX: baked into the Pool at construction. Already overridable via DATABASE_CONNECTION_TIMEOUT_MS.",
  DB_STATEMENT_TIMEOUT_MS:
    "Same as DB_POOL_MAX: baked into the Pool at construction. Already overridable via DATABASE_STATEMENT_TIMEOUT_MS.",
  DB_QUERY_TIMEOUT_MS:
    "Same as DB_POOL_MAX: baked into the Pool at construction. Already overridable via DATABASE_QUERY_TIMEOUT_MS.",
  DB_HEALTHCHECK_TIMEOUT_MS:
    "Read once by the readiness endpoint's probe helper at call time from the constant, not from a re-readable source; deliberately short and not something an admin needs to tune live.",
} as const satisfies Record<string, string>;

export type SettingKey = keyof typeof SETTINGS_REGISTRY;

type ValueForType<T extends SettingType> = T extends "int" | "float"
  ? number
  : T extends "bool"
    ? boolean
    : string;

/** The runtime type a resolved setting has, derived from its registry `type`. */
export type SettingValue<K extends SettingKey> = ValueForType<
  (typeof SETTINGS_REGISTRY)[K]["type"]
>;

export function isSettingKey(key: string): key is SettingKey {
  return Object.prototype.hasOwnProperty.call(SETTINGS_REGISTRY, key);
}

export function getSettingDefinition(key: SettingKey): SettingDefinition {
  return SETTINGS_REGISTRY[key];
}

const schemaCache = new Map<SettingKey, z.ZodType>();

function schemaFor(key: SettingKey): z.ZodType {
  const cached = schemaCache.get(key);
  if (cached) return cached;

  const def: SettingDefinition = SETTINGS_REGISTRY[key];
  let schema: z.ZodType;

  switch (def.type) {
    case "int": {
      let numeric = z.coerce.number().int();
      if (def.min !== undefined) numeric = numeric.min(def.min);
      if (def.max !== undefined) numeric = numeric.max(def.max);
      schema = numeric;
      break;
    }
    case "float": {
      let numeric = z.coerce.number();
      if (def.min !== undefined) numeric = numeric.min(def.min);
      if (def.max !== undefined) numeric = numeric.max(def.max);
      schema = numeric;
      break;
    }
    case "bool":
      // Not z.coerce.boolean(): it turns the string "false" into true, which
      // is exactly the mistake this validation exists to catch.
      schema = z.union([
        z.boolean(),
        z.enum(["true", "false"]).transform((v) => v === "true"),
      ]);
      break;
    case "email":
      schema = z.email();
      break;
    case "url":
      schema = z.url();
      break;
    case "enum":
      schema = z.enum([...(def.options ?? [])] as [string, ...string[]]);
      break;
    case "string": {
      let text = z.string();
      if (def.min !== undefined) text = text.min(def.min);
      if (def.max !== undefined) text = text.max(def.max);
      schema = text;
      break;
    }
  }

  schemaCache.set(key, schema);
  return schema;
}

/**
 * Validate an admin-supplied value against its registry constraints.
 *
 * On success the returned `value` is the canonical string to store, so the
 * database never holds a padded or oddly typed representation.
 */
export function validateSettingValue(
  key: SettingKey,
  value: unknown,
): { ok: true; value: string } | { ok: false; error: string } {
  const raw = typeof value === "string" ? value.trim() : value;
  const parsed = schemaFor(key).safeParse(raw);
  if (!parsed.success) {
    const def = SETTINGS_REGISTRY[key];
    const detail = parsed.error.issues[0]?.message ?? "Invalid value";
    return { ok: false, error: `${def.label} (${key}): ${detail}` };
  }
  return { ok: true, value: String(parsed.data) };
}

/**
 * Coerce a stored TEXT value (or an environment override) into the type the
 * registry declares. Returns undefined when the stored row is malformed, so
 * the caller can fall back to the shipped default instead of throwing.
 */
export function coerceSettingValue<K extends SettingKey>(
  key: K,
  raw: unknown,
): SettingValue<K> | undefined {
  const input = typeof raw === "string" ? raw.trim() : raw;
  const parsed = schemaFor(key).safeParse(input);
  return parsed.success ? (parsed.data as SettingValue<K>) : undefined;
}
