import { readFileSync, writeFileSync } from "fs"

// ── 55 NEW CHECKS ──────────────────────────────────────────────────────
const newChecks = [
  { id:"csp-wildcard-src",type:"combined",title:"CSP with Wildcard Source",category:"headers",severity:"HIGH",description:"Content-Security-Policy uses a wildcard (*) source directive, effectively disabling CSP protection.",evidence:"CSP header contains wildcard (*) source.",riskImpact:"A wildcard CSP source allows loading resources from any origin, defeating the purpose of CSP.",explanation:"CSP wildcard sources allow any origin to serve content, making XSS and data injection trivially exploitable.",fixSteps:["Replace wildcard sources with specific trusted origins.","Use 'self' for same-origin resources.","Audit all third-party sources and whitelist them explicitly."],codeExamples:[{label:"Nginx",language:"nginx",code:`add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://trusted.cdn.com;" always;`}]},
  { id:"expect-ct-missing",type:"header-missing",targetHeader:"expect-ct",title:"Missing Expect-CT Header",category:"headers",severity:"LOW",description:"The Expect-CT header is not set. It helps detect misissued certificates.",evidence:"Header 'Expect-CT' is not present.",riskImpact:"Without Expect-CT, misissued TLS certificates may go undetected.",explanation:"Expect-CT allows sites to opt in to reporting and enforcement of Certificate Transparency, catching rogue CAs.",fixSteps:["Add Expect-CT with enforce and max-age.","Configure a report-uri for violations."],codeExamples:[{label:"Nginx",language:"nginx",code:`add_header Expect-CT "max-age=86400, enforce" always;`}]},
  { id:"x-dns-prefetch-control",type:"header-missing",targetHeader:"x-dns-prefetch-control",title:"Missing X-DNS-Prefetch-Control Header",category:"headers",severity:"LOW",description:"X-DNS-Prefetch-Control is not set. DNS prefetching can leak which sites users visit.",evidence:"Header 'X-DNS-Prefetch-Control' is not present.",riskImpact:"Browsers may prefetch DNS for links on the page, leaking browsing intent to DNS resolvers.",explanation:"DNS prefetching improves performance but can be a privacy concern. Setting it to 'off' prevents unintended DNS lookups.",fixSteps:["Add X-DNS-Prefetch-Control: off to disable DNS prefetching."],codeExamples:[{label:"Nginx",language:"nginx",code:`add_header X-DNS-Prefetch-Control "off" always;`}]},
  { id:"x-download-options",type:"header-missing",targetHeader:"x-download-options",title:"Missing X-Download-Options Header",category:"headers",severity:"LOW",description:"The X-Download-Options header is not set. In IE, downloads can open directly in the browser context.",evidence:"Header 'X-Download-Options' is not present.",riskImpact:"IE users may execute downloaded files in the site's security context.",explanation:"Setting X-Download-Options to noopen prevents IE from executing downloads in the site's context.",fixSteps:["Add X-Download-Options: noopen header."],codeExamples:[{label:"Nginx",language:"nginx",code:`add_header X-Download-Options "noopen" always;`}]},
  { id:"cache-no-store-sensitive",type:"combined",title:"Sensitive Page Missing Cache-Control: no-store",category:"headers",severity:"MEDIUM",description:"Pages with login forms or sensitive inputs lack Cache-Control: no-store.",evidence:"Sensitive page content cached without no-store directive.",riskImpact:"Sensitive form data may be cached by browsers or proxies, exposing it to unauthorized access.",explanation:"Pages containing login forms, payment fields, or personal data should never be cached to prevent data leakage.",fixSteps:["Add Cache-Control: no-store, no-cache for pages with sensitive forms.","Ensure Pragma: no-cache is also set for HTTP/1.0 compatibility."],codeExamples:[]},
  { id:"etag-inode-leak",type:"combined",title:"ETag Header Leaking Server Information",category:"headers",severity:"LOW",description:"The ETag header may contain inode information that reveals server details.",evidence:"ETag header contains inode-style format.",riskImpact:"Inode-based ETags leak internal file system details about the server.",explanation:"Apache and some servers generate ETags using inode-mtime-size format, revealing server internals.",fixSteps:["Configure ETag to use only file size and modification time.","In Apache: FileETag MTime Size","In Nginx: etag on (already safe by default)."],codeExamples:[]},
  { id:"x-permitted-cross-domain",type:"header-missing",targetHeader:"x-permitted-cross-domain-policies",title:"Missing X-Permitted-Cross-Domain-Policies",category:"headers",severity:"LOW",description:"The X-Permitted-Cross-Domain-Policies header is not set.",evidence:"Header 'X-Permitted-Cross-Domain-Policies' is not present.",riskImpact:"Flash and PDF plugins may load data across domains without restriction.",explanation:"This header controls whether Flash and Acrobat can load data from your domain. Setting it to 'none' prevents cross-domain policy file abuse.",fixSteps:["Add X-Permitted-Cross-Domain-Policies: none"],codeExamples:[]},
  { id:"cookie-samesite-none",type:"combined",title:"Cookie with SameSite=None Without Secure",category:"cookies",severity:"HIGH",description:"A cookie is set with SameSite=None but without the Secure flag.",evidence:"Cookie has SameSite=None without Secure attribute.",riskImpact:"SameSite=None cookies without Secure are rejected by modern browsers and may expose session data.",explanation:"When SameSite is None, the Secure flag is required. Without it, the cookie is blocked or sent over insecure connections.",fixSteps:["Always pair SameSite=None with the Secure flag.","Consider using SameSite=Lax if cross-site access is not needed."],codeExamples:[]},
  { id:"cookie-prefix-missing",type:"combined",title:"Session Cookie Missing __Host- or __Secure- Prefix",category:"cookies",severity:"LOW",description:"Session cookies are not using secure cookie prefixes.",evidence:"Session cookie lacks __Host- or __Secure- prefix.",riskImpact:"Without cookie prefixes, cookies may be set by subdomains or over insecure connections.",explanation:"Cookie prefixes (__Host-, __Secure-) enforce that cookies must have specific attributes, preventing cookie injection attacks.",fixSteps:["Use __Host- prefix for cookies bound to a single origin.","Use __Secure- prefix for cookies that must be sent over HTTPS."],codeExamples:[]},
  { id:"cookie-max-age-excessive",type:"combined",title:"Cookie with Excessively Long Max-Age",category:"cookies",severity:"LOW",description:"A cookie has a max-age exceeding one year.",evidence:"Cookie max-age exceeds 365 days.",riskImpact:"Long-lived cookies increase the window for session theft and tracking.",explanation:"Session and authentication cookies should have reasonable expiration times to limit exposure.",fixSteps:["Set session cookies to expire within hours or days.","Use sliding expiration for persistent sessions."],codeExamples:[]},
  { id:"js-eval-usage",type:"body-pattern",title:"JavaScript eval() Usage Detected",category:"content",severity:"HIGH",description:"The page uses eval() which can execute arbitrary code.",evidence:"Detected eval() calls in JavaScript.",riskImpact:"eval() executes arbitrary strings as code, making XSS exploitation trivial.",explanation:"eval() is one of the most dangerous JavaScript functions. Any user input reaching eval() leads to code execution.",fixSteps:["Replace eval() with JSON.parse() for data parsing.","Use Function constructor only as a last resort.","Refactor code to avoid dynamic code execution."],codeExamples:[]},
  { id:"document-write-usage",type:"body-pattern",title:"document.write() Usage Detected",category:"content",severity:"MEDIUM",description:"The page uses document.write() which can inject arbitrary HTML.",evidence:"Detected document.write() or document.writeln() calls.",riskImpact:"document.write() can be exploited for DOM-based XSS and breaks page rendering in some cases.",explanation:"document.write() injects raw HTML into the document. If user input flows into it, attackers can inject scripts.",fixSteps:["Replace document.write() with DOM manipulation methods.","Use textContent or createElement for safe DOM updates."],codeExamples:[]},
  { id:"innerhtml-assignment",type:"body-pattern",title:"innerHTML Assignment Detected",category:"content",severity:"MEDIUM",description:"Direct innerHTML assignment found which can lead to XSS.",evidence:"Detected .innerHTML = assignments in JavaScript.",riskImpact:"innerHTML parses HTML strings, allowing script injection if the input is user-controlled.",explanation:"innerHTML is a common XSS vector. Assigning user input to innerHTML executes embedded scripts.",fixSteps:["Use textContent for text-only content.","Use DOMPurify to sanitize HTML before innerHTML assignment.","Prefer createElement/appendChild patterns."],codeExamples:[]},
  { id:"unsafe-target-blank-norel",type:"body-pattern",title:"Links with target=_blank Missing rel=noopener noreferrer",category:"content",severity:"LOW",description:"External links open in new tabs without proper rel attributes.",evidence:"Found links with target='_blank' without rel='noopener noreferrer'.",riskImpact:"New tabs can access the opener's window.opener object and the referrer leaks the current URL.",explanation:"Adding both noopener and noreferrer prevents tab-napping and referrer leakage.",fixSteps:["Add rel='noopener noreferrer' to all target='_blank' links."],codeExamples:[]},
  { id:"unvalidated-file-upload",type:"body-pattern",title:"File Upload Without Validation Indicators",category:"content",severity:"MEDIUM",description:"File upload inputs detected without apparent MIME type restrictions.",evidence:"Found file inputs without accept attribute restrictions.",riskImpact:"Unrestricted file uploads can lead to malicious file execution on the server.",explanation:"File upload fields should restrict accepted types to prevent uploading of scripts and executables.",fixSteps:["Add accept attribute to limit file types.","Validate MIME type and extension server-side.","Store uploads outside the web root."],codeExamples:[]},
  { id:"clickjacking-js-only",type:"body-pattern",title:"Clickjacking Protection via JavaScript Only",category:"content",severity:"MEDIUM",description:"Clickjacking protection relies solely on JavaScript frame-busting.",evidence:"Detected JavaScript frame-busting code without HTTP header protection.",riskImpact:"JavaScript frame-busting can be bypassed by attackers using sandbox attributes.",explanation:"Frame-busting scripts are unreliable. HTTP headers (X-Frame-Options, CSP frame-ancestors) are the correct solution.",fixSteps:["Use X-Frame-Options header instead of JavaScript.","Add CSP frame-ancestors directive."],codeExamples:[]},
  { id:"json-hijacking",type:"combined",title:"JSON Response Without Proper Content-Type",category:"headers",severity:"MEDIUM",description:"JSON API responses served without application/json content type.",evidence:"Response contains JSON but Content-Type is not application/json.",riskImpact:"JSON responses with wrong content type may be vulnerable to JSON hijacking in older browsers.",explanation:"Serving JSON with text/html content type can lead to script injection if the JSON contains HTML-like structures.",fixSteps:["Set Content-Type: application/json for all JSON API responses.","Add X-Content-Type-Options: nosniff."],codeExamples:[]},
  { id:"exposed-phpinfo",type:"body-pattern",title:"PHP Info Page Exposed",category:"information-disclosure",severity:"CRITICAL",description:"A phpinfo() output page is exposed, revealing extensive server configuration.",evidence:"Detected phpinfo() output in the page.",riskImpact:"phpinfo() reveals PHP version, modules, environment variables, and server paths to attackers.",explanation:"phpinfo() is a debugging tool that should never be accessible in production.",fixSteps:["Remove or restrict access to phpinfo() pages.","Block access via web server configuration."],codeExamples:[]},
  { id:"exposed-env-file",type:"body-pattern",title:"Environment File Contents Exposed",category:"information-disclosure",severity:"CRITICAL",description:"Contents resembling a .env file detected in the response.",evidence:"Detected .env file patterns (KEY=VALUE with sensitive variable names).",riskImpact:"Exposed .env files reveal database credentials, API keys, and secrets.",explanation:"The .env file typically contains all application secrets. It should never be served by the web server.",fixSteps:["Block access to .env files in web server config.","Move .env outside the web root.","Add .env to .gitignore."],codeExamples:[]},
  { id:"exposed-git-directory",type:"body-pattern",title:"Git Repository Directory Exposed",category:"information-disclosure",severity:"CRITICAL",description:"Indicators of an exposed .git directory detected.",evidence:"Found references to .git/config, .git/HEAD, or similar paths.",riskImpact:"An exposed .git directory allows attackers to download entire source code and commit history.",explanation:"The .git directory contains the complete repository. Attackers can reconstruct all source code and find secrets in history.",fixSteps:["Block access to .git/ directory in web server config.","In Nginx: location ~ /\\.git { deny all; }","In Apache: RedirectMatch 404 /\\.git"],codeExamples:[]},
  { id:"exposed-wp-config",type:"body-pattern",title:"WordPress Configuration File Exposed",category:"information-disclosure",severity:"CRITICAL",description:"WordPress wp-config.php contents or backup detected.",evidence:"Detected wp-config patterns in the response.",riskImpact:"wp-config.php contains database credentials and authentication keys.",explanation:"This file is the most sensitive in a WordPress installation. Backup copies (.bak, .old, ~) are common exposure vectors.",fixSteps:["Block direct access to wp-config.php.","Remove backup copies from web root."],codeExamples:[]},
  { id:"exposed-database-dump",type:"body-pattern",title:"Database Dump Exposed",category:"information-disclosure",severity:"CRITICAL",description:"SQL database dump or backup content detected in the response.",evidence:"Found SQL dump patterns (CREATE TABLE, INSERT INTO, mysqldump).",riskImpact:"Database dumps contain all application data including user credentials and personal information.",explanation:"Database backups accidentally left in web-accessible directories expose the entire database.",fixSteps:["Remove database dumps from web root.","Store backups in secure, non-web-accessible locations.","Use access controls on backup directories."],codeExamples:[]},
  { id:"exposed-backup-files",type:"body-pattern",title:"Backup File References Detected",category:"information-disclosure",severity:"HIGH",description:"References to backup files (.bak, .old, .backup, .swp) found.",evidence:"Detected backup file references in page source.",riskImpact:"Backup files often contain source code with embedded credentials and database passwords.",explanation:"Editors and backup tools create copies with predictable extensions that web servers may serve directly.",fixSteps:["Remove backup files from web root.","Configure web server to block .bak, .old, .swp, ~ files."],codeExamples:[]},
  { id:"exposed-log-files",type:"body-pattern",title:"Log File References Detected",category:"information-disclosure",severity:"HIGH",description:"References to log files or log output detected.",evidence:"Found log file paths or debug log output.",riskImpact:"Log files may contain IP addresses, user actions, errors with stack traces, and internal paths.",explanation:"Application logs should never be served publicly as they contain operational details useful to attackers.",fixSteps:["Block access to log directories.","Store logs outside the web root."],codeExamples:[]},
  { id:"version-disclosure-html",type:"body-pattern",title:"Software Version Disclosed in HTML",category:"information-disclosure",severity:"LOW",description:"Software version numbers found in HTML meta tags or comments.",evidence:"Detected version disclosure in HTML source.",riskImpact:"Version numbers help attackers find known vulnerabilities for specific software versions.",explanation:"Generator meta tags, HTML comments, and footer text commonly leak CMS and framework versions.",fixSteps:["Remove generator meta tags.","Strip version numbers from HTML output."],codeExamples:[]},
  { id:"insecure-crossorigin-attr",type:"body-pattern",title:"Insecure crossorigin Attribute Usage",category:"content",severity:"LOW",description:"Resources loaded with crossorigin attribute but without integrity checks.",evidence:"Found crossorigin attribute without integrity (SRI) attribute.",riskImpact:"Cross-origin resources without integrity checks can be tampered with if the CDN is compromised.",explanation:"The crossorigin attribute enables CORS for the resource but without SRI, there's no verification of content integrity.",fixSteps:["Add integrity attribute alongside crossorigin.","Generate SRI hashes using srihash.org."],codeExamples:[]},
  { id:"event-handler-attrs",type:"body-pattern",title:"Inline Event Handler Attributes",category:"content",severity:"MEDIUM",description:"HTML elements with inline event handler attributes detected.",evidence:"Found onclick, onerror, onload, or other inline event handlers.",riskImpact:"Inline event handlers increase the XSS attack surface and prevent strict CSP enforcement.",explanation:"Inline event handlers (onclick, onerror, onload) execute JavaScript directly, bypassing CSP nonce/hash protections.",fixSteps:["Move event handlers to external JavaScript files.","Use addEventListener() instead.","Enable strict CSP without unsafe-inline."],codeExamples:[]},
  { id:"svg-xss-risk",type:"body-pattern",title:"SVG with Scripting Capabilities",category:"content",severity:"MEDIUM",description:"Inline SVG elements with script or event handler content detected.",evidence:"Found SVG elements with embedded scripts or event handlers.",riskImpact:"SVG files can contain JavaScript that executes in the page context.",explanation:"Inline SVGs with script tags or event handlers execute JavaScript just like regular HTML, posing XSS risk.",fixSteps:["Sanitize SVG content to remove scripts.","Use img tags instead of inline SVGs for untrusted content.","Add CSP to restrict SVG script execution."],codeExamples:[]},
  { id:"websocket-unencrypted",type:"body-pattern",title:"Unencrypted WebSocket Connection (ws://)",category:"content",severity:"HIGH",description:"WebSocket connections using ws:// instead of wss:// detected.",evidence:"Found unencrypted ws:// WebSocket URLs.",riskImpact:"Unencrypted WebSocket traffic can be intercepted and modified by network attackers.",explanation:"WebSocket connections should always use wss:// (TLS) to prevent eavesdropping and tampering.",fixSteps:["Replace all ws:// URLs with wss://.","Ensure the WebSocket server supports TLS."],codeExamples:[]},
  { id:"exposed-aws-metadata",type:"body-pattern",title:"AWS Metadata URL Detected",category:"information-disclosure",severity:"CRITICAL",description:"References to AWS metadata endpoint (169.254.169.254) found.",evidence:"Detected AWS metadata URL patterns.",riskImpact:"The AWS metadata endpoint exposes IAM credentials, instance details, and user data.",explanation:"If an SSRF vulnerability exists, attackers can reach the metadata endpoint to steal IAM role credentials.",fixSteps:["Block access to 169.254.169.254 from application code.","Use IMDSv2 (token-required) to mitigate SSRF-based metadata theft."],codeExamples:[]},
  { id:"cors-null-origin",type:"combined",title:"CORS Allows null Origin",category:"headers",severity:"HIGH",description:"Access-Control-Allow-Origin is set to 'null', which can be exploited.",evidence:"CORS header allows null origin.",riskImpact:"Sandboxed iframes send Origin: null, so allowing null enables cross-site data theft.",explanation:"The null origin is sent by sandboxed iframes and local file:// pages. Allowing it grants access to attackers.",fixSteps:["Never allow 'null' as a CORS origin.","Whitelist specific trusted origins instead."],codeExamples:[]},
  { id:"cache-poisoning-headers",type:"combined",title:"Cache Poisoning Risk via Unkeyed Headers",category:"headers",severity:"MEDIUM",description:"Response varies on headers not included in Vary, risking cache poisoning.",evidence:"Response behavior varies on unkeyed headers.",riskImpact:"Attackers can poison shared caches by injecting different responses for the same URL.",explanation:"If a cache does not key on headers that change the response, an attacker can poison the cache with malicious content.",fixSteps:["Include all varying headers in the Vary response header.","Use Vary: Accept-Encoding, Accept-Language as needed."],codeExamples:[]},
  { id:"access-control-max-age-excessive",type:"combined",title:"CORS Preflight Cache Too Long",category:"headers",severity:"LOW",description:"Access-Control-Max-Age is set to an excessively long duration.",evidence:"CORS preflight cache exceeds 24 hours.",riskImpact:"Excessively long preflight cache means CORS policy changes take too long to propagate.",explanation:"The Access-Control-Max-Age header controls how long browsers cache preflight responses.",fixSteps:["Set Access-Control-Max-Age to 3600 (1 hour) or less."],codeExamples:[]},
  { id:"missing-noindex-staging",type:"body-pattern",title:"Staging/Dev Site Without noindex",category:"configuration",severity:"MEDIUM",description:"Staging or development site detected without search engine exclusion.",evidence:"Detected staging indicators (subdomain, meta tags) without noindex.",riskImpact:"Search engines may index development/staging sites, exposing pre-release features and test data.",explanation:"Staging sites should use meta robots noindex or X-Robots-Tag to prevent search engine indexing.",fixSteps:["Add <meta name='robots' content='noindex, nofollow'>.","Set X-Robots-Tag: noindex header.","Use robots.txt Disallow for staging."],codeExamples:[]},
  { id:"exposed-admin-panel",type:"body-pattern",title:"Admin Panel Publicly Accessible",category:"configuration",severity:"HIGH",description:"References to admin panels or login portals detected.",evidence:"Found admin URL patterns in page source.",riskImpact:"Publicly accessible admin panels are prime targets for brute-force and credential stuffing attacks.",explanation:"Admin interfaces should be hidden behind VPNs, IP whitelists, or additional authentication layers.",fixSteps:["Restrict admin panel access by IP.","Move admin to a non-standard path.","Add additional authentication (2FA, VPN)."],codeExamples:[]},
  { id:"insecure-form-method",type:"body-pattern",title:"Sensitive Form Using GET Method",category:"content",severity:"MEDIUM",description:"Forms handling sensitive data (passwords, credit cards) use GET method.",evidence:"Found forms with sensitive inputs using method='GET'.",riskImpact:"GET parameters appear in URLs, browser history, server logs, and referrer headers.",explanation:"Sensitive data submitted via GET is visible everywhere - URLs, proxy logs, bookmarks, and browser history.",fixSteps:["Change form method to POST for sensitive data.","Use HTTPS for all form submissions."],codeExamples:[]},
  { id:"accessible-source-code",type:"body-pattern",title:"Application Source Code Exposed",category:"information-disclosure",severity:"HIGH",description:"Server-side source code (PHP, Python, Ruby, Java) exposed in response.",evidence:"Detected server-side language code patterns in response.",riskImpact:"Exposed source code reveals application logic, database queries, and potential vulnerabilities.",explanation:"Server-side code should be processed by the application server, not served as raw text.",fixSteps:["Ensure web server processes all server-side files.","Check file extension handlers are properly configured."],codeExamples:[]},
  { id:"x-aspnetmvc-version",type:"combined",title:"ASP.NET MVC Version Disclosed",category:"headers",severity:"LOW",description:"The X-AspNetMvc-Version header reveals the framework version.",evidence:"X-AspNetMvc-Version header is present.",riskImpact:"Disclosing the ASP.NET MVC version helps attackers target known vulnerabilities.",explanation:"This header is automatically added by ASP.NET MVC. It should be removed in production.",fixSteps:["Add MvcHandler.DisableMvcResponseHeader = true in Global.asax.","Remove via web.config custom headers."],codeExamples:[]},
  { id:"x-generator-header",type:"combined",title:"X-Generator Header Disclosed",category:"headers",severity:"LOW",description:"The X-Generator header reveals the CMS or framework used.",evidence:"X-Generator header is present.",riskImpact:"Revealing the CMS or framework helps attackers find known vulnerabilities.",explanation:"The X-Generator header is set by many CMS platforms. It should be removed in production.",fixSteps:["Remove X-Generator header in server configuration.","In WordPress, use remove_action('wp_head', 'wp_generator')."],codeExamples:[]},
  { id:"open-cors-methods",type:"combined",title:"CORS Allows Dangerous HTTP Methods",category:"headers",severity:"MEDIUM",description:"Access-Control-Allow-Methods includes PUT, DELETE, or PATCH without restriction.",evidence:"CORS allows dangerous HTTP methods.",riskImpact:"Allowing PUT/DELETE/PATCH via CORS can enable cross-origin data modification.",explanation:"CORS method restrictions should only allow methods actually needed by legitimate cross-origin requests.",fixSteps:["Restrict Access-Control-Allow-Methods to only required methods.","Avoid allowing PUT, DELETE, PATCH unless necessary."],codeExamples:[]},
  { id:"insecure-cookie-domain",type:"combined",title:"Cookie Domain Set Too Broadly",category:"cookies",severity:"MEDIUM",description:"A cookie domain is set to a parent domain, making it accessible to all subdomains.",evidence:"Cookie domain set to parent domain level.",riskImpact:"Broadly scoped cookies are sent to all subdomains, including potentially untrusted ones.",explanation:"Setting cookie domain to .example.com sends the cookie to all subdomains. A compromised subdomain can steal these cookies.",fixSteps:["Scope cookies to the specific subdomain that needs them.","Avoid setting domain on cookies when possible (defaults to exact origin)."],codeExamples:[]},
  { id:"multiple-csp-headers",type:"combined",title:"Multiple Conflicting CSP Headers",category:"headers",severity:"MEDIUM",description:"Multiple Content-Security-Policy headers detected which may conflict.",evidence:"Found multiple CSP headers in the response.",riskImpact:"Multiple CSP headers create an intersection of policies, potentially being more restrictive or confusing than intended.",explanation:"When multiple CSP headers are present, browsers enforce the intersection. This can lead to unexpected blocking or gaps.",fixSteps:["Consolidate all CSP directives into a single header.","Use report-only for testing new policies."],codeExamples:[]},
  { id:"trace-method-enabled",type:"combined",title:"HTTP TRACE Method May Be Enabled",category:"configuration",severity:"MEDIUM",description:"The server may have HTTP TRACE method enabled.",evidence:"Server did not return Method Not Allowed for TRACE indicators.",riskImpact:"TRACE method can be used for Cross-Site Tracing (XST) attacks to steal credentials.",explanation:"HTTP TRACE reflects the request back, potentially exposing authentication headers and cookies.",fixSteps:["Disable TRACE method in server configuration.","In Apache: TraceEnable Off","In Nginx: if ($request_method = TRACE) { return 405; }"],codeExamples:[]},
  { id:"exposed-swagger-ui",type:"body-pattern",title:"Swagger/OpenAPI Documentation Exposed",category:"information-disclosure",severity:"MEDIUM",description:"Swagger UI or OpenAPI documentation found publicly accessible.",evidence:"Detected Swagger UI or OpenAPI spec references.",riskImpact:"API documentation reveals all endpoints, parameters, and authentication mechanisms.",explanation:"Public API docs help attackers understand your API surface and craft targeted attacks.",fixSteps:["Restrict Swagger/API docs to authenticated users.","Block access in production environments.","Use API gateways with proper auth."],codeExamples:[]},
  { id:"exposed-graphql-playground",type:"body-pattern",title:"GraphQL Playground/Explorer Exposed",category:"information-disclosure",severity:"HIGH",description:"GraphQL Playground, GraphiQL, or Apollo Explorer is publicly accessible.",evidence:"Detected GraphQL IDE references in page source.",riskImpact:"GraphQL IDEs allow attackers to explore your schema, run arbitrary queries, and extract data.",explanation:"GraphQL development tools should be disabled in production to prevent unauthorized schema exploration.",fixSteps:["Disable GraphQL Playground/GraphiQL in production.","Implement authentication for GraphQL endpoints.","Disable introspection in production."],codeExamples:[]},
  { id:"cdn-integrity-missing",type:"body-pattern",title:"CDN Resources Without Integrity Verification",category:"content",severity:"MEDIUM",description:"Resources loaded from CDNs without Subresource Integrity (SRI).",evidence:"Found CDN resources (cdnjs, jsdelivr, unpkg, etc.) without integrity attribute.",riskImpact:"If a CDN is compromised, malicious code is served to all users without detection.",explanation:"SRI ensures that resources fetched from CDNs haven't been tampered with by verifying a cryptographic hash.",fixSteps:["Add integrity and crossorigin attributes to all CDN resources.","Generate hashes at srihash.org."],codeExamples:[]},
  { id:"autocomplete-cc",type:"body-pattern",title:"Credit Card Fields Without Autocomplete Control",category:"content",severity:"MEDIUM",description:"Credit card input fields without explicit autocomplete settings.",evidence:"Found credit card inputs without autocomplete attribute.",riskImpact:"Browsers may store and autofill credit card data insecurely.",explanation:"Credit card fields should use appropriate autocomplete values (cc-number, cc-exp) or autocomplete=off.",fixSteps:["Set autocomplete='cc-number' for card number fields.","Use autocomplete='off' if autofill is not desired."],codeExamples:[]},
  { id:"form-without-action",type:"body-pattern",title:"Form Without Explicit Action Attribute",category:"content",severity:"LOW",description:"Forms without an explicit action attribute submit to the current URL.",evidence:"Found form elements without action attribute.",riskImpact:"Missing action attributes may cause data to be sent to unintended endpoints via URL manipulation.",explanation:"Forms without action submit to the current URL, which can be manipulated through URL parameters.",fixSteps:["Always set an explicit action attribute on forms.","Use relative or absolute URLs in form actions."],codeExamples:[]},
  { id:"outdated-tls-ciphers",type:"combined",title:"Potentially Weak TLS Cipher Configuration",category:"ssl",severity:"MEDIUM",description:"The server may support weak or outdated TLS cipher suites.",evidence:"Weak cipher suite indicators detected.",riskImpact:"Weak ciphers can be broken to decrypt intercepted traffic.",explanation:"Outdated ciphers like RC4, DES, and export-grade suites are vulnerable to known attacks.",fixSteps:["Configure server to use only modern cipher suites.","Disable TLS 1.0, 1.1 and weak ciphers.","Use Mozilla SSL Configuration Generator."],codeExamples:[]},
  { id:"missing-hpkp-alternative",type:"combined",title:"No Certificate Pinning Mechanism",category:"ssl",severity:"LOW",description:"No certificate pinning mechanism (Expect-CT or CAA record) detected.",evidence:"No certificate pinning or CT enforcement headers found.",riskImpact:"Without certificate pinning, a compromised CA can issue rogue certificates for your domain.",explanation:"Certificate pinning ensures only specific CAs can issue certificates for your domain.",fixSteps:["Use Expect-CT header to enforce Certificate Transparency.","Configure CAA DNS records to restrict authorized CAs."],codeExamples:[]},
  { id:"exposed-server-status",type:"body-pattern",title:"Server Status Page Exposed",category:"information-disclosure",severity:"HIGH",description:"Apache/Nginx server status page is publicly accessible.",evidence:"Detected server status/info page content.",riskImpact:"Server status pages reveal active connections, request URLs, client IPs, and server performance data.",explanation:"mod_status (Apache) and stub_status (Nginx) provide operational data useful for reconnaissance.",fixSteps:["Restrict server-status to localhost only.","In Apache: Require local.","In Nginx: allow 127.0.0.1; deny all;"],codeExamples:[]},
  { id:"cookie-no-path",type:"combined",title:"Cookie Without Path Restriction",category:"cookies",severity:"LOW",description:"Cookies set without explicit Path attribute default to the current directory.",evidence:"Cookie missing explicit Path attribute.",riskImpact:"Cookies without path restriction may be sent to unintended URL paths.",explanation:"Setting an explicit Path limits which URLs receive the cookie, reducing the attack surface.",fixSteps:["Set explicit Path=/ or a more restrictive path on all cookies."],codeExamples:[]},
  { id:"dangling-markup-injection",type:"body-pattern",title:"Potential Dangling Markup Injection",category:"content",severity:"MEDIUM",description:"Unclosed HTML tags or attributes that could enable dangling markup injection.",evidence:"Found unclosed tag/attribute patterns susceptible to dangling markup.",riskImpact:"Dangling markup injection can exfiltrate page data to attacker-controlled servers.",explanation:"Unclosed HTML attributes or tags can capture subsequent page content and send it to external URLs.",fixSteps:["Ensure all HTML tags and attributes are properly closed.","Use a strict HTML validator.","Implement CSP to block inline styles and restrict form actions."],codeExamples:[]},
  { id:"exposed-docker-config",type:"body-pattern",title:"Docker Configuration Exposed",category:"information-disclosure",severity:"HIGH",description:"Docker configuration files (docker-compose.yml, Dockerfile) exposed.",evidence:"Detected Docker configuration patterns in response.",riskImpact:"Docker configs reveal infrastructure layout, environment variables, and service dependencies.",explanation:"Docker files contain deployment architecture and often reference secrets through environment variables.",fixSteps:["Block access to Docker files in web server config.","Move Docker files outside the web root."],codeExamples:[]},
  { id:"insecure-jsonp",type:"body-pattern",title:"JSONP Endpoint Detected",category:"content",severity:"HIGH",description:"JSONP callback patterns detected which can lead to data theft.",evidence:"Found JSONP callback parameter usage.",riskImpact:"JSONP endpoints can be exploited for cross-origin data theft since they bypass same-origin policy.",explanation:"JSONP wraps data in a callback function, making it loadable as a script from any origin.",fixSteps:["Replace JSONP with CORS-enabled JSON APIs.","If JSONP is required, validate the callback parameter strictly."],codeExamples:[]},
  { id:"reflected-input",type:"body-pattern",title:"Potential Reflected Input in Response",category:"content",severity:"HIGH",description:"URL parameters appear to be reflected directly in the HTML response.",evidence:"Detected URL parameter values reflected in page content.",riskImpact:"Reflected input without sanitization is the primary vector for reflected XSS attacks.",explanation:"When user input from URL parameters appears unescaped in the HTML response, it enables XSS.",fixSteps:["HTML-encode all reflected output.","Use Content-Security-Policy to mitigate XSS impact.","Implement input validation on all parameters."],codeExamples:[]},
  { id:"hsts-short-max-age",type:"combined",title:"HSTS max-age Too Short",category:"headers",severity:"MEDIUM",description:"The HSTS max-age is set to less than 6 months.",evidence:"HSTS max-age is less than 15768000 seconds.",riskImpact:"Short HSTS max-age means the protection expires quickly, leaving gaps for SSL stripping attacks.",explanation:"HSTS max-age should be at least 1 year (31536000) for effective protection. Shorter values leave windows of vulnerability.",fixSteps:["Set HSTS max-age to at least 31536000 (1 year).","Consider adding includeSubDomains and preload."],codeExamples:[]},
  { id:"xss-reflected-error",type:"body-pattern",title:"Error Messages Reflecting User Input",category:"content",severity:"HIGH",description:"Error messages that reflect user input detected, potential reflected XSS.",evidence:"Found error messages containing URL parameters or user input.",riskImpact:"Error messages reflecting input are a classic reflected XSS vector.",explanation:"When error pages include the invalid input in the error message without encoding, XSS is possible.",fixSteps:["HTML-encode all user input in error messages.","Use generic error messages that don't include input values."],codeExamples:[]},
]

// Read existing file
const data = JSON.parse(readFileSync("lib/scanner/checks-data.json", "utf-8"))
console.log(`Existing checks: ${data.checks.length}`)

// Add new checks
data.checks.push(...newChecks)
data.version = "2.0.0"
console.log(`Total checks after adding: ${data.checks.length}`)

writeFileSync("lib/scanner/checks-data.json", JSON.stringify(data, null, 2))
console.log("Done writing checks-data.json")
