import json, os

# Try multiple possible paths
for candidate in [
    'lib/scanner/checks-data.json',
    os.path.join(os.getcwd(), 'lib/scanner/checks-data.json'),
    '/vercel/share/v0-project/lib/scanner/checks-data.json',
    '/vercel/share/v0-next-shadcn/lib/scanner/checks-data.json',
]:
    if os.path.exists(candidate):
        path = candidate
        break
else:
    # List directories to find it
    print("CWD:", os.getcwd())
    for root, dirs, files in os.walk(os.getcwd()):
        for f in files:
            if f == 'checks-data.json':
                path = os.path.join(root, f)
                print(f"Found at: {path}")
                break
        else:
            continue
        break
    else:
        print("ERROR: checks-data.json not found anywhere")
        exit(1)

print(f"Using: {path}")

with open(path, 'r') as f:
    data = json.load(f)

print(f"Current checks: {len(data['checks'])}")

new_checks = [
    {"id":"coep-missing","type":"header-missing","title":"Cross-Origin-Embedder-Policy Missing","category":"headers","severity":"LOW","description":"COEP header is not set.","evidence":"Cross-Origin-Embedder-Policy header not found.","riskImpact":"Without COEP, cross-origin resources can be loaded without explicit permission.","explanation":"COEP requires all resources to grant permission via CORS or CORP headers.","recommendation":"Add Cross-Origin-Embedder-Policy: require-corp header.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy","headerName":"cross-origin-embedder-policy"},
    {"id":"nel-missing","type":"header-missing","title":"Network Error Logging Not Configured","category":"headers","severity":"LOW","description":"NEL header is not set.","evidence":"NEL header not found.","riskImpact":"Network errors go undetected without NEL.","explanation":"NEL allows browsers to report network errors to a specified endpoint.","recommendation":"Configure NEL header with a reporting endpoint.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Network_Error_Logging","headerName":"nel"},
    {"id":"report-to-missing","type":"header-missing","title":"Report-To Header Missing","category":"headers","severity":"LOW","description":"Report-To header is not configured.","evidence":"Report-To header not found.","riskImpact":"CSP violations and other errors cannot be reported.","explanation":"Report-To defines endpoints where browsers send violation and error reports.","recommendation":"Add Report-To header with a reporting group.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to","headerName":"report-to"},
    {"id":"expect-ct-missing","type":"header-missing","title":"Expect-CT Header Missing","category":"headers","severity":"LOW","description":"Expect-CT header is not set.","evidence":"Expect-CT header not found.","riskImpact":"Misissued certificates may not be detected.","explanation":"Expect-CT enforces Certificate Transparency requirements.","recommendation":"Add Expect-CT header with enforce and max-age directives.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT","headerName":"expect-ct"},
    {"id":"timing-allow-origin","type":"header-present","title":"Timing-Allow-Origin Wildcard","category":"headers","severity":"LOW","description":"Timing-Allow-Origin set to wildcard.","evidence":"Timing-Allow-Origin: * detected.","riskImpact":"Exposes detailed timing data to any origin.","explanation":"This header controls which origins can read performance timing data.","recommendation":"Restrict Timing-Allow-Origin to trusted domains.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin","headerName":"timing-allow-origin","headerValue":"*"},
    {"id":"powered-by-header","type":"header-present","title":"X-Powered-By Header Exposed","category":"headers","severity":"LOW","description":"X-Powered-By header reveals technology stack.","evidence":"X-Powered-By header detected.","riskImpact":"Attackers can target known vulnerabilities for the disclosed technology.","explanation":"This header reveals backend framework or language information.","recommendation":"Remove the X-Powered-By header.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-powered-by"},
    {"id":"aspnet-version","type":"header-present","title":"X-AspNet-Version Header Exposed","category":"headers","severity":"LOW","description":"ASP.NET version disclosed via header.","evidence":"X-AspNet-Version header detected.","riskImpact":"Reveals exact ASP.NET version for targeted attacks.","explanation":"This header is added by ASP.NET and discloses the framework version.","recommendation":"Remove X-AspNet-Version in web.config.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-aspnet-version"},
    {"id":"aspnetmvc-version","type":"header-present","title":"X-AspNetMvc-Version Header Exposed","category":"headers","severity":"LOW","description":"ASP.NET MVC version disclosed.","evidence":"X-AspNetMvc-Version header detected.","riskImpact":"Reveals exact MVC framework version.","explanation":"This header discloses the ASP.NET MVC version in use.","recommendation":"Remove X-AspNetMvc-Version header.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-aspnetmvc-version"},
    {"id":"via-header-disclosure","type":"header-present","title":"Via Header Reveals Proxy Info","category":"headers","severity":"LOW","description":"Via header discloses proxy information.","evidence":"Via header detected.","riskImpact":"Reveals internal infrastructure and proxy chain.","explanation":"The Via header is added by proxies, exposing network topology.","recommendation":"Strip Via header at the edge proxy.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via","headerName":"via"},
    {"id":"etag-inode","type":"body-pattern","title":"ETag Leaks Inode Information","category":"information-disclosure","severity":"LOW","description":"ETag header contains inode information.","evidence":"ETag with inode-size-timestamp format detected.","riskImpact":"Inode numbers reveal filesystem details.","explanation":"Apache sometimes includes inode numbers in ETags.","recommendation":"Configure FileETag directive to exclude inode.","references":"https://httpd.apache.org/docs/2.4/mod/core.html#fileetag"},
    {"id":"cookie-prefix-missing","type":"body-pattern","title":"Cookies Missing __Host- or __Secure- Prefix","category":"cookies","severity":"LOW","description":"Sensitive cookies lack security prefixes.","evidence":"Session cookies without __Host- or __Secure- prefix.","riskImpact":"Cookies lack browser-enforced constraints.","explanation":"Cookie prefixes add extra security guarantees enforced by browsers.","recommendation":"Use __Host- prefix for session cookies on HTTPS.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes"},
    {"id":"cookie-expires-long","type":"body-pattern","title":"Cookie With Excessively Long Expiration","category":"cookies","severity":"LOW","description":"Cookies set to expire far in the future.","evidence":"Cookie with max-age exceeding 1 year detected.","riskImpact":"Long-lived cookies increase the window for theft.","explanation":"Cookies that persist for years are a security risk.","recommendation":"Set reasonable max-age values.","references":"https://owasp.org/www-community/controls/SecureCookieAttribute"},
    {"id":"samesite-none-cookie","type":"body-pattern","title":"Cookie SameSite=None Without Secure","category":"cookies","severity":"MEDIUM","description":"Cookie has SameSite=None but no Secure flag.","evidence":"SameSite=None cookie without Secure attribute.","riskImpact":"Cookie will be rejected by modern browsers.","explanation":"Browsers require SameSite=None cookies to also have Secure.","recommendation":"Add Secure flag to all SameSite=None cookies.","references":"https://web.dev/samesite-cookies-explained/"},
    {"id":"csp-unsafe-inline","type":"body-pattern","title":"CSP Allows unsafe-inline Scripts","category":"headers","severity":"HIGH","description":"Content Security Policy permits inline scripts.","evidence":"CSP contains unsafe-inline in script-src.","riskImpact":"Inline scripts negate most XSS protections.","explanation":"unsafe-inline allows execution of inline scripts and event handlers.","recommendation":"Use nonce-based or hash-based CSP instead.","references":"https://content-security-policy.com/unsafe-inline/"},
    {"id":"csp-unsafe-eval","type":"body-pattern","title":"CSP Allows unsafe-eval","category":"headers","severity":"HIGH","description":"Content Security Policy permits eval().","evidence":"CSP contains unsafe-eval in script-src.","riskImpact":"eval() can execute attacker-injected strings as code.","explanation":"unsafe-eval allows dynamic code execution via eval() and Function().","recommendation":"Remove unsafe-eval and refactor code.","references":"https://content-security-policy.com/unsafe-eval/"},
    {"id":"csp-wildcard-src","type":"body-pattern","title":"CSP Uses Wildcard Source","category":"headers","severity":"MEDIUM","description":"Content Security Policy uses * source.","evidence":"CSP contains wildcard (*) source directive.","riskImpact":"Any origin can serve content.","explanation":"Wildcard sources allow loading resources from any origin.","recommendation":"Replace * with specific trusted domains.","references":"https://content-security-policy.com/"},
    {"id":"autocomplete-password","type":"body-pattern","title":"Password Fields Allow Autocomplete","category":"content","severity":"LOW","description":"Password inputs allow browser autocomplete.","evidence":"Password input without autocomplete attribute.","riskImpact":"Stored passwords can be extracted by XSS.","explanation":"Browsers may store passwords in autocomplete.","recommendation":"Add autocomplete=new-password to password fields.","references":"https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion"},
    {"id":"form-no-csrf","type":"body-pattern","title":"Forms Without CSRF Token","category":"content","severity":"HIGH","description":"POST forms lack CSRF protection tokens.","evidence":"Form with method=POST missing hidden CSRF token field.","riskImpact":"Attackers can forge form submissions.","explanation":"CSRF tokens ensure submissions originate from your site.","recommendation":"Add CSRF token to all POST forms.","references":"https://owasp.org/www-community/attacks/csrf"},
    {"id":"js-eval-usage","type":"body-pattern","title":"JavaScript eval() Usage Detected","category":"content","severity":"MEDIUM","description":"Direct eval() calls found in page scripts.","evidence":"eval() function calls detected in JavaScript.","riskImpact":"eval() can execute arbitrary code.","explanation":"eval() interprets strings as code, creating injection risks.","recommendation":"Replace eval() with JSON.parse() or safe alternatives.","references":"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval"},
    {"id":"document-write","type":"body-pattern","title":"document.write() Usage Detected","category":"content","severity":"LOW","description":"document.write() calls found in page.","evidence":"document.write() detected in scripts.","riskImpact":"Can be exploited for XSS if input is not sanitized.","explanation":"document.write() injects HTML directly.","recommendation":"Use DOM methods like createElement instead.","references":"https://developer.mozilla.org/en-US/docs/Web/API/Document/write"},
    {"id":"innerhtml-assignment","type":"body-pattern","title":"Unsafe innerHTML Assignment","category":"content","severity":"MEDIUM","description":"innerHTML assignment with dynamic data detected.","evidence":"innerHTML = or innerHTML += patterns found.","riskImpact":"innerHTML can execute injected scripts.","explanation":"Setting innerHTML with user input creates XSS vulnerabilities.","recommendation":"Use textContent or sanitize with DOMPurify.","references":"https://owasp.org/www-community/xss-filter-evasion-cheatsheet"},
    {"id":"postmessage-no-origin","type":"body-pattern","title":"postMessage Without Origin Check","category":"content","severity":"HIGH","description":"window.postMessage used without origin validation.","evidence":"addEventListener message without origin check.","riskImpact":"Any page can send messages to your window.","explanation":"Without validating event.origin, any site can communicate.","recommendation":"Always check event.origin in message handlers.","references":"https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage"},
    {"id":"json-hijacking","type":"body-pattern","title":"JSON Response Without Protection","category":"content","severity":"MEDIUM","description":"JSON array response vulnerable to hijacking.","evidence":"JSON response starts with [ character.","riskImpact":"Legacy browsers may allow JSON hijacking.","explanation":"JSON arrays can be intercepted via script tag inclusion.","recommendation":"Wrap JSON responses in an object.","references":"https://owasp.org/www-community/attacks/JSON_Hijacking"},
    {"id":"graphql-introspection","type":"body-pattern","title":"GraphQL Introspection Enabled","category":"information-disclosure","severity":"MEDIUM","description":"GraphQL endpoint allows introspection.","evidence":"GraphQL introspection or /graphql endpoint detected.","riskImpact":"Reveals entire API schema and types.","explanation":"Introspection lets anyone discover your full API structure.","recommendation":"Disable introspection in production.","references":"https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/"},
    {"id":"swagger-exposed","type":"body-pattern","title":"API Documentation Publicly Accessible","category":"information-disclosure","severity":"MEDIUM","description":"Swagger/OpenAPI documentation found exposed.","evidence":"References to /swagger, /api-docs, or openapi.json.","riskImpact":"API docs reveal all endpoints and parameters.","explanation":"Public API docs help attackers understand your API.","recommendation":"Restrict API docs to authenticated users.","references":"https://owasp.org/API-Security/"},
    {"id":"wp-version-exposed","type":"body-pattern","title":"WordPress Version Exposed","category":"information-disclosure","severity":"LOW","description":"WordPress version number found in source.","evidence":"WordPress version meta tag or generator detected.","riskImpact":"Version info helps find known vulnerabilities.","explanation":"WordPress adds version info to meta tags by default.","recommendation":"Remove version info with remove_action.","references":"https://developer.wordpress.org/plugins/security/"},
    {"id":"aws-metadata","type":"body-pattern","title":"AWS Metadata Endpoint Reference","category":"information-disclosure","severity":"CRITICAL","description":"Reference to AWS metadata endpoint detected.","evidence":"AWS metadata IP 169.254.169.254 found.","riskImpact":"SSRF to metadata can steal IAM credentials.","explanation":"AWS metadata service provides credentials accessible from instances.","recommendation":"Block metadata access; use IMDSv2.","references":"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html"},
    {"id":"error-page-info","type":"body-pattern","title":"Verbose Error Page Information","category":"information-disclosure","severity":"MEDIUM","description":"Detailed error information exposed.","evidence":"Stack traces, SQL errors, or framework errors detected.","riskImpact":"Error details reveal file paths and database structure.","explanation":"Verbose error pages leak implementation details.","recommendation":"Use custom error pages.","references":"https://owasp.org/www-community/Improper_Error_Handling"},
    {"id":"git-exposed","type":"body-pattern","title":".git Directory Potentially Exposed","category":"information-disclosure","severity":"HIGH","description":"References to .git directory found.","evidence":".git/ path or git metadata detected.","riskImpact":"Exposed .git allows downloading entire source code.","explanation":"Accessible .git lets attackers reconstruct your repo.","recommendation":"Block access to .git directory.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"env-file-exposed","type":"body-pattern","title":".env File Reference Detected","category":"information-disclosure","severity":"CRITICAL","description":"References to .env file found.","evidence":".env file path or content detected.","riskImpact":"Exposed .env files contain credentials and secrets.","explanation":".env files should never be web-accessible.","recommendation":"Block .env access in web server config.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"backup-files","type":"body-pattern","title":"Backup File References Detected","category":"information-disclosure","severity":"MEDIUM","description":"References to backup files found.","evidence":"References to .bak, .old, .orig files detected.","riskImpact":"Backup files may contain source code or dumps.","explanation":"Backup files on servers can expose previous code versions.","recommendation":"Remove backup files from production.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"sql-error-messages","type":"body-pattern","title":"SQL Error Messages Exposed","category":"information-disclosure","severity":"HIGH","description":"SQL error messages found in response.","evidence":"Database error messages detected in output.","riskImpact":"SQL errors reveal database type and structure.","explanation":"Unhandled SQL errors expose database internals.","recommendation":"Catch database errors and show generic messages.","references":"https://owasp.org/www-community/attacks/SQL_Injection"},
    {"id":"path-traversal-patterns","type":"body-pattern","title":"Path Traversal Patterns Detected","category":"content","severity":"HIGH","description":"Path traversal sequences found.","evidence":"../ or ..%2f patterns detected.","riskImpact":"Path traversal can access files outside web root.","explanation":"Unvalidated file paths allow reading arbitrary files.","recommendation":"Validate and canonicalize all file paths.","references":"https://owasp.org/www-community/attacks/Path_Traversal"},
    {"id":"insecure-websocket","type":"body-pattern","title":"Insecure WebSocket Connection (ws://)","category":"content","severity":"MEDIUM","description":"WebSocket using unencrypted ws:// protocol.","evidence":"ws:// connection detected instead of wss://.","riskImpact":"WebSocket data transmitted in plaintext.","explanation":"ws:// connections are not encrypted unlike wss://.","recommendation":"Use wss:// for all WebSocket connections.","references":"https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API"},
    {"id":"cors-null-origin","type":"body-pattern","title":"CORS Allows null Origin","category":"headers","severity":"HIGH","description":"CORS Access-Control-Allow-Origin set to null.","evidence":"Access-Control-Allow-Origin: null detected.","riskImpact":"Sandboxed iframes and data: URLs use null origin.","explanation":"Allowing null origin enables CORS bypass from sandboxed contexts.","recommendation":"Never allow null as a CORS origin.","references":"https://portswigger.net/web-security/cors"},
    {"id":"mixed-content-form","type":"body-pattern","title":"Form Submits to HTTP Endpoint","category":"content","severity":"HIGH","description":"HTTPS page contains form posting to HTTP.","evidence":"Form action pointing to http:// URL.","riskImpact":"Form data transmitted unencrypted.","explanation":"Mixed content forms leak sensitive data over insecure connections.","recommendation":"Ensure all form actions use HTTPS.","references":"https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content"},
    {"id":"target-blank-noreferrer","type":"body-pattern","title":"Links Missing rel=noreferrer","category":"content","severity":"LOW","description":"External links with target=_blank lack noreferrer.","evidence":"Links with target=_blank missing rel=noreferrer.","riskImpact":"Referrer information leaked to external sites.","explanation":"Without noreferrer, the target page receives your URL as referrer.","recommendation":"Add rel=noreferrer to external target=_blank links.","references":"https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer"},
    {"id":"jwt-exposed","type":"body-pattern","title":"JWT Token Exposed in Page Source","category":"information-disclosure","severity":"HIGH","description":"JSON Web Token found in page source.","evidence":"JWT pattern (eyJ...) detected in HTML.","riskImpact":"Exposed tokens allow session hijacking.","explanation":"JWTs in page source can be stolen by XSS attacks.","recommendation":"Never embed JWTs in HTML; use HttpOnly cookies.","references":"https://owasp.org/www-community/attacks/JSON_Web_Token"},
    {"id":"internal-ip-disclosure","type":"body-pattern","title":"Internal IP Address Disclosed","category":"information-disclosure","severity":"MEDIUM","description":"Private IP addresses found in response.","evidence":"RFC 1918 private IP address detected.","riskImpact":"Internal IPs reveal network topology.","explanation":"Private addresses like 10.x, 172.16-31.x, 192.168.x expose infrastructure.","recommendation":"Sanitize responses to remove internal IP addresses.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"base-tag-injection","type":"body-pattern","title":"Base Tag Present - Potential Injection","category":"content","severity":"MEDIUM","description":"HTML base tag detected.","evidence":"<base href=> tag found in page.","riskImpact":"Injected base tags can redirect all relative URLs.","explanation":"Base tag injection changes the base URL for all relative paths.","recommendation":"Avoid using base tags or ensure they cannot be injected.","references":"https://owasp.org/www-community/attacks/Content_Security_Policy"},
    {"id":"file-upload-no-validation","type":"body-pattern","title":"File Upload Without Type Validation","category":"content","severity":"MEDIUM","description":"File upload form without accept attribute.","evidence":"Input type=file without accept restriction.","riskImpact":"Unrestricted uploads can lead to code execution.","explanation":"Without type validation, malicious files may be uploaded.","recommendation":"Add accept attribute and validate server-side.","references":"https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload"},
    {"id":"srp-protocol-downgrade","type":"body-pattern","title":"Protocol Downgrade References","category":"configuration","severity":"MEDIUM","description":"HTTP references on HTTPS page suggest downgrade.","evidence":"http:// URLs found on HTTPS page source.","riskImpact":"Protocol downgrades expose data to MitM attacks.","explanation":"Loading HTTP resources on HTTPS breaks the security chain.","recommendation":"Ensure all resources use HTTPS.","references":"https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content"},
    {"id":"cache-sensitive-data","type":"header-present","title":"Sensitive Page Missing Cache-Control","category":"headers","severity":"MEDIUM","description":"Page with forms missing no-store cache directive.","evidence":"Page with forms lacks Cache-Control: no-store.","riskImpact":"Sensitive data cached in browser or CDN.","explanation":"Without no-store, form data pages may be cached.","recommendation":"Add Cache-Control: no-store to sensitive pages.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control","headerName":"cache-control"},
    {"id":"age-header-cdn","type":"header-present","title":"CDN Cache Age Reveals Architecture","category":"headers","severity":"LOW","description":"Age header exposes CDN caching details.","evidence":"Age header detected in response.","riskImpact":"Reveals CDN usage and caching behavior.","explanation":"Age header shows how long content has been cached.","recommendation":"Consider stripping Age header at edge.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age","headerName":"age"},
    {"id":"debug-header","type":"header-present","title":"Debug Header Detected","category":"headers","severity":"HIGH","description":"Debug or diagnostic header found.","evidence":"X-Debug, X-Debug-Token, or similar header detected.","riskImpact":"Debug headers reveal internal state and IDs.","explanation":"Debug headers left in production expose diagnostic info.","recommendation":"Remove all debug headers in production.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-debug-token"},
    {"id":"sourcemap-exposed","type":"body-pattern","title":"JavaScript Source Maps Exposed","category":"information-disclosure","severity":"MEDIUM","description":"Source map references found in JavaScript.","evidence":"sourceMappingURL detected in scripts.","riskImpact":"Source maps reveal original unminified source code.","explanation":"Source maps in production allow viewing original code.","recommendation":"Remove sourceMappingURL in production builds.","references":"https://developer.chrome.com/docs/devtools/javascript/source-maps/"},
    {"id":"open-redirect","type":"body-pattern","title":"Potential Open Redirect","category":"content","severity":"MEDIUM","description":"URL redirect parameters detected.","evidence":"URL parameters like redirect=, url=, next= found.","riskImpact":"Open redirects enable phishing attacks.","explanation":"Unvalidated redirect parameters can send users to malicious sites.","recommendation":"Validate redirect URLs against an allowlist.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"clickjacking-no-ancestors","type":"body-pattern","title":"CSP Missing frame-ancestors Directive","category":"headers","severity":"MEDIUM","description":"No frame-ancestors in Content Security Policy.","evidence":"CSP lacks frame-ancestors directive.","riskImpact":"Page may be framed by malicious sites.","explanation":"frame-ancestors provides clickjacking protection via CSP.","recommendation":"Add frame-ancestors 'self' to CSP.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors"},
    {"id":"subresource-integrity","type":"body-pattern","title":"External Scripts Missing SRI","category":"content","severity":"MEDIUM","description":"External scripts loaded without integrity hash.","evidence":"Script tags with external src missing integrity attribute.","riskImpact":"Compromised CDN can inject malicious code.","explanation":"SRI ensures scripts match expected content hashes.","recommendation":"Add integrity and crossorigin attributes to external scripts.","references":"https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity"},
    {"id":"clear-site-data-missing","type":"header-missing","title":"Clear-Site-Data Header Not Used on Logout","category":"headers","severity":"LOW","description":"No Clear-Site-Data header on logout endpoint.","evidence":"Clear-Site-Data header not found.","riskImpact":"Session data may persist after logout.","explanation":"Clear-Site-Data instructs browsers to clear stored data.","recommendation":"Send Clear-Site-Data header on logout responses.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data","headerName":"clear-site-data"},
    {"id":"feature-policy","type":"header-missing","title":"Permissions-Policy Header Missing","category":"headers","severity":"LOW","description":"Permissions-Policy (Feature-Policy) not set.","evidence":"Permissions-Policy header not found.","riskImpact":"Browser features like camera and mic are unrestricted.","explanation":"Permissions-Policy controls which browser features your site can use.","recommendation":"Add Permissions-Policy to restrict unnecessary features.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy","headerName":"permissions-policy"},
    {"id":"access-control-expose","type":"header-present","title":"CORS Exposes Sensitive Headers","category":"headers","severity":"LOW","description":"Access-Control-Expose-Headers is too broad.","evidence":"Multiple sensitive headers exposed via CORS.","riskImpact":"Exposed headers may leak sensitive information.","explanation":"CORS Expose-Headers lets JavaScript access response headers.","recommendation":"Only expose necessary headers via CORS.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers","headerName":"access-control-expose-headers"},
    {"id":"iframe-sandbox","type":"body-pattern","title":"Iframes Without Sandbox Attribute","category":"content","severity":"MEDIUM","description":"Iframe elements missing sandbox attribute.","evidence":"Iframe tags without sandbox restriction.","riskImpact":"Unsandboxed iframes have full page permissions.","explanation":"Sandbox restricts what embedded content can do.","recommendation":"Add sandbox attribute with minimal permissions.","references":"https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox"},
    {"id":"dangling-markup","type":"body-pattern","title":"Dangling Markup Pattern Detected","category":"content","severity":"MEDIUM","description":"Unclosed tags or attributes that may leak data.","evidence":"Potential dangling markup injection point detected.","riskImpact":"Dangling markup can exfiltrate page content.","explanation":"Unclosed attributes in injected HTML can capture subsequent content.","recommendation":"Sanitize all user inputs and close all tags properly.","references":"https://portswigger.net/web-security/cross-site-scripting/dangling-markup"},
    {"id":"php-errors-exposed","type":"body-pattern","title":"PHP Error Messages Exposed","category":"information-disclosure","severity":"HIGH","description":"PHP error or warning messages found.","evidence":"PHP Fatal error, Warning, or Notice detected.","riskImpact":"PHP errors reveal file paths and code structure.","explanation":"Visible PHP errors expose server internals.","recommendation":"Set display_errors=Off and log_errors=On.","references":"https://www.php.net/manual/en/errorfunc.configuration.php"},
    {"id":"cors-credentials-wildcard","type":"body-pattern","title":"CORS Credentials With Wildcard Origin","category":"headers","severity":"CRITICAL","description":"CORS allows credentials with wildcard origin.","evidence":"Access-Control-Allow-Credentials: true with Allow-Origin: *.","riskImpact":"Any site can make authenticated requests.","explanation":"This combination allows any origin to send credentialed requests.","recommendation":"Never combine credentials: true with wildcard origin.","references":"https://portswigger.net/web-security/cors"},
]

# Check for duplicates
existing_ids = {c['id'] for c in data['checks']}
added = 0
for check in new_checks:
    if check['id'] not in existing_ids:
        data['checks'].append(check)
        added += 1

with open(path, 'w') as f:
    json.dump(data, f, indent=2)

print(f"Added {added} new checks. Total: {len(data['checks'])}")
