import json, os

path = os.path.join(os.path.dirname(__file__), '..', 'lib', 'scanner', 'checks-data.json')

with open(path, 'r') as f:
    data = json.load(f)

new_checks = [
    {"id":"coep-missing","type":"header-missing","title":"Cross-Origin-Embedder-Policy Missing","category":"headers","severity":"LOW","description":"COEP header is not set.","evidence":"Cross-Origin-Embedder-Policy header not found.","riskImpact":"Without COEP, cross-origin resources can be loaded without explicit permission.","explanation":"COEP requires all resources to grant permission via CORS or CORP headers.","recommendation":"Add Cross-Origin-Embedder-Policy: require-corp header.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy","headerName":"cross-origin-embedder-policy"},
    {"id":"nel-missing","type":"header-missing","title":"Network Error Logging Not Configured","category":"headers","severity":"LOW","description":"NEL header is not set.","evidence":"NEL header not found.","riskImpact":"Network errors go undetected without NEL.","explanation":"NEL allows browsers to report network errors to a specified endpoint.","recommendation":"Configure NEL header with a reporting endpoint.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Network_Error_Logging","headerName":"nel"},
    {"id":"report-to-missing","type":"header-missing","title":"Report-To Header Missing","category":"headers","severity":"LOW","description":"Report-To header is not configured.","evidence":"Report-To header not found.","riskImpact":"CSP violations and other errors cannot be reported.","explanation":"Report-To defines endpoints where browsers send violation and error reports.","recommendation":"Add Report-To header with a reporting group.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to","headerName":"report-to"},
    {"id":"expect-ct-missing","type":"header-missing","title":"Expect-CT Header Missing","category":"headers","severity":"LOW","description":"Expect-CT header is not set.","evidence":"Expect-CT header not found.","riskImpact":"Misissued certificates may not be detected.","explanation":"Expect-CT enforces Certificate Transparency requirements.","recommendation":"Add Expect-CT header with enforce and max-age directives.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT","headerName":"expect-ct"},
    {"id":"timing-allow-origin","type":"header-present","title":"Timing-Allow-Origin Wildcard","category":"headers","severity":"LOW","description":"Timing-Allow-Origin set to wildcard.","evidence":"Timing-Allow-Origin: * detected.","riskImpact":"Exposes detailed timing data to any origin.","explanation":"This header controls which origins can read performance timing data via the Resource Timing API.","recommendation":"Restrict Timing-Allow-Origin to trusted domains.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin","headerName":"timing-allow-origin","headerValue":"*"},
    {"id":"powered-by-header","type":"header-present","title":"X-Powered-By Header Exposed","category":"headers","severity":"LOW","description":"X-Powered-By header reveals technology stack.","evidence":"X-Powered-By header detected.","riskImpact":"Attackers can target known vulnerabilities for the disclosed technology.","explanation":"This header reveals backend framework or language information.","recommendation":"Remove the X-Powered-By header.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-powered-by"},
    {"id":"aspnet-version","type":"header-present","title":"X-AspNet-Version Header Exposed","category":"headers","severity":"LOW","description":"ASP.NET version disclosed via header.","evidence":"X-AspNet-Version header detected.","riskImpact":"Reveals exact ASP.NET version for targeted attacks.","explanation":"This header is added by ASP.NET and discloses the framework version.","recommendation":"Remove X-AspNet-Version in web.config.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-aspnet-version"},
    {"id":"aspnetmvc-version","type":"header-present","title":"X-AspNetMvc-Version Header Exposed","category":"headers","severity":"LOW","description":"ASP.NET MVC version disclosed.","evidence":"X-AspNetMvc-Version header detected.","riskImpact":"Reveals exact MVC framework version.","explanation":"This header discloses the ASP.NET MVC version in use.","recommendation":"Remove X-AspNetMvc-Version header.","references":"https://owasp.org/www-project-secure-headers/","headerName":"x-aspnetmvc-version"},
    {"id":"via-header-disclosure","type":"header-present","title":"Via Header Reveals Proxy Info","category":"headers","severity":"LOW","description":"Via header discloses proxy/gateway information.","evidence":"Via header detected.","riskImpact":"Reveals internal infrastructure and proxy chain.","explanation":"The Via header is added by proxies and gateways, exposing network topology.","recommendation":"Strip Via header at the edge proxy.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via","headerName":"via"},
    {"id":"etag-inode","type":"body-pattern","title":"ETag Leaks Inode Information","category":"information-disclosure","severity":"LOW","description":"ETag header contains inode information.","evidence":"ETag with inode-size-timestamp format detected.","riskImpact":"Inode numbers reveal filesystem details.","explanation":"Apache sometimes includes inode numbers in ETags which leaks server filesystem info.","recommendation":"Configure FileETag directive to exclude inode.","references":"https://httpd.apache.org/docs/2.4/mod/core.html#fileetag"},
    {"id":"cookie-prefix-missing","type":"body-pattern","title":"Cookies Missing __Host- or __Secure- Prefix","category":"cookies","severity":"LOW","description":"Sensitive cookies lack security prefixes.","evidence":"Session cookies without __Host- or __Secure- prefix.","riskImpact":"Without prefixes, cookies lack additional browser-enforced constraints.","explanation":"Cookie prefixes (__Host- and __Secure-) add extra security guarantees enforced by browsers.","recommendation":"Use __Host- prefix for session cookies on HTTPS.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes"},
    {"id":"cookie-expires-long","type":"body-pattern","title":"Cookie With Excessively Long Expiration","category":"cookies","severity":"LOW","description":"Cookies set to expire far in the future.","evidence":"Cookie with max-age exceeding 1 year detected.","riskImpact":"Long-lived cookies increase the window for session theft.","explanation":"Cookies that persist for years are a security risk if they contain session data.","recommendation":"Set reasonable max-age values; use session cookies where possible.","references":"https://owasp.org/www-community/controls/SecureCookieAttribute"},
    {"id":"samesite-none-cookie","type":"body-pattern","title":"Cookie With SameSite=None Without Secure","category":"cookies","severity":"MEDIUM","description":"Cookie has SameSite=None but lacks Secure flag.","evidence":"SameSite=None cookie without Secure attribute.","riskImpact":"Cookie will be rejected by modern browsers.","explanation":"Browsers require SameSite=None cookies to also have the Secure attribute.","recommendation":"Add Secure flag to all SameSite=None cookies.","references":"https://web.dev/samesite-cookies-explained/"},
    {"id":"csp-unsafe-inline","type":"body-pattern","title":"CSP Allows unsafe-inline Scripts","category":"headers","severity":"HIGH","description":"Content Security Policy permits inline scripts.","evidence":"CSP contains 'unsafe-inline' in script-src.","riskImpact":"Inline scripts negate most XSS protections CSP provides.","explanation":"unsafe-inline allows execution of inline script elements and event handlers.","recommendation":"Use nonce-based or hash-based CSP instead of unsafe-inline.","references":"https://content-security-policy.com/unsafe-inline/"},
    {"id":"csp-unsafe-eval","type":"body-pattern","title":"CSP Allows unsafe-eval","category":"headers","severity":"HIGH","description":"Content Security Policy permits eval().","evidence":"CSP contains 'unsafe-eval' in script-src.","riskImpact":"eval() can execute attacker-injected strings as code.","explanation":"unsafe-eval allows JavaScript eval(), Function(), and similar dynamic code execution.","recommendation":"Remove unsafe-eval and refactor code to avoid eval().","references":"https://content-security-policy.com/unsafe-eval/"},
    {"id":"csp-wildcard-src","type":"body-pattern","title":"CSP Uses Wildcard Source","category":"headers","severity":"MEDIUM","description":"Content Security Policy uses * as a source.","evidence":"CSP contains wildcard (*) source directive.","riskImpact":"Any origin can serve content, defeating CSP protections.","explanation":"Wildcard sources allow loading resources from any origin.","recommendation":"Replace * with specific trusted domains.","references":"https://content-security-policy.com/"},
    {"id":"autocomplete-password","type":"body-pattern","title":"Password Fields Without autocomplete=off","category":"content","severity":"LOW","description":"Password inputs allow browser autocomplete.","evidence":"Password input without autocomplete=\"off\" or autocomplete=\"new-password\".","riskImpact":"Stored passwords can be extracted by XSS or shared computer access.","explanation":"Browsers may store passwords in autocomplete, accessible to other users or scripts.","recommendation":"Add autocomplete=\"new-password\" to password fields.","references":"https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion"},
    {"id":"form-no-csrf","type":"body-pattern","title":"Forms Without CSRF Token","category":"content","severity":"HIGH","description":"POST forms lack visible CSRF protection tokens.","evidence":"Form with method=POST missing hidden CSRF token field.","riskImpact":"Without CSRF tokens, attackers can forge form submissions.","explanation":"CSRF tokens ensure form submissions originate from your site.","recommendation":"Add CSRF token to all POST forms.","references":"https://owasp.org/www-community/attacks/csrf"},
    {"id":"js-eval-usage","type":"body-pattern","title":"JavaScript eval() Usage Detected","category":"content","severity":"MEDIUM","description":"Direct eval() calls found in page scripts.","evidence":"eval() function calls detected in JavaScript.","riskImpact":"eval() can execute arbitrary code if input is attacker-controlled.","explanation":"eval() interprets strings as code, creating injection vulnerabilities.","recommendation":"Replace eval() with JSON.parse() or other safe alternatives.","references":"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!"},
    {"id":"document-write","type":"body-pattern","title":"document.write() Usage Detected","category":"content","severity":"LOW","description":"document.write() calls found in page.","evidence":"document.write() detected in scripts.","riskImpact":"document.write can be exploited for XSS if input is not sanitized.","explanation":"document.write() injects HTML directly and is blocked during streaming.","recommendation":"Use DOM methods like createElement and appendChild instead.","references":"https://developer.mozilla.org/en-US/docs/Web/API/Document/write"},
    {"id":"innerhtml-assignment","type":"body-pattern","title":"Unsafe innerHTML Assignment","category":"content","severity":"MEDIUM","description":"innerHTML assignment with dynamic data detected.","evidence":"innerHTML = or innerHTML += patterns found.","riskImpact":"innerHTML can execute injected scripts if input is unsanitized.","explanation":"Setting innerHTML with user input creates XSS vulnerabilities.","recommendation":"Use textContent or sanitize with DOMPurify before innerHTML.","references":"https://owasp.org/www-community/xss-filter-evasion-cheatsheet"},
    {"id":"postmessage-no-origin","type":"body-pattern","title":"postMessage Without Origin Check","category":"content","severity":"HIGH","description":"window.postMessage used without origin validation.","evidence":"addEventListener('message') without origin check.","riskImpact":"Any page can send messages to your window, potentially triggering unsafe actions.","explanation":"Without validating event.origin, any website can communicate with your page.","recommendation":"Always check event.origin in message event handlers.","references":"https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns"},
    {"id":"json-hijacking","type":"body-pattern","title":"JSON Response Without Protection","category":"content","severity":"MEDIUM","description":"JSON array response vulnerable to hijacking.","evidence":"JSON response starts with [ character.","riskImpact":"Older browsers may allow JSON hijacking via script tag inclusion.","explanation":"JSON arrays can be intercepted by overriding Array constructors in legacy browsers.","recommendation":"Wrap JSON responses in an object or use XSSI protection prefix.","references":"https://owasp.org/www-community/attacks/JSON_Hijacking"},
    {"id":"graphql-introspection","type":"body-pattern","title":"GraphQL Introspection Enabled","category":"information-disclosure","severity":"MEDIUM","description":"GraphQL endpoint allows introspection queries.","evidence":"GraphQL introspection or /graphql endpoint detected.","riskImpact":"Introspection reveals entire API schema, types, and queries.","explanation":"GraphQL introspection lets anyone discover your full API structure.","recommendation":"Disable introspection in production.","references":"https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/"},
    {"id":"swagger-exposed","type":"body-pattern","title":"API Documentation Publicly Accessible","category":"information-disclosure","severity":"MEDIUM","description":"Swagger/OpenAPI documentation found exposed.","evidence":"References to /swagger, /api-docs, or openapi.json detected.","riskImpact":"API docs reveal all endpoints, parameters, and data models.","explanation":"Public API documentation helps attackers understand your entire API surface.","recommendation":"Restrict API docs access to authenticated users.","references":"https://owasp.org/API-Security/"},
    {"id":"wp-version-exposed","type":"body-pattern","title":"WordPress Version Exposed","category":"information-disclosure","severity":"LOW","description":"WordPress version number found in page source.","evidence":"WordPress version meta tag or generator tag detected.","riskImpact":"Version info helps attackers find known vulnerabilities.","explanation":"WordPress adds version info to meta tags and script URLs by default.","recommendation":"Remove version info with remove_action('wp_head', 'wp_generator').","references":"https://developer.wordpress.org/plugins/security/"},
    {"id":"php-version-header","type":"header-present","title":"X-PHP-Version Header Exposed","category":"headers","severity":"LOW","description":"PHP version disclosed via response header.","evidence":"X-Powered-By: PHP/ or similar header detected.","riskImpact":"PHP version helps target known vulnerabilities.","explanation":"PHP can expose its version in response headers.","recommendation":"Set expose_php = Off in php.ini.","references":"https://www.php.net/manual/en/ini.core.php#ini.expose-php","headerName":"x-powered-by"},
    {"id":"aws-metadata","type":"body-pattern","title":"AWS Metadata Endpoint Reference","category":"information-disclosure","severity":"CRITICAL","description":"Reference to AWS metadata endpoint (169.254.169.254) detected.","evidence":"AWS metadata IP found in page source.","riskImpact":"SSRF to metadata endpoint can steal IAM credentials.","explanation":"The AWS metadata service provides instance credentials and secrets accessible from within the instance.","recommendation":"Block metadata access from applications; use IMDSv2.","references":"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html"},
    {"id":"error-page-info","type":"body-pattern","title":"Verbose Error Page Information","category":"information-disclosure","severity":"MEDIUM","description":"Detailed error information exposed in response.","evidence":"Stack traces, SQL errors, or framework error pages detected.","riskImpact":"Error details reveal file paths, database structure, and code.","explanation":"Verbose error pages leak implementation details useful for attacks.","recommendation":"Use custom error pages; log details server-side only.","references":"https://owasp.org/www-community/Improper_Error_Handling"},
    {"id":"git-exposed","type":"body-pattern","title":".git Directory Potentially Exposed","category":"information-disclosure","severity":"HIGH","description":"References to .git directory found.","evidence":".git/ path or git metadata detected.","riskImpact":"Exposed .git allows downloading entire source code history.","explanation":"If .git is accessible, attackers can reconstruct your entire repository.","recommendation":"Block access to .git directory in web server config.","references":"https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/05-Enumerate_Infrastructure_and_Application_Admin_Interfaces"},
    {"id":"env-file-exposed","type":"body-pattern","title":".env File Reference Detected","category":"information-disclosure","severity":"CRITICAL","description":"References to .env file found in page source.","evidence":".env file path or content detected.","riskImpact":"Exposed .env files contain database credentials, API keys, and secrets.","explanation":".env files should never be web-accessible as they contain all application secrets.","recommendation":"Block .env access in web server; move secrets to environment variables.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"backup-files","type":"body-pattern","title":"Backup File References Detected","category":"information-disclosure","severity":"MEDIUM","description":"References to backup files found.","evidence":"References to .bak, .old, .orig, or .save files detected.","riskImpact":"Backup files may contain source code or database dumps.","explanation":"Backup files left on servers can expose previous versions of code with known vulnerabilities.","recommendation":"Remove backup files from production servers.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"sql-error-messages","type":"body-pattern","title":"SQL Error Messages Exposed","category":"information-disclosure","severity":"HIGH","description":"SQL error messages found in response.","evidence":"Database error messages detected in page output.","riskImpact":"SQL errors reveal database type, table names, and query structure.","explanation":"Unhandled SQL errors expose database internals useful for SQL injection.","recommendation":"Catch database errors and show generic messages to users.","references":"https://owasp.org/www-community/attacks/SQL_Injection"},
    {"id":"path-traversal-patterns","type":"body-pattern","title":"Path Traversal Patterns Detected","category":"content","severity":"HIGH","description":"Path traversal sequences found in URLs or parameters.","evidence":"../ or ..%2f patterns detected.","riskImpact":"Path traversal can access files outside the web root.","explanation":"Unvalidated file path inputs allow reading arbitrary server files.","recommendation":"Validate and canonicalize all file paths; use allowlists.","references":"https://owasp.org/www-community/attacks/Path_Traversal"},
    {"id":"insecure-websocket","type":"body-pattern","title":"Insecure WebSocket Connection (ws://)","category":"content","severity":"MEDIUM","description":"WebSocket connections using ws:// instead of wss://.","evidence":"ws:// WebSocket URLs found.","riskImpact":"Unencrypted WebSocket traffic can be intercepted.","explanation":"Like HTTP vs HTTPS, ws:// is unencrypted while wss:// uses TLS.","recommendation":"Use wss:// for all WebSocket connections.","references":"https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API"},
    {"id":"svg-script-injection","type":"body-pattern","title":"SVG With Embedded Script","category":"content","severity":"HIGH","description":"SVG images containing script elements detected.","evidence":"SVG with <script> or event handlers found.","riskImpact":"SVG scripts execute in the context of the hosting page.","explanation":"SVG files can contain JavaScript that executes when rendered inline.","recommendation":"Sanitize SVGs before inline rendering; serve with Content-Type: image/svg+xml.","references":"https://owasp.org/www-community/attacks/xss/"},
    {"id":"base-tag-injection","type":"body-pattern","title":"Base Tag Present (Potential Hijacking)","category":"content","severity":"MEDIUM","description":"HTML <base> tag detected that could redirect relative URLs.","evidence":"<base href> tag found in page.","riskImpact":"A malicious base tag redirects all relative URLs to attacker's domain.","explanation":"The <base> tag changes the base URL for all relative links and resource loads.","recommendation":"Avoid using <base> tag; if needed, validate it server-side.","references":"https://html.spec.whatwg.org/multipage/semantics.html#the-base-element"},
    {"id":"crlf-injection","type":"body-pattern","title":"CRLF Injection Patterns","category":"content","severity":"HIGH","description":"Potential CRLF injection vectors detected.","evidence":"%0d%0a or \\r\\n patterns in URLs or parameters.","riskImpact":"CRLF injection can split HTTP responses, enabling header injection.","explanation":"Carriage return and line feed characters can inject additional HTTP headers.","recommendation":"Sanitize user input; strip CR/LF characters from header values.","references":"https://owasp.org/www-community/vulnerabilities/CRLF_Injection"},
    {"id":"clickjack-frameable","type":"body-pattern","title":"Page Is Frameable (No X-Frame-Options)","category":"content","severity":"MEDIUM","description":"Page can be embedded in frames without restriction.","evidence":"No X-Frame-Options or frame-ancestors CSP detected.","riskImpact":"Clickjacking attacks can trick users into unintended actions.","explanation":"Without frame protection, your page can be overlaid with invisible click targets.","recommendation":"Set X-Frame-Options: DENY or use CSP frame-ancestors.","references":"https://owasp.org/www-community/attacks/Clickjacking"},
    {"id":"cors-origin-reflection","type":"body-pattern","title":"CORS Origin Reflection","category":"headers","severity":"HIGH","description":"Server reflects the Origin header in Access-Control-Allow-Origin.","evidence":"ACAO header reflects arbitrary origins.","riskImpact":"Any website can make authenticated cross-origin requests.","explanation":"Reflecting the Origin header is nearly as dangerous as using a wildcard with credentials.","recommendation":"Whitelist specific trusted origins.","references":"https://portswigger.net/web-security/cors"},
    {"id":"sensitive-form-get","type":"body-pattern","title":"Sensitive Form Using GET Method","category":"content","severity":"MEDIUM","description":"Forms with sensitive fields using GET method.","evidence":"Login or payment form using method=GET.","riskImpact":"GET parameters appear in URLs, browser history, and server logs.","explanation":"Sensitive data in GET requests is logged in browser history, server logs, and referrer headers.","recommendation":"Use POST method for forms handling sensitive data.","references":"https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url"},
    {"id":"unvalidated-redirect","type":"body-pattern","title":"Unvalidated Redirect Parameter","category":"content","severity":"MEDIUM","description":"URL parameters that control redirects detected.","evidence":"redirect=, return_to=, next=, or url= parameters found.","riskImpact":"Open redirects enable phishing by abusing trusted domain.","explanation":"URL parameters that control redirects can be manipulated to redirect to malicious sites.","recommendation":"Validate redirect destinations against an allowlist.","references":"https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html"},
    {"id":"cors-null-origin","type":"body-pattern","title":"CORS Allows null Origin","category":"headers","severity":"HIGH","description":"Server allows null origin in CORS.","evidence":"Access-Control-Allow-Origin: null detected.","riskImpact":"null origin can be spoofed via sandboxed iframes.","explanation":"Allowing null origin is exploitable because iframes with sandbox attribute send null origin.","recommendation":"Never whitelist null origin in CORS.","references":"https://portswigger.net/web-security/cors"},
    {"id":"missing-viewport-meta","type":"body-pattern","title":"Missing Viewport Meta Tag","category":"content","severity":"LOW","description":"Page lacks viewport meta tag for responsive design.","evidence":"No <meta name=\"viewport\"> tag found.","riskImpact":"Page may not render properly on mobile devices.","explanation":"Without viewport meta, browsers use desktop rendering which can expose UI redress vulnerabilities.","recommendation":"Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.","references":"https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag"},
    {"id":"lazy-loading-missing","type":"body-pattern","title":"Images Without Lazy Loading","category":"content","severity":"LOW","description":"Images lack loading=\"lazy\" attribute.","evidence":"<img> tags without loading attribute detected.","riskImpact":"All images load immediately, increasing bandwidth and page load time.","explanation":"Lazy loading defers off-screen image loading, improving performance.","recommendation":"Add loading=\"lazy\" to below-the-fold images.","references":"https://web.dev/browser-level-image-lazy-loading/"},
    {"id":"input-no-maxlength","type":"body-pattern","title":"Text Inputs Without maxlength","category":"content","severity":"LOW","description":"Text input fields lack maxlength attribute.","evidence":"<input type=\"text\"> without maxlength detected.","riskImpact":"Unbounded input can cause buffer issues or database overflows.","explanation":"Without maxlength, users can submit arbitrarily long strings.","recommendation":"Set appropriate maxlength on all text inputs.","references":"https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength"},
    {"id":"http-method-override","type":"body-pattern","title":"HTTP Method Override Header Detected","category":"configuration","severity":"MEDIUM","description":"X-HTTP-Method-Override or similar headers detected.","evidence":"Method override headers found.","riskImpact":"Can bypass access controls that check HTTP methods.","explanation":"Method override headers tell the server to treat the request as a different HTTP method.","recommendation":"Disable method override in production; enforce methods at the router level.","references":"https://owasp.org/www-project-web-security-testing-guide/"},
    {"id":"access-control-expose","type":"body-pattern","title":"Access-Control-Expose-Headers Too Broad","category":"headers","severity":"LOW","description":"CORS exposes sensitive headers to JavaScript.","evidence":"Access-Control-Expose-Headers includes sensitive headers.","riskImpact":"Exposed headers may leak security tokens or internal data.","explanation":"This header controls which response headers are accessible to JavaScript.","recommendation":"Only expose headers that client-side code actually needs.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers"},
    {"id":"feature-policy-missing","type":"header-missing","title":"Feature-Policy/Permissions-Policy Incomplete","category":"headers","severity":"LOW","description":"Feature policy does not restrict sensitive features.","evidence":"Permissions-Policy missing camera, microphone, or geolocation restrictions.","riskImpact":"Iframes and scripts can access device features without restriction.","explanation":"Feature policy controls which browser features can be used by embedded content.","recommendation":"Set Permissions-Policy to restrict camera, microphone, geolocation, and payment.","references":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy","headerName":"permissions-policy"},
    {"id":"cdn-cache-poisoning","type":"body-pattern","title":"Potential Cache Poisoning Vectors","category":"configuration","severity":"MEDIUM","description":"Unkeyed headers that could enable cache poisoning detected.","evidence":"Vary header missing or X-Forwarded-Host reflected.","riskImpact":"Cache poisoning serves malicious content to all users.","explanation":"If caches don't key on all input-affecting headers, attackers can poison cached responses.","recommendation":"Include all relevant headers in Vary; validate Host and X-Forwarded-* headers.","references":"https://portswigger.net/web-security/web-cache-poisoning"},
    {"id":"trace-method-enabled","type":"body-pattern","title":"HTTP TRACE Method Potentially Enabled","category":"configuration","severity":"MEDIUM","description":"TRACE method may be enabled on the server.","evidence":"Server allows TRACE method or reflects request body.","riskImpact":"TRACE can be used for Cross-Site Tracing (XST) attacks.","explanation":"TRACE echoes the request back, potentially revealing cookies and auth headers.","recommendation":"Disable TRACE method on the web server.","references":"https://owasp.org/www-community/attacks/Cross_Site_Tracing"},
    {"id":"ssrf-indicators","type":"body-pattern","title":"SSRF Indicator Patterns","category":"content","severity":"HIGH","description":"URL parameters that accept full URLs detected.","evidence":"Parameters accepting URL values (url=, src=, dest=, redirect=) found.","riskImpact":"SSRF can access internal services, cloud metadata, and bypass firewalls.","explanation":"Server-side request forgery occurs when user input controls outbound requests.","recommendation":"Validate and restrict URL inputs; block internal IP ranges.","references":"https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"},
    {"id":"prototype-pollution","type":"body-pattern","title":"Prototype Pollution Vectors","category":"content","severity":"HIGH","description":"JavaScript patterns susceptible to prototype pollution.","evidence":"Object merge/extend with user input or __proto__ references.","riskImpact":"Prototype pollution can lead to XSS, DoS, or privilege escalation.","explanation":"Modifying Object.prototype affects all objects in the application.","recommendation":"Freeze prototypes; validate object keys; use Map instead of plain objects.","references":"https://portswigger.net/web-security/prototype-pollution"},
    {"id":"jwt-in-url","type":"body-pattern","title":"JWT Token in URL Parameters","category":"information-disclosure","severity":"HIGH","description":"JWT tokens passed in URL query strings.","evidence":"JWT pattern (eyJ...) found in URL parameters.","riskImpact":"Tokens in URLs are logged in browser history, server logs, and referrer headers.","explanation":"JWTs should be transmitted in headers, not URLs.","recommendation":"Pass JWT tokens in Authorization header or HttpOnly cookies.","references":"https://tools.ietf.org/html/rfc7519"},
    {"id":"service-worker-scope","type":"body-pattern","title":"Service Worker With Broad Scope","category":"configuration","severity":"MEDIUM","description":"Service worker registered with overly broad scope.","evidence":"Service worker registration with / scope detected.","riskImpact":"A compromised service worker can intercept all site requests.","explanation":"Service workers intercept all fetch requests within their scope.","recommendation":"Limit service worker scope to necessary paths.","references":"https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API"},
    {"id":"local-storage-sensitive","type":"body-pattern","title":"Sensitive Data in localStorage","category":"content","severity":"MEDIUM","description":"JavaScript storing potentially sensitive data in localStorage.","evidence":"localStorage.setItem with token/password/secret keys detected.","riskImpact":"localStorage is accessible to any script on the same origin.","explanation":"Unlike HttpOnly cookies, localStorage data can be stolen via XSS.","recommendation":"Store sensitive data in HttpOnly cookies, not localStorage.","references":"https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html"},
    {"id":"x-debug-header","type":"header-present","title":"X-Debug-Token Header Exposed","category":"headers","severity":"MEDIUM","description":"Debug token header found in response.","evidence":"X-Debug-Token or X-Debug-Token-Link header detected.","riskImpact":"Debug profiler exposes request details, queries, and execution data.","explanation":"Symfony and other frameworks expose debug toolbar tokens via headers.","recommendation":"Disable debug mode in production.","references":"https://symfony.com/doc/current/reference/configuration/web_profiler.html","headerName":"x-debug-token"},
]

existing_ids = {c['id'] for c in data['checks']}
added = 0
for check in new_checks:
    if check['id'] not in existing_ids:
        data['checks'].append(check)
        added += 1

with open(path, 'w') as f:
    json.dump(data, f, indent=2)

print(f"Added {added} new checks. Total: {len(data['checks'])}")
