"use client";

import { AlertTriangle, Check, Copy, Loader2, ScrollText } from "lucide-react";
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

interface AiSummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** True while the /history/[id]/summary request is in flight. */
  loading: boolean;
  /** Set when the request fails or the model returns nothing usable. */
  error: string | null;
  /** The generated summary text once the request resolves. Null until then. */
  summary: string | null;
}

/**
 * Result of the on-demand "Generate AI summary" scan action. Deliberately
 * smaller and plainer than AiVerifyResultModal's severity-accent card: this
 * is a paragraph of prose, not a set of findings with their own severity
 * distribution, so a colored rail + stat bar would be decoration with
 * nothing underneath it.
 */
export function AiSummaryModal({
  open,
  onOpenChange,
  loading,
  error,
  summary,
}: AiSummaryModalProps) {
  const [copied, setCopied] = useState(false);

  function copySummary() {
    if (!summary) return;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        {loading ? (
          <div className="flex items-start gap-3">
            <Loader2
              aria-hidden
              className="mt-0.5 h-5 w-5 shrink-0 animate-spin text-primary"
            />
            <DialogHeader className="min-w-0 text-left">
              <DialogTitle>Summarizing this scan</DialogTitle>
              <DialogDescription>
                Turning the findings into a short, plain-English readout.
                Usually just a few seconds.
              </DialogDescription>
            </DialogHeader>
          </div>
        ) : error ? (
          <>
            <DialogHeader className="text-left">
              <DialogTitle className="flex items-center gap-2">
                <AlertTriangle
                  className="h-5 w-5 text-destructive"
                  aria-hidden="true"
                />
                Couldn&apos;t generate a summary
              </DialogTitle>
              <DialogDescription>{error}</DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button variant="outline" onClick={() => onOpenChange(false)}>
                Close
              </Button>
            </DialogFooter>
          </>
        ) : summary ? (
          <>
            <DialogHeader className="text-left">
              <DialogTitle className="flex items-center gap-2">
                <ScrollText
                  className="h-5 w-5 text-primary"
                  aria-hidden="true"
                />
                AI summary
              </DialogTitle>
              <DialogDescription className="sr-only">
                Plain-English summary of this scan&apos;s results, generated by
                AI.
              </DialogDescription>
            </DialogHeader>
            <p className="rounded-md border border-border bg-muted/30 px-4 py-3 text-sm leading-relaxed text-foreground/90">
              {summary}
            </p>
            <DialogFooter className="gap-2 sm:justify-between">
              <Button
                variant="ghost"
                size="sm"
                onClick={copySummary}
                className="gap-1.5"
              >
                {copied ? (
                  <Check className="h-3.5 w-3.5 text-[hsl(var(--success))]" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                {copied ? "Copied" : "Copy text"}
              </Button>
              <Button onClick={() => onOpenChange(false)}>Close</Button>
            </DialogFooter>
          </>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
