"use client";

import { AlertTriangle, Check, Copy, Loader2, ScrollText } from "lucide-react";
import { useState } from "react";
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { copyToClipboard } from "@/lib/ui/clipboard";

interface AiSummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** True while the /history/[id]/summary request is in flight. */
  loading: boolean;
  /** Set when the request fails or the model returns nothing usable. */
  error: string | null;
  /** The generated summary text once the request resolves. Null until then. */
  summary: string | null;
}

/**
 * Result of the on-demand "Generate AI summary" scan action. Deliberately
 * smaller and plainer than AiVerifyResultModal's severity-accent card: this
 * is a paragraph of prose, not a set of findings with their own severity
 * distribution, so a colored rail + stat bar would be decoration with
 * nothing underneath it.
 */
export function AiSummaryModal({
  open,
  onOpenChange,
  loading,
  error,
  summary,
}: AiSummaryModalProps) {
  const [copied, setCopied] = useState(false);

  async function copySummary() {
    if (!summary) return;
    if (await copyToClipboard(summary)) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {/* variant="shell": the model writes as much prose as it likes, so the
          summary is the one band that scrolls, under a fixed title and above a
          Copy button that stays reachable on a short viewport. */}
      <DialogContent variant="shell" size="md">
        {loading ? (
          <>
            <DialogHeader>
              <div className="flex items-center gap-2.5">
                <Loader2
                  aria-hidden
                  className="h-4 w-4 shrink-0 animate-spin text-primary"
                />
                <DialogTitle>Summarizing this scan</DialogTitle>
              </div>
            </DialogHeader>
            <DialogBody>
              <DialogDescription>
                Turning the findings into a short, plain-English readout.
                Usually just a few seconds.
              </DialogDescription>
            </DialogBody>
          </>
        ) : error ? (
          <>
            <DialogHeader>
              <div className="flex items-center gap-2.5">
                <AlertTriangle
                  className="h-4 w-4 shrink-0 text-destructive"
                  aria-hidden="true"
                />
                <DialogTitle>Couldn&apos;t generate a summary</DialogTitle>
              </div>
            </DialogHeader>
            <DialogBody>
              <DialogDescription>{error}</DialogDescription>
            </DialogBody>
          </>
        ) : summary ? (
          <>
            <DialogHeader>
              <div className="flex items-center gap-2.5">
                <ScrollText
                  className="h-4 w-4 shrink-0 text-primary"
                  aria-hidden="true"
                />
                <DialogTitle>AI summary</DialogTitle>
              </div>
              <DialogDescription className="sr-only">
                Plain-English summary of this scan&apos;s results, generated by
                AI.
              </DialogDescription>
            </DialogHeader>
            <DialogBody>
              <p className="rounded-md border border-border bg-muted/30 px-4 py-3 text-sm leading-relaxed text-foreground/90">
                {summary}
              </p>
            </DialogBody>
            <DialogFooter>
              <Button
                variant="ghost"
                size="sm"
                onClick={copySummary}
                className="gap-1.5"
              >
                {copied ? (
                  <Check className="h-3.5 w-3.5 text-[hsl(var(--success))]" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                {copied ? "Copied" : "Copy text"}
              </Button>
            </DialogFooter>
          </>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
